### ISSUE TITLE
[lit-next] Monorepo Suggestion

### ISSUE THREAD

**Issue by daKmoR** [lit/lit#1282]
Suggestion is to replace lerna bootstrap with yarn workspaces (later npm workspaces?) and lerna publish with [changesets](https://github.com/atlassian/changesets).

how the workflow is:
- do code changes
- if you want to release a package do `npm run changeset` which will create a markdown file which includes the content for the changelog for this code change 
- a github action will create/update a merge request which shows all the version bumps and changelogs
- if you want to release for real you merge this "version packages" pull request

we use it in modern web and such an automatic pull request looks like this https://github.com/modernweb-dev/web/pull/579

## Our little history:

In open-wc back then we had about 10 packages and we have been using lerna with npm for about half a year but we had many stability issues as with broken installations or tests just failing without a reason.
We then enabled yarn workspaces which made it stable enough and we use it to this day in open-wc. Still the automatic release via semantic versioning is a little too magical and does not give enough control that's why we looked into alternatives and found changesets. Which we now use happily in lion and modern-web and we will soon change it for open-wc as well.

**Comment by jorenbroekema** [comment]
The biggest selling points of changesets, in my opinion, over something like lerna:
- Mindset of `intent to release`. Only release when you've documented the intent to do so (by doing `npm run changeset` and creating an intent-to-release markdown file, which contains the summary that will show up in the changelog, and whether it's a major, minor or patch bump). Whereas with Lerna, you would specify a file filter, and any change there would result in, at least, a patch, whether you want to or not. So a documentation or comment edit in the src code would release a patch when you might not want this, since that change doesn't require a publish.
- Human readable changelog. With most auto-release tools (standard-version is another example), it's the commit message that is taken as a conventional way to create the changelog. This is nice because you don't have to do things twice: a commit message and a similar changelog entry. But since commit messages are often limited to 72 chars so they are readable fully in the commit history, it severely limits you to writing a human readable changelog entry that is actually useful to people, and I noticed at least personally that changelogs have become more and more useless over the years as people have automated them to rely on commit message. So therefore I really like being able to write a bit more expansive summary of the change and what my users need to know about it.

**Comment by justinfagnani** [comment]
I'm not so inclined to use Yarn - we've used it before and it wasn't enough of an improvement over npm to be worth the additional tools and documentation. Basically everyone has npm installed, and not everyone has Yart. NPM 7 will start having workspace support as well. We do intended to try that out.

I would look into changesets. Hopefully it works with npm. If it doesn't, it furthers my perception about Yarn adding friction and fragmentation.

**Comment by daKmoR** [comment]
changesets hast nothing to do with yarn so that should work fine 👍

workspaces are just so much more stable then the "trickery" that lerna does and as yarn is the only tool supporting it now we use it.
Once npm workspaces are there and if they work equally good then we will very likely switch as well 🤗

PS: I agree if all you use it npm features then yarn is not a significant upgrade... but if workspaces help you then it is a significant improvement.

**Comment by justinfagnani** [comment]
@daKmoR that's good to know. The examples on their repo all used Yarn, and commands like `yarn changesets` which makes it look like a built-in or something, so it was hard to tell.

**Comment by Westbrook** [comment]
Yarn is tricky because it doesn't use the `run` command the way that `npm` does to access scripts and then on top of that gives access to `bin` in that same cli location, so depending on your set up `yarn changesets` can both be a package script of accessing the bin directly...

**Comment by abdonrd** [comment]
I created two PRs to unify the ESLint and Prettier configs in the monorepo:

- https://github.com/Polymer/lit-html/pull/1292
- https://github.com/Polymer/lit-html/pull/1297

**Comment by kevinpschaaf** [comment]
Closing, as we've integrated changesets into our monorepo now, and are reaping the awesome benefits of it!
