### ISSUE TITLE
[lit-element] Unable to create working es bundle with lit-next

### ISSUE THREAD

**Issue by dflorey** [lit/lit#1324]
# Description
With the old release (lit-element 2.3.x) release I've been able to bundle and publish a minified es-module using rollup by reexporting the desired bits and pieces like this:
```
export * from 'lit-element'
export * from 'lit-html'
export * from 'lit-html/directives/if-defined'
export * from 'lit-html/directives/style-map'
export * from 'lit-html/directives/class-map'
export * from 'lit-html/directives/unsafe-html'

```
with the according rollup config:
```
export default {
  input: './index.js',
  output: {
    file: 'esm/lit.min.js',
    sourcemap: false
  },
  plugins: [
    resolve(),
    terser()]
}
```
The bundle enabled me to share the same lit-html instance between different modules of my app loaded at runtime (so that I can mix templates from different modules).

I've tried to build a similar bundle with lit-next, but I've been stuck with an error.
I've added the decorators to the bundle.
```
export * from 'lit-element/lib/decorators'
```
This is the error that I get (using a non-minified bundle):
![image (1)](https://user-images.githubusercontent.com/2938750/94451712-059cd180-01af-11eb-94f9-b748139dfb45.png)

**Comment by justinfagnani** [comment]
@dflorey I can't see the actually error that's being reported.

Note that we're already publishing the minified modules with this release. We've chosen minifier parameters that we know are optimal and safe for our codebase, so I would recommend using our production build. For example, your terser invocation probably won't minify our private property names like ours does.

You also shouldn't need to create a custom bundle to share lit-html across multiple modules. `npm dedupe` usually ensure that you have the same instance.

**Comment by dflorey** [comment]
Sorry for the missing info! The actual error msg has been "directiveCtor is not a constructor" (or something along those lines, forgot to copy paste).
If I find the time I'll dig into this again- after sleeping over it I think I'll have to check once again if an old directive from a 3dr party lib (e.g. lit-translate) caused this issue. Strangely it did not pop up when bundling lit@next with my app, only when dynamically loading the generated es module at runtime.

Let me explain, why I created the bundle in the first place:
My app can be extended by users by loading es modules at runtime (e.g. from unpkg). I'm then loading the extensions using
`await import(moduleUrl)`.
I had to make sure that extensions don't bundle lit to be able to consume templates provided by the extensions.
As I don't know the modules at compile/bundle time so I cannot use `npm dedupe`. As both my app and the extensions consume the same lit es module (by importing it from unpkg at runtime) it works fine.
For performance reasons it would be great to have a single minified lit-bundle containing all the used directives etc.
Hope this makes sense...

**Comment by kevinpschaaf** [comment]
Based on your screenshot, it looks like you're passing a lit-html 1.x directive implementation to the `lit-next` `directive()` factory:

![image.png](https://images.zenhubusercontent.com/5afdd6514b5806bc2bd39b97/95f4b3d7-c478-4c88-bf97-1b139b68204c)

Note that directive _authoring_ is one of the major breaking changes in `lit-next`. There is a small migration guide here in the README: https://github.com/Polymer/lit-html/tree/lit-next/packages/lit-html#-migrating-directives. You'll need to re-write any custom directives using the new `class MyDirective extends Directive` syntax, implement state as simple fields on the directive class instance rather than using WeakMaps, etc.

We'll add an issue to add a better warning message in dev mode to give a better warning, since this will likely be a common mistake/oversight when migrating.

Hope that helps.

**Comment by dflorey** [comment]
Thank you! That's appreciated, especially when migrating large apps with 3rd party directives.
