### ISSUE TITLE
[infra] Re-enable Edge tests

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#1527]
@rictic to recommend which version to use

**Comment by rictic** [comment]
Useragent: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063

Version: 40.15063.0.0

**Comment by kevinpschaaf** [comment]
Noting that although we want to enable Edge 15 to match internal browser config, Edge 18 fails due to use of `globalThis`, which the web-test-runner `legacyPlugin` doesn't include for Edge due to using a `'noModule' in HTMLScriptEleemnt` feature detection for loading CoreJS: https://github.com/modernweb-dev/web/issues/1265.

Edge 15 should not have this issue however since it does not have module support.

**Comment by justinfagnani** [comment]
Does this matter anymore?

**Comment by rictic** [comment]
I believe that the original reason for this bug no longer matters
