### ISSUE TITLE
[ssr] Pre-rendering demo in ssr 

### ISSUE THREAD

**Issue by baboonmaj** [lit/lit#1715]
Thank you for releasing `lit 2.0.0-pre.2` along with `ssr` support !!!

I was trying to work out a case where given some data I would like to generate a `html string` containing events and nested lit-elements for rendering it on a browser later.

I was trying to modify the demo code provided in the package `@lit-labs/ssr` which uses a `koa` server to generate the html.
I. Is it possible to pre-render using the same approach but without a server ? and can a small demo code be provided for pre-rendering as well just like ssr ?

any help or little hand-holding will be of great help

**Comment by thescientist13** [comment]
The server is only incidental in this case as that demo actually just passes the rendered result (a stream) to Koa based on an HTTP request.

Basically, you could just use the filesystem to loop through a bunch of HTML files and SSR the HTML and JS that way, and then instead of the middleware approach, just write the `ssrResult` to a file (e.g. _index.html_) on disk instead.

**Comment by aomarks** [comment]
Check out https://github.com/lit/lit/tree/main/packages/labs/eleventy-plugin-lit for an example of how you can use Lit SSR for a pre-rendering use-case. Or if you're using Eleventy, you could directly use that plugin.
