### ISSUE TITLE
[TypeScript]: register component once

### ISSUE THREAD

**Issue by lbenie** [lit/lit#1812]
# Description

When importing components that use the `@customElement` decorator. Sometimes, they are already defined (used) before in some other component. This throws an error and the error is not handled.

# Steps to Reproduce

1. Write this code

```ts
import ComponentA from './componentA';

render(html`<component-a></component-a>`, document.body);
```

2. See this output...

## Live Reproduction Link

https://stackblitz.com/edit/lit-html

## Expected Results

Possible solutions:

1. Try/catch around the `customElement.define` function and catch the error
2. check if the component already exists in the registry, otherwise define it
	```ts
		const customElement = (tagName: string) => {
			// this ensures it's only defined once in the registry and allows re-use
			if (!customElement.get(tagName)) {
				customElement.define(tagName, ...)
			}
		}
	```

## Actual Results

`NotSupportedError`
> The CustomElementRegistry already contains an entry with the same name or the same constructor (or is otherwise already defined)

## Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by kevinpschaaf** [comment]
We generally consider the current error a good one. The currently spec'ed custom elements registry is global, and so that means only one definition of a component for a given tag name can exist on the page, although there is active work on standardizing [Scoped Custom Element Registries](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Scoped-Custom-Element-Registries.md) to deal with this (and [@lit-labs/scoped-registry-mixin](https://www.npmjs.com/package/@lit-labs/scoped-registry-mixin) gives a preview of how that might look in Lit).

In the meantime, we believe the default behavior should be that the user knows they are violating the one-definition-one-tag rule in the global registry, because it means one of two things:
1. You are trying to use two different components registered against the same tag name in an application, which is an error condition. Since each callsite expects to be using different elements (or two different versions of an element), silently choosing the first one would still result in a broken program (despite avoiding the `NotSupportedError`)
1. Your build setup is somehow allowing the same component source to be duplicated in your application, which is wasteful. Normally, module-loading semantics (either in bundlers or natively in the browser) dedupe, such that modules that define elements can be imported my multiple call sites without duplication. Duplication can happen when elements are distributed as bundles rather than modules (which defeats de-duplication), which is why we recommend _not_ publishing reusable elements with bundled dependencies. 

Note, `npm dedupe` can help ensure only one version of a semver-compatible element is being installed in your application. If your application is calling for two non-semver-compatible versions of the same element, then you're back in case (1), where choosing the first one registered is not a generally safe solution.

For these reasons, we're unlikely to change the default behavior of the `customElement` decorator, since we feel surfacing the two error conditions is important.

If you really want to work around this in your own application, you could make your own version of the decorator (it's trivial in TS) and alias it using e.g. [@rollup/plugin-alias](https://www.npmjs.com/package/@rollup/plugin-alias) or the equivalent for your build chain.

**Comment by lbenie** [comment]
@kevinpschaaf thanks for the explanation.
I agree with what you said, I was wondering what was lit's stance on it.

I already monkey patched the decorator as you suggested, it's trivial. I was wondering if "longer-term" there was a better solution.

I'll keep an eye on the scoped-registry-mixin :).

Thanks again!
