### ISSUE TITLE
[ssr] `<?>` element rendered with nested lit template

### ISSUE THREAD

**Issue by aomarks** [lit/lit#1818]
Input:

```js
import { render } from "@lit-labs/ssr/lib/render-with-global-dom-shim.js";
import { html } from "lit";

const who = html`<b>World</b>`;
const hello = html`Hello ${who}`;
const res = render(hello);
for await (const value of res) {
  process.stdout.write(value);
}
```

Result:

```html
<!--lit-part bvCHCwwjhws=-->Hello <!--lit-part usEl6FeaGlw=--><b>World</b><!--/lit-part--><?><!--/lit-part-->
                                                                                          ^^^
```

**Comment by kevinpschaaf** [comment]
Turns out `<?>` is a super-shorthand for way to get the browser to parse a comment node that @justinfagnani discovered; `<?` starts a processing instruction, which then gets parsed into a comment `<!--?-->`. So it's just a slight byte-savings over `<!---->` for a literal string representing a comment. Where it's used in the core, we just need to ensure an end node exists for a part, and don't care about its contents.

Is this causing a problem? Or did it just look like a bug? We can change it to `<!---->` if needed.

**Comment by aomarks** [comment]
> Turns out `<?>` is a super-shorthand for way to get the browser to parse a comment node that @justinfagnani discovered; `<?` starts a processing instruction, which then gets parsed into a comment `<!--?-->`. So it's just a slight byte-savings over `<!---->` for a literal string representing a comment. Where it's used in the core, we just need to ensure an end node exists for a part, and don't care about its contents.

Oh! Cool, TIL.

> Is this causing a problem? Or did it just look like a bug? We can change it to `<!---->` if needed.

Nope, I just thought it looked suspicious. Thanks for the info, closing.
