### ISSUE TITLE
Reflect lit element defined properties for designer

### ISSUE THREAD

**Issue by jogibear9988** [lit/lit#1864]
Hello,
I'm working on a universal HTML Designer application (https://github.com/node-projects/web-component-designer demo: https://node-projects.github.io/web-component-designer-demo/index.html)

in wich I'd also like to support lit-elements (especially reading out the properties of them).

If the Properties are defined in the static properties field, I could read them with this code: https://github.com/node-projects/web-component-designer/blob/master/src/elements/services/propertiesService/services/AbstractBasePropertiesService.ts

but is there also a way to get the properties defined by the @properties decorator?

**Comment by jogibear9988** [comment]
With this code: https://github.com/node-projects/web-component-designer/blob/master/src/elements/services/propertiesService/services/Lit2PropertiesService.ts

I get now the properties for exampke when I use the https://github.com/rough-stuff/wired-elements (wich also use lit)

But for Material Components Web Components I still get no properties.

**Comment by jogibear9988** [comment]
Is this the right solution:

Object.getPrototypeOf($0.constructor)
and the use:
_classProperties ?

I need to know whats the correct way for each version of lit, so I could display the properties in my designer

**Comment by justinfagnani** [comment]
Yeah, you can read `_classProperties`, though because that's a private property we rename it in the production builds.

That would also only include `@property` annotated properties. While that se indeed the easily declared reactive properties, they're not the only public settable properties that a component may have. Any field or attribute may something a designer needs to use. It's common to implement getters and setters that effect rendering too.

I'd be more inclined to either read a public interface from a [custom-elements-manifest](https://github.com/webcomponents/custom-elements-manifest) than a live element, or just read properties from the prototype. Then you don't need to build an instance inspector for each web component library and you support vanilla elements.

**Comment by jogibear9988** [comment]
I can read them from the Prototype, but I need additional Infos.
For example the Property could be an enum. If you use the TypeScript enum as Type (at least in polymer and my component), i will use the values of it for a dropdown.
I also support that you write your own PropertiesService, wich could use a manifest.
(see https://github.com/node-projects/web-component-designer-demo/blob/master/src/services/customPropertiesService.ts)

Maybe lit (google) could evolve a standard how a manifest for a webcomponent would look like? So every webcomponent author would do it the same way?

**Comment by jogibear9988** [comment]
I'm such an idiot, you already linked to the file format https://github.com/webcomponents/custom-elements-manifest
;-) sorry

**Comment by jogibear9988** [comment]
I've already created an issue at it, that I would like to see the enum values in the manifest

**Comment by jogibear9988** [comment]
@justinfagnani and a last question
https://github.com/Polymer/designer is dead, or? is there smth. similar in the works, or is it a good decision to work on my own?

**Comment by sorvell** [comment]
Closing based on the discussion above. If there are still questions related to this please open a new issue. There's no active work happening on a Lit designer for what it's worth.
