### ISSUE TITLE
SSR bug in Chrome only

### ISSUE THREAD

**Issue by shakyShane** [lit/lit#1872]
# Description

I tried to SSR + hydrate a simple html shell + a button element. in Chrome only, the HTML for the `<app-button>` element is duplicated once the JS kicks in. This does not happen in Brave or Safari

**Edit**: Looks like the reason this appears to work is that the other browser do not support the same feature set at chrome - the SSR'd elements do not show on those browsers without JS

# Steps to Reproduce

I made a minimal example: 

https://github.com/shakyShane/lit-ssr-bug

## Expected Results

No duplicated DOM

## Actual Results

Duplicated DOM in chrome (left). Safari (middle) and Brave (right) does not have this issue.

![image](https://user-images.githubusercontent.com/1643522/117821769-d03b8480-b263-11eb-8d07-6d46bc77abb8.png)

## Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by shakyShane** [comment]
Ok, so this is a problem with esbuild. I've switched to webpack and the issue is resolved... I hope this helps someone else :)

**Comment by martinfojtik** [comment]
@shakyShane How exactly did you manage to fix this problem? I am using Webpack but still have duplicated content in Chrome.

**Comment by shakyShane** [comment]
@martinfojtik I just make sure the first line in the initial bundle is 

```js
import "lit/experimental-hydrate-support.js";
```

**Comment by e111077** [comment]
Seen this problem before in Astro. The ssr helper polyfills are being loaded after the `lit` import. This means that when the component hydrates it simply appends the hydrated template since lit has not yet gotten the polyfill that tells it to hydrate the template instead

**Comment by kevinpschaaf** [comment]
Closing for now, since I think the important point from this issue is documented in the readme: https://github.com/lit/lit/tree/main/packages/labs/ssr#hydrating-litelements
> To hydrate LitElement shadow roots, load the lit/hydrate-support.js module... This module should be loaded before the lit module is loaded, to ensure hydration support is properly installed.

We clearly need a lot more SSR docs and higher-level API's and patterns for users to follow, but this will come as SSR matures.

**Comment by DannyMoerkerke** [comment]
How is this supposed to work with the Koa example on the lit website?
I forked it and now run into the problem  that when the hydration data is coming from an api the element is rendered twice again.

In this example I simulate the api delay with `setTimeout`. How do I fix this?

https://stackblitz.com/edit/lit-ssr-global-ziy5z1

**Comment by e111077** [comment]
Heya I answered Danny's question on Twitter but posting it here as well for anyone that comes across this issue:

In the example above, there is an error thrown in the lit experimental-hydrate package because there is a mismatch in the state of the `data` reactive property on the server and at hydration time. There are generally 3 solutions in no particular order:

1. Make sure the data is available statically at hydration time
2. Make sure the data is available before element upgrade
3. Use the `defer-hydration` attribute to defer hydration until you have set the state on the client

### Make sure the data is available statically at hydration time

A way to do this is to set all the data bound to elements statically by serializing all the data bindings as attributes. In the case above, Danny is doing `.data=${data}` in lit-html on the server. An option is to SSR render data as an attribute like so `data=${JSON.stringify(data)}`.

This means that the element can then upgrade and have state ready by first render via Lit Reactive Property Attribute Conversion

### Make sure the data is available before element upgrade

In the case above, the example:

1. loads lit hydration helpers
2. loads element definitions
3. gets a reference to the element and updates the `data` property like so:

```ts
setTimeout(() => {
  greeter.data = [{ name: 'John' }, { name: 'Jane' }];
});
```

To make sure that the data matches before hydration, updating the data property (3) can be done before loading the element definitions (2) since [Lit will not override any properties set on the element at upgrade time](https://github.com/lit/lit/blob/77544071eaed1c0bbf0447b9faa316dd244094c9/packages/reactive-element/src/reactive-element.ts#L984-L1007).

### Use the `defer-hydration` attribute to defer hydration until you have set the state on the client

Lit SSRs `defer-hydration` attribute will defer hydration until the attribute is removed. So, in the SSR template, one can render `<my-greeter defer-hydration .data=${data}>`.

Then on the client, you can synchronize the state with the server at your leisure and remove the `defer-hydration` attribute once the properties have been set. e.g.

```ts
await import('/node_modules/lit/experimental-hydrate-support.js');
import('./src/components/simple-greeter.js');
const greeter = document.querySelector('simple-greeter');
greeter.data = [{ name: 'John' }, { name: 'Jane' }];
greeter.removeAttribute('defer-hydration');
```
