### ISSUE TITLE
No compatibility: lit-html v2 TemplateResult inside lit-html v1 TemplateResult

### ISSUE THREAD

**Issue by Knorgias** [lit/lit#1900]
# Description

{ LitElement } imported from  lit is expected to be compatible with { html } from 'lit-element'. That is not the case, it seems.

# Steps to Reproduce

1. Write this code
```js
import { html } from 'https://jspm.dev/lit'; 

// fails with lit-element 2.x
import { html as htmlPrev, LitElement as PrevLitElement } from 'https://jspm.dev/lit-element'; 

export class MyPreview extends PrevLitElement {
  render() {
    return htmlPrev`
      <div>Preview context (prev lit):<br/> ${html`<span>new lit</span>`}</div>
      <br/><br/>
      window.litHtmlVersions:</br>
      ${window.litHtmlVersions.join(', ')}
    `;
  }
}

customElements.define("my-preview", MyPreview);
```

2. See this output...

## Live Reproduction Link

https://webcomponents.dev/edit/hYCBikhyOF3NGrSFd6cw/src/index.js

## Expected Results

Expected output:
```
Preview context (prev lit):
new lit
```

## Actual Results

The output given is:

```
Preview context (prev lit):
[object Object]
```

**Comment by justinfagnani** [comment]
This is working as expected. Because we use `instanceof` to check for TemplateResult objects in lit-html 1.x, we can only render those that are produced from the same copy of the library that's receiving them. In lit-html 2.x we check for a special property, so going forward different copies are interoperable, but not going back to lit-html 1.x.

**Comment by Knorgias** [comment]
Thanks for the feedback!
