### ISSUE TITLE
Question about ifDefined behavior change in lit 2.0

### ISSUE THREAD

**Issue by bschlenk** [lit/lit#1927]
It looks like in lit 2, [`ifDefined` has been changed](https://github.com/lit/lit/blob/main/packages/lit-html/src/directives/if-defined.ts#L15) to handle both `null` and `undefined`, instead of only `undefined` like in lit-html. Is this correct? If so, I think it would be helpful if a blurb about this change was added to the [upgrade guide](https://lit.dev/docs/releases/upgrade/). It's certainly a helpful change for me, I can remove my `ifNotNull` custom directive and use `ifDefined` directly. But I only realized this by accident.

I'm also curious about how `ifDefined` is implemented as a function. I don't see any documentation on how to implement a `function` directive vs. a `class` directive on the new docsite. I'm guessing this just conforms to the function that would be returned by [wrapping a class with `directive`](https://github.com/lit/lit/blob/72877fd1de43ccdd579778d5df407e960cb64b03/packages/lit-html/src/directive.ts#L81-L86). Is writing a custom directive this way "officially" supported?

**Comment by kevinpschaaf** [comment]
The key change in 2.0 is that rendering `nothing` to an attribute position now causes the attribute to be removed. Previously, there was no way for a _value_ to cause an attribute to be removed; the only way was use `directive`'s ability to get access to the underlying DOM and call `removeAttribute`, which is what the previous implementation of `ifDefined` did.

The above change now then means that `ifDefined` in 2.0 can be implemented as a simple functional transform of a nullish value to `nothing`, rather than needing to be an actual directive that access the DOM. And you're correct that we do a nullish test (`value ?? nothing`) rather than a strict undefined test.

Both were intentional changes, but it looks like we did indeed miss these two changes in the upgrade guide, so we'll leave this issue open to correct the upgrade guide:
* Rendering the value `nothing` to an attribute expression causes the attribute to be removed (when an attribute has multiple expressions in it, _any_ value of `nothing` will cause the entire attribute to be removed)
* `ifDefined` in an attribute expression will cause the attribute to be removed for both `null` and `undefined`
