### ISSUE TITLE
Question: Any way to render on nested property change?

### ISSUE THREAD

**Issue by tstewart-klaudhaus** [lit/lit#1938]
Let's say I make an address component, which takes an object property with street and suburb keys, each with a string value.

Currently, if I change the object identity of the property itself, the component will be re-rendered, but if I change (from somewhere else in the app) just the value of the street key of the property, no render is triggered.

Is there a recommended approach to have a component watch the inner value of a property rather than just its reference identity?

EDIT: Note: similar scenario happens when trying to add extra options to the array property of a dropdown component, for example.

**Comment by davidhicks980** [comment]
Please tell me if I misunderstood, but I think you can use a 'hasChanged' function when defining a new property within your component. Ideally, you would actually want to define two separate primitives in your component (two strings called street and suburb), as it makes diffing a lot easier (if you had huge objects, it could hurt performance if you diffed on every property change). 

You can see an example on the Lit playground page: 
https://lit.dev/playground/#sample=examples/properties-has-changed

If you do want to use an object though, I think this example may be helpful.
 ```
interface Address {
  street: string;
  suburb: string;
}

@customElement('address-component')
export class AddressComponent extends LitElement {
  @property({
    type: Object,
    hasChanged: (currentAddress?: Address, previousAddress?: Address) => {
      return !(currentAddress?.street === previousAddress?.street);
    },
  })
  address?;

  firstUpdated(_changedProperties) {
    this.address = { street: '111 11 street', suburb: 'somewhere in canada' };
  }
  render() {
    return html` <input
        @input="${(e) => {
          this.address.street = e.target.value;
        }}"
      />
      <span>${this.address?.street}</span>`;
    }
} 
```
Please let me know if this is not what you were looking for! Hopefully we can find the answer if so. Also, keep in mind that when assigning an object in the template, you don't have to put quotes around it: 
![image](https://user-images.githubusercontent.com/59215665/120523784-556a1300-c3a4-11eb-9683-3586359a5798.png) 

It threw me off the first time I had to use objects as properties. 

Anyways, good luck!! David

**Comment by tstewart-klaudhaus** [comment]
Thanks for taking the time to look at this David. I've done a bit of investigation of the `hasChanged` function, and it doesn't seem to work quite the way you're suggesting. From the lit.dev documentation:

> `hasChanged()`
>
> Called when a reactive property is set. ...

It is only called when the value of the property itself is set (i.e. to a different object entirely), so it can only serve to "filter out" renders, making them _less_ rather than _more_ granular. I have done a few code experiments to confirm this, I'm in the process of tidying and documenting them and will post here once complete.

There is another component lifecycle method called `requestUpdate`, which can imperatively trigger an update cycle, however this would require setting up some sort of watcher on the object's properties when it is first set, and each time it is reset.

Thanks again for your input.

**Comment by davidhicks980** [comment]
OH if you want to update whenever the object is set, you could just return 'true' from the hasChanged function... albeit I feel oddly guilty whenever I do it. I made a stackblitz this time, but it does use lit-element because that was a template I had saved. Should work about the same though:

https://stackblitz.com/edit/hgtmpc?file=address-single.js

Is that more like what you are looking for? Also, you were totally right about the requestUpdate! I typed the response up and forgot to add it in. I'll fix it above. 

You may also be able to use a setter, but I think that still requires your new object to pass the 'hasChanged' criteria.

Feel free to take over that stackblitz also!

David

**Comment by justinfagnani** [comment]
Lit has a simple change detection strategy that works by creating accessors for reactive properties. Anything more involved than that requires an entire system to observe objects and collections - which is going to be more opinionated and invasive than we want to be, and possibly unnecessary for a lot of devs who use immutable patterns or statement management libraries.

Right now libraries that allow deep property observation either:
- Patch accessors onto objects as they're used, and patch mutating methods onto common collections like Array, Map, Set (ie, patch Array.push() and Set.add()). We don't want to patch other objects - it's dangerous, slow, and incomplete - we can't possibly know all the mutating methods to patch and Array's can't be fully supported.
- Require that all data object are used via a set of Proxies that serve the same purposes as the patches, but don't modify the underlying object. It's better than patching but doesn't work on IE11, creates a new Proxy object for every object used in the data system, and is also incomplete first due to the same issue with patching, and second because this system can't detect changes that happen outside of the Proxies.
- Rerun all expressions any time anything in the app changes, and know when the world changes by patching all async task creation in the entire DOM API so that you can check the expression list when the tasks complete. This is the zone.js approach, and it's also invasive, incomplete and slow.
- Make you opt-in to special observable objects. These objects do the same work that patching plain data object would, but there's no patching because the objects were design to be observed. MobX is a good example, and [there's a nice mixin for using it with Lit](https://www.npmjs.com/package/@adobe/lit-mobx). This approach doesn't have the downsides of the above if you can use those special objects.

Given that the first three have too many downsides for us, and the last technique already works with Lit, we're keeping our deep change detection simple, and recommend using a thrid-party observer system like MobX. I also hear that Vue's reactivity system, which uses Proxies, can work well with Lit.

**Comment by sorvell** [comment]
Closing based on @justinfagnani's response. Please re-open if further discussion is necessary.
