### ISSUE TITLE
[TypeScript] Using Array<Type> in property decorator returns an error

### ISSUE THREAD

**Issue by Nuciloco** [lit/lit#2004]
# Description
The property decorator for **LitElement** components doesn't seem to accept generic types of **Array** in a certain way.
For example ``Array<String>`` causes **TypeScript** to return with this error:

```
TS1005: '(' expected.
```

If you replace ``Array<String>`` with ``Array<String>()`` instead as far as I tested, **TypeScript** won't return any errors at all.
Either this is intentional and not documented with **Lit**, intentional with **TypeScript**, or is a bug.

# Steps to Reproduce

```ts
@property({type: Array<String>}}
```
This will return this error: ``TS1005: '(' expected.``

However using this code instead:
```ts
@property({type: Array<String>()}}
```
Returns no errors as far as I tested right now.

**Comment by straversi** [comment]
That's because the value of `type` should be a value, not a TypeScript type. The `type` attribute is not used for type-checking, it's used to let Lit know how to convert the attribute string into a JS value. See this [section of the docs](https://lit.dev/docs/components/properties/#conversion-type).

You probably want:

```ts
@property({type: Array}) myProperty: Array<String>;
```

**Comment by kevinpschaaf** [comment]
Closing based on @straversi's excellent answer.
