### ISSUE TITLE
Using templates in html files?

### ISSUE THREAD

**Issue by K1DV5** [lit/lit#2019]
I was looking into how lit-html works and I couldn't find anything on using templates in html files. If lit-html takes the template literals and creates html templates, I think the possibility to use existing templates defined in `<template>` tags in html files would eliminate the first step. And it would allow the template to be editor friendly (syntax highlighting etc., which is what I'm actually interested in) since it is mixed with the other html content.

**Comment by justinfagnani** [comment]
lit-html templates are necessarily JavaScript because the expressions reference JavaScript objects. For a template system to be authored in HTML you need to provide data objects to the template being rendered and have some sort of expression syntax and control flow. lit-html is small in part because it just uses JavaScript for that.

You can however build a in-HTML template system on top of lit-html's core. I have a side project where I've done this called Stampino: https://www.npmjs.com/package/stampino warning it's not production ready and has some API warts, but it's an example of what can be done with Lit 2.

If you're looking for syntax highlighting, there are plugins for various editors like VS Code. [lit-plugin](https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin) provides syntax highlighting, code completion, linting, hover-over docs and more.
