### ISSUE TITLE
details element with default `open` state fires toggle event on render/mount

### ISSUE THREAD

**Issue by schwers** [lit/lit#2020]
[I have a lit playground link demo'ing this behavior](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgc3RhdGV9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCB7IGxpdmUgfSBmcm9tICdsaXQvZGlyZWN0aXZlcy9saXZlLmpzJztcblxuXG5AY3VzdG9tRWxlbWVudCgnc2ltcGxlLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYHAgeyBjb2xvcjogYmx1ZSB9YDtcblxuICBAc3RhdGUoKVxuICBwcml2YXRlIG9wZW4gPSB0cnVlO1xuICBcbiAgaGFuZGxlVG9nZ2xlKCkge1xuICAgIGNvbnNvbGUubG9nKCdmaXJlcyBoYW5kbGVyJylcbiAgfSBcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgPGRldGFpbHMgLm9wZW49JHtsaXZlKHRoaXMub3Blbil9IEB0b2dnbGU9JHt0aGlzLmhhbmRsZVRvZ2dsZX0-PHN1bW1hcnk-c3VtbWFyeTwvc3VtbWFyeT5kZXRhaWxzPC9kZXRhaWxzPmA7XG4gIH1cbn0ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZyBuYW1lPVwiV29ybGRcIj48L3NpbXBsZS1ncmVldGluZz5cbjwvYm9keT5cbiJ9XQ), copying the code below.

If the default state of a details element `open` attribute is `true`, the `toggle` event handler is called after rendering. This does not happen when `open`'s initial value is `false`. We're using `details&summary` for large comments threads which can accumulate quite lot of calls to the toggle handler. We're currently short-circuiting this by checking `event.target.open !== this.open` but I would have expected the handler to only fire on change to `open`

```ts
import {html, css, LitElement} from 'lit';
import {customElement, state} from 'lit/decorators.js';
import { live } from 'lit/directives/live.js';


@customElement('simple-greeting')
export class SimpleGreeting extends LitElement {
  static styles = css`p { color: blue }`;

  @state()
  private open = true;
  
  handleToggle() {
    console.log('fires handler')
  } 

  render() {
    return html`<details .open=${live(this.open)} @toggle=${this.handleToggle}><summary>summary</summary>details</details>`;
  }
}
```

**Comment by madbook** [comment]
Just to be clear, this also happens if `open` is set as a plain boolean attribute, i.e.

```ts
render() {
  return html`<details open @toggle=${this.handleToggle}> ...
```

**Comment by aomarks** [comment]
I think it's just the natural behavior of `<details>` that it fires a `toggle` event whenever the `open` attribute is set, including the first time it is set. Here's a [repro](https://lit.dev/playground/#project=W3sibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPGJvZHk-XG4gIFxuPGRldGFpbHMgb3Blbj48L2RldGFpbHM-XG5cbjxwcmU-XG5sb2c6PC9wcmU-XG5cbjxzY3JpcHQ-XG5jb25zdCBkZXRhaWxzID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignZGV0YWlscycpO1xuZGV0YWlscy5hZGRFdmVudExpc3RlbmVyKCd0b2dnbGUnLCAoZXZlbnQpID0-IHtcbiAgZG9jdW1lbnQucXVlcnlTZWxlY3RvcigncHJlJykudGV4dENvbnRlbnQgKz1cbiAgICBldmVudC50YXJnZXQub3BlbiA_ICdcXG4gIG9wZW5lZCcgOiAnXFxuICBjbG9zZWQnO1xufSk7XG48L3NjcmlwdD5cbjwvYm9keT4ifV0) showing the same behavior without any Lit code.

Note also it's fired asynchronously, so that multiple toggles are coalesced (see https://html.spec.whatwg.org/multipage/interactive-elements.html#the-details-element:event-toggle). So it doesn't matter whether you add the event listener before or after you set the open attribute.

Maybe in your example you could compare `event.target.opened` to `this.open` to decide if you actually need to do anything in response to the `toggle` event.

**Comment by schwers** [comment]
@aomarks closing the loop on this, we'll keep using details with the `event.target.open` guard as suggested and add that to our documentation. Thanks for the help.
