### ISSUE TITLE
lit-html 2 removes HTML it does not know about

### ISSUE THREAD

**Issue by vladitasev** [lit/lit#2037]
# Description

HTML, generated outside of lit-html, is removed upon re-rendering.

# Background

The use case is a web component that renders its template inside its `shadowRoot` with `lit-html`, and then shows a map, which is a thirdparty and gets a DOM element to render itself inside. The project used to run with `1.4.1` until now, but after migrating to a newer version of our framework, which is already updated to `lit-2.0.0-rc3`, the map, rendered by the thirdparty, disappears after the first re-render of the lit template.

# Steps to Reproduce

1. Open this codesandbox for a minimal setup:
https://codesandbox.io/s/fervent-night-lhdwj

The code is:

```js
import { render, html } from "lit-html";

const runThirdparty = (el) => {
  el.classList.add("my-class");
  el.innerHTML = "Third party set some content inside";
};

const app = document.getElementById("app"); // we use lit-html inside this div

render(html`<div class="test"></div>`, app); // fill the div with some content

runThirdparty(app.children[0]); // run a thirdparty that creates content within the lit-html controlled div

render(html`<div class="test"></div>`, app); // BREAKING CHANGE in 2.0.0-rc3 - the second call to render removes third-party content
```

It simulates the use-case where we create some HTML with lit-html, then have a third-party run inside (in this example inside the div with `class="test"`, and then we re-render the HTML with lit-html.

2. See this output...

The string `"Third party set some content inside"` can no longer be seen on the HTML page to the right after the second lit-html `render` call.

Now go to `package.json`, set the version to `1.4.1`, save, and observe the result: no matter how many times one runs `render`, the third-party-code generated HTML inside the static parts of the template remains intact.

## Live Reproduction Link

https://codesandbox.io/s/fervent-night-lhdwj

## Expected Results

I would expect that `lit-html` will only modify dynamic parts of the template (as it used to behave in 1.4.1). When I pass an even entirely static template, and have a third-party generate some HTML inside parts of it, I would expect that lit-html will not remove externally-generated HTML. 

## Actual Results

All HTML that appeared from external sources between `render` calls is removed.

## Browsers Affected

- [x ] Chrome
- [ x] Firefox
- [x ] Edge
- [ x] Safari 11
- [x ] Safari 10
- [ x] IE 11

**Comment by sorvell** [comment]
The change here is that in Lit1, templates were considered the same if their static strings were the same. In Lit2, we use the Javascript that returns a unique array per call site of a template literal. This is a nice performance improvement, but can be an issue if you render exactly this way.

Therefore, in Lit1, this code would be considered an "update" and not generate new DOM, but in Lit2, the 2nd render call is considered to have a new template and therefore renders new DOM.

```
render(html`<div class="test"></div>`, app);
// ...
render(html`<div class="test"></div>`, app); // <-- considered a new template in Lit2 but not Lit1
```

You can easily fix this by creating a render function like this:

```
const renderApp = () => {
  render(html`<div class="test"></div>`, app);
}

renderApp();
// ...
renderApp();
```

Since there's one template, Lit2 will consider the 2nd call to `renderApp()` an "update" and not render new DOM. 

Hope that explains the issue and is an easy fix.
