### ISSUE TITLE
[react] Configured events use native events while built-in events use React's synthetic events

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#2127]
We should see if we can wrap configured events in React's synthetic event wrapper in order to make handling events more consistent and familiar to React users.

**Comment by justinfagnani** [comment]
@claviska since you've been using the React wrapper, what's your opinion on this?

**Comment by claviska** [comment]
I agree with the intent — it should work the way React users expect. (It's just unfortunate React doesn't use standard events.)

**Comment by vmizgiris-equinix** [comment]
I've come across this issue by noticing that any events, if named using any name that an HTMLElement class or its derivative uses for native events, will be wrapped using React's synthetic event wrapper, even if it's a user configured event.

If you were to map these events in the React wrapper like such:

```
{
  onClick: 'click',
  onOpen: 'open',
  onClose: 'close'
}
```

*onClick* and *onClose* would always get triggered twice, whereas *onOpen* would only get triggered once, because `open` is not part of any native event dispatched by any HTML element.

The solutions I see for my use case are:

* Name user configured events differently, e.g. a prefix, `my-click` or `my-open`. In my opinion, this is not always ideal, and for existing systems and applications this can present a problem when integrating and / or switching from a different design system and native web components or traditional libraries
* Only keep mapping for those events that do not replicate native event names. This is probably the approach I'd go with right now, but it's also less than ideal as you'd always have to carefully check which event is native and which is not. For example, a fairly recent `HTMLDialogElement` has events named `cancel` and `close`, which do not appear in any other HTML element - this would be easy to overlook.
* Standardize events as per the original suggestion in this thread. IMO, labs could also avoid creating additional mapping for events with native names that will already be wrapped by React. Or some other, similar way...

Having said that, the suggested practice might be not to name user configured events using names of native events. If that's the case, it would be useful to hear some advise why that would be the case, and maybe a mention for that somewhere in Lit documentation, e.g. a short paragraph or a link to the appropriate standards and recommendations. I would very much appreciate to hear more about it.

TIA

**Comment by justinfagnani** [comment]
Thanks for that information @vmizgiris-equinix! The double-firing is an important bug to fix regardless of the wrapper situation. Would you mind opening a new issue for that? If you can make a reproduction on lit.dev/playground that would really help too!

**Comment by vmizgiris-equinix** [comment]
Thanks @justinfagnani, I commented too early... I was using a slightly modified copy of @lit-labs/react which of course was the reason for my issue :| Tried to replicate using @lit-labs/react and I could not observe that issue anymore!!! Silly me.

/ot

**Comment by taylor-vann** [comment]
might be the oddball here but i think this is WAI

"The synthetic events are different from, and do not map directly to, the browser’s native events."
"The specific mapping is not part of the public API and may change at any time."
https://reactjs.org/docs/events.html#overview

I take this to mean react can / will / has changed what DOM events correlate to certain react events. So it's not consistent to assume what events will become synthetic events (other than spotting camelCased versus noncamelcased functions)

And AFAIK (could be totally incorrect here) there's not a great way to augment react's native event system. Or a good way to add to ReactDOMs SimpleEventPlugin / PluginHub without extending ReactDOM itself.

I feel like devs could benefit from knowing what they’re using isn’t exactly a react component and likewise does not use react synthetic events.

As in, when we use refs in ReactDOM, they're usually HTMLElements. And we'd add DOM event listeners to those refs. And that's what is being "rendered" in our react module: a reference to an HTML Element inside a React Element, not a React Element itself.

**Comment by taylor-vann** [comment]
I'd like to close this bug as WAI :)

Unless there's any major protests? Or unless there's a way to augment ReactDOM events ergonomically.

**Comment by claviska** [comment]
> I feel like devs could benefit from knowing what they’re using isn’t exactly a react component and likewise does not use react synthetic events.
>
> As in, when we use refs in ReactDOM, they're usually HTMLElements. And we'd add DOM event listeners to those refs. And that's what is being "rendered" in our react module: a reference to an HTML Element inside a React Element, not a React Element itself.
>
> I'd like to close this bug as WAI :)

I'll second this motion. In the spirit of consistency, I agree with the objective but with the wrappers, I haven't heard a single complaint from users about native vs synthetic events.

I'm also thinking about React's experimental support for custom elements. If I understand correctly, they're not translating custom element events to synthetic events, and in that case the wrapper probably shouldn't either.

**Comment by justinfagnani** [comment]
> It has the same interface as the browser’s native event

That seems to say that it's fine to not wrap. React probably wants to move away from wrapping anyway. The only potential trip-up here is that these event handler's events won't have the `nativeEvent` property.

**Comment by taylor-vann** [comment]
Thanks for the help everyone!
