### ISSUE TITLE
[localize] Improve handling of translation messages with same id

### ISSUE THREAD

**Issue by fetherston** [lit/lit#2140]
## Description

- Who wants the functionality
Your friends at Reddit 😄 

- What it is they want
The following code produces the below error when running `lit-localize extract`
```js
msg(str`${mother} said hello`)
msg(str`${father} said hello`)
....
error TS2324: Message ids must have the same default text wherever they are used
```

- Why they want it
To improve developer ergonomics of using Lit/Localize.

## Acceptance criteria

**At a minimum:** the error message is more clear and actionable. 
**Ideally:** Allow the same message in multiple places, as long as the strings + description are the same.

**Comment by aomarks** [comment]
If there are multiple @lit/localize messages with the same ID (whether defined automatically or manually), we currently run a validation check to reduce the chance that those messages might actually have different semantic meaning, since they will be translated as a single unit. It's defined here: https://github.com/lit/lit/blob/064e2f4aca7fe822206c09438d0e68ccbec0c973/packages/localize-tools/src/program-analysis.ts#L631

The current rule is:

- Require that the string portions of the template are identical.
- Require that the text of the template expressions are identical.

Which is why the above example errors. We'll modify the rule to instead:

- Require that the string portions of the template are identical.
- Require that the descriptions are identical.

And to have a more helpful error message like:

```
The translation message with ID <id> was defined in N places, but with different strings or descriptions. If these messages should be translated together, make sure their strings and descriptions or identical, and consider factoring it out into a common variable or function. If they should be translated separately, add an "id" override to distinguish them."
```
