### ISSUE TITLE
Shady DOM dosen't work with modern bundlers

### ISSUE THREAD

**Issue by herberthobregon** [lit/lit#2142]
# Description

If you use a simple HTML with unpkg.com, shady DOM works

```html
<!DOCTYPE html>
<body>
    <outer-element></outer-element>
    <script>
        customElements.forcePolyfill = true;
        ShadyDOM = {force: true};
        ShadyCSS = {shimcssproperties: false};
    </script>
    <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.6.0/webcomponents-bundle.js"></script>
    <script type="module">
        import 'https://unpkg.com/lit@2.0.0-rc.4/polyfill-support.js?module';
        import {LitElement, css, html} from 'https://unpkg.com/lit@2.0.0-rc.4?module';

        customElements.define(
          "outer-element",
          class extends LitElement {
            static get styles() {
              return [
                css`
                  :host {
                    color: orange;
                  }
                  div {
                    color: red;
                  }
                `
              ];
            }
            render() {
              return html`
                -> Outer element should be color orange...
                <div>${"Button Text Red"}</div>
              `;
            }
          }
        );
    </script>
</body>
```

But with bundler o dev servers (like vitejs) dosen't work

# Steps to Reproduce

1. Write this code

HTML
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shady Dom Lit Element Simple Starter Kit</title>
    <script>
        customElements.forcePolyfill = true;
        ShadyDOM = {force: true};
        ShadyCSS = {shimcssproperties: true};
    </script>
</head>
<body>
    <outer-element></outer-element>
    <lit-app></lit-app>
    <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.6.0/webcomponents-bundle.js"></script>
    <script type="module" src="/src/lit-app.ts"></script>
</body>
</html>
```
```ts
import 'lit/polyfill-support.js';
import { LitElement, html, css } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('lit-app')
export class LitApp extends LitElement {
  static styles = [
    css`
      :host {
        display: block;
        color: blue;
      }
      div.red {
        color: red;
      }
    `
  ];

  render() {
    return html`
      <h1>Hello from TS</h1>
      <div class="red">${'Button Text Red'}</div>
    `;
  }
}

```

2. See this output...

## Live Reproduction Link

https://stackblitz.com/edit/vite-zv4cxk

## Expected Results

Generate Shady CSS scope Styles in header

## Actual Results

Don't generate shady scope styles in header

## Browsers Affected

- [ x ] Chrome 93
- [ x ] Firefox
- [ x ] Edge
- [ x ] Safari 11
- [ x ] Safari 10
- [ x ] IE 11

**Comment by thescientist13** [comment]
I recall that the webcomponents.org website / repo recommended _not_ using bundlers with these polyfills, as something like webpack for example, wraps everything it processes in a custom runtime to manage its own code splitting mechanisms.

I would explore to make sure these specific polyfill bundles you are using are not getting transformed in anyway through these modern tools or otherwise try and recreate the issue using nothing but a simple HTTP server to help bisect where the issue could be coming from because there are a couple possibilities here:
1. an actual bug in Lit
1. transforms applied by Vite
1. whatever magic Stackblitz may be doing on top of the previous two

So simplifying the stack more and then validating the issue with more and more tooling will likely help narrow down the issue as well.

**Comment by justinfagnani** [comment]
It looks like there's something wrong with Vite.

@thescientist13 is right that you shouldn't import the polyfills or polyfill-support. Those are supposed to be loaded with script tags before any application code. The problem is that even when you fix that Vite is loading the script tags out-of-order. That breaks HTML's spec-defined behavior and loads the app code before the polyfills are enabled.

Here's a version of the demo that _should_ work, but doesn't: https://stackblitz.com/edit/vite-zzslhj?file=index.html

If you open the preview in a new window and look at the network panel you'll see that lit-app.js is loaded before polyfill-support.js and webcomponents-bundle.js. This isn't how the <script> tags are supposed to load given their type and placement in HTML.

**Comment by herberthobregon** [comment]
I add this order

```html
<script type="module" src="/polyfill-support.ts"></script>
<script type="module" src="/lit-app.ts"></script>
```
```typescript
import 'lit/polyfill-support.js';
console.log("LOADED","lit/polyfill-support.js")
```
```typescript
import 'lit/polyfill-support.js';
import { LitElement, html, css } from 'lit';
import { customElement } from 'lit/decorators.js';

console.log('LOADED', 'lit-app');
@customElement('lit-app')
....
....
```
![image](https://user-images.githubusercontent.com/6503845/132543484-38132091-4fe4-4e3d-89da-3b5b79aaa3e8.png)

But still doesn't work 😢

**Comment by sorvell** [comment]
The issue is that the mode of `polyfill-support` and the mode of Lit must match. The lit from unpkg is running in `prod` mode and the version built by vite is running in `dev` mode. Only 1 `polyfill-support` is currently supported and it can either be in `prod` or `dev`.
