### ISSUE TITLE
CSS :host() does not work

### ISSUE THREAD

**Issue by busynest** [lit/lit#2144]
## Description

- Jacek Markiewicz
- To make :host() work again. Stopped working after upgrade.

- To encapsulate CSS within element, without leaking out.
- Example: All various `form{}` properties effect a form that is suppoed to be encapulated.

-  adding and removing`<script src="node_modules/lit/polyfill-support.js">` causes weird breaks (mostly toast and drawer) , but doesn't help.

Project:
- https://github.com/busynest/centre

From what I can tell, maybe typescript merge brings everything together in a non encapsulated way.

I also tried `static get styles()` vs `static styles`

**Comment by busynest** [comment]
update to lit Solved: :host() and encapsulation works again.

somehow I circled back to `static get styles():CSSResult { return css' :host{} ... ' }`

The problem was probaly caused by instructions saying to use `static styles = css' :host {} ...'`
and somehow polyfill-support.js loads properly now.

**Comment by herberthobregon** [comment]
@busynest **Comment and close** your issue. (in the future) When you update lit, remove package-lock.json and yarn.lock with node_modules and reinstall if you have a problems 😄

**Comment by thescientist13** [comment]
@busynest 
I _think_ the way I understand the distinction between these two
```js
static styles = css`
  p {
    color: green;
  }
`;
```

```js
static get styles() {
  const mainColor = css`red`;
  return css`
    div { color: ${mainColor} }
  `;
}
```

is that the first will only be evaluated once, and so the second form is intended for use with expressions (since it is a getter function), such that say if that `mainColor` variable changes, then only in the second case would the styles get updated again to reflect the new value / styles in your component.

Not sure if that applies to your use case since I don't know the full CSS.

----

I think an exception to the first case would be if you used CSS custom properties?  In that case you could avoid having to implement the second variant and still get the performance benefit of the former.

I may be wrong, but just my thoughts on the subject, hopefully someone can help confirm for you.

**Comment by justinfagnani** [comment]
A static field and getter should behave the same. The only reason we ever showed the static getter is because fields weren't standardized quite yet. We don't call the getter multiple times.

**Comment by busynest** [comment]
Seems like "polyfill-support.js" was not loading, but works now.
Probably got fixed during a reinstall.

But this glitch was nice to see how Typescript merges everything into top-level application.

**Comment by sorvell** [comment]
Closing since this appears to be resolved. Feel free to re-open with more info if the problem persists. Thanks.
