### ISSUE TITLE
Importing a library from jsDelivr CDN does not work

### ISSUE THREAD

**Issue by IgorNovozhilov** [lit/lit#2190]
**Exception**: Couldn't find the requested file.
https://cdn.jsdelivr.net/npm/lit-html/+esm

see: https://github.com/jsdelivr/jsdelivr/issues/18263

library is not loaded, but the module type is specified in the package.json
https://cdn.jsdelivr.net/npm/lit-html@2.0.0/package.json

**Comment by justinfagnani** [comment]
This works: https://cdn.jsdelivr.net/npm/lit-html

Is there any reason that's not good?

**Comment by IgorNovozhilov** [comment]
@justinfagnani
> This works: https://cdn.jsdelivr.net/npm/lit-html
> 
> Is there any reason that's not good?

This is not what you need at all. We need to work in ESM mode, which allows you to connect libraries directly from the CDN

You should learn more about the principles of working with ES modules.

see: https://cdn.jsdelivr.net/npm/lit/+esm
It contains this import `import"/npm/lit-html@2.0.0/+esm"`
```
/**
 * Bundled by jsDelivr using Rollup v2.56.3 and Terser v5.7.1.
 * Original file: /npm/lit@2.0.0/index.js
 *
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
import"/npm/@lit/reactive-element@1.0.0/+esm";import"/npm/lit-html@2.0.0/+esm";export*from"/npm/lit-element@3.0.0/lit-element.js/+esm";
//# sourceMappingURL=/sm/29e3775ce80ba6c8ab70014059fcb11fb56ce54e8175928712c91077840f21c5.map
```

...
This is also mentioned here:
https://stackoverflow.com/questions/56506084/can-i-use-es-modules-library-from-cdn

**Comment by IgorNovozhilov** [comment]
Also, here is a working example of the problem for you.
When using [`Material Web Components`](https://github.com/material-components/material-web) this  error crashes import from CDN:
https://demo-source.github.io/mwc-dialog.v1.html
![image](https://user-images.githubusercontent.com/3082812/134619872-f06d4062-734b-4bb5-bfed-e9d412af14a9.png)

**Comment by IgorNovozhilov** [comment]
The problem can be fixed with the 1st line
`"module": "lit-html.js",`
https://github.com/lit/lit/pull/2194/files

My example (lit-html copy):
https://cdn.jsdelivr.net/npm/demo-source/+esm

The same as in https://cdn.jsdelivr.net/npm/lit-html, but with the ability to import the module

**Comment by justinfagnani** [comment]
> You should learn more about the principles of working with ES modules.

Yes thank you, but we've been shipping standard modules for 4+ years now and know them very well.

I am however not so familiar with jsdelivr and what's it's attempting to do with modules. The URL https://cdn.jsdelivr.net/npm/lit-html _is_ serving up a standard JS module with an `export` statement. Please be more specific than saying "this is not what you need".

Regardless, https://cdn.jsdelivr.net/npm/lit-html/+esm appears to be working now, as is your MWC demo. Seems like jsdelivr fixed a bug on their end.

**Comment by thescientist13** [comment]
Just a Lit user here, but as a suggestion for tools like jsdelivr, it might be worth avoiding the need to rely on and / or requiring libraries to maintain these bespoke community driven hints and fields in _package.json_ like the `module` field being added in the linked PR long term.  

Although not ESM specific to my knowledge, the NodeJS / npm toolchain has landed on these two hints that are likely to be more long term and hopefully gain more traction over time and would likely be a better investment in terms of support for the jsdelivr team since that is what library authors will already be optimizing for in an ESM world in NodeJS.
- [`type: "module"`](https://nodejs.org/api/esm.html#esm_enabling)
- [`exports` map](https://nodejs.org/api/packages.html#packages_exports)

By using these hints, jsdelivr should be able to support npm packages out of the box and even better, be able to rely on NodeJS to do all the [heavy lifting](https://nodejs.org/api/modules.html#modules_require_resolve_request_options) for them when building / bundling for delivery over their CDN.

Just my $.02.

**Comment by IgorNovozhilov** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18298
