### ISSUE TITLE
Error! $TypeError: Failed to resolve module specifier "lit/decorators". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by leonheess** [lit/lit#2225]
I followed the upgrade guide and using lit 2.0.0 with rollup I'm getting:

    Error! $TypeError: Failed to resolve module specifier "lit/decorators". Relative references must start with either "/", "./", or "../".

This is independent of browsers or OS.

**Comment by justinfagnani** [comment]
When using Lit in a browser you must either resolve "bare" module specifiers to paths, or use import maps. See https://lit.dev/docs/tools/requirements/#building-for-modern-browsers

Also, the decorator module must be imported as `lit/decorators.js` - with the file extension - according to our package exports configuration.

In sort, browser do not inherently support bare module specifiers, because they don't know where to look up the specifier. They do support paths and URLs though, because those point to an actual location the browser can fetch from. Modern tools like [Web Dev Server](https://modern-web.dev/docs/dev-server/overview/) will rewrite bare specifiers to paths.

You can also use [Import Maps](https://wicg.github.io/import-maps/) in Chrome to tell the browser where to resolve bare specifiers to.

**Comment by leonheess** [comment]
The file extension solved my issue! However, my IDE keeps removing it but that is a problem for itself - thank you!
