### ISSUE TITLE
[lit] Static build for CDN distribution

### ISSUE THREAD

**Issue by slightlyoff** [lit/lit#2272]
Per a F2F conversation with @justinfagnani, wanted to capture agreement to add a single, modern-browser-exclusive build of LitElement and the most frequently used lit-html directives to the distributed NPM module. The goal is to enable easy inclusion of LitElement from a single source file.

## Rationale

LitElement, when built, is tiny! That isn't apparent when using it from, e.g., unpkg. The need for the Polymer CLI tools also increases the friction to getting started with the edit/compile cycle that historically makes web development so much fun.

Instead of trying to boil the whole ocean by providing every build variant, or having to compromise on size to accomodate legacy, the idea here is to get developers started quickly while providing an easier path to "real" LitElement usage via local builds.

Part of this approach might need to add guards to the build to give up when loaded in the presence of existing LitElement (to prevent over-inclusion) and console logging to flag that this isn't the most efficient approach.

**Comment by jimmont** [comment]
Is it possible to publish the ES modules as javascript with the bare module-name paths resolved to local paths and published at https://lit.github.io/lit/ (or root there)? And expose that branch for cloning to allow using locally? 

Minification and other transformations aren't needed in my case as the projects I'd be using this with would have their own bundling/processing steps.

This would allow using Lit without requiring additional tooling (npm, rollup, etc, etc) and side-step those risks and overhead.

The user story would be:
As a developer I want static importable javascript files so that I can use Lit directly without additional package/transform tooling, except for a web browser and git.

**Comment by jimmont** [comment]
> As a developer I want static importable javascript files so that I can use Lit directly without additional package/transform tooling, except for a web browser and git.

following up to my previous comment I've been working through a solution to provide own static modules, including Lit, without using npm directly; transforming modules to use as static resources and provide for installation using git in mixed projects where the module provided is expected to work with npm; this is specific to how I consume Lit related dependencies, this issue and the user story mentioned here;

the script to import, as part of an evolving idea to solve for the given user-story, essentially copies the modules from unpkg and saves locally:
https://github.com/sourdough/starter/blob/main/tools/external.importer.js

the transformed dependencies dumped into a repo for checkout (including Lit):
https://github.com/sourdough/wildtype

an npm based sample project for testing this scenario and solution:
https://github.com/sourdough/batch

an npm managed dependency which installs the above wildtype modules:
https://github.com/sourdough/ingredient

I was expecting consuming projects to have their own process which would optimize for their development and release scenarios.
The aim is to remove intermediate package management software and all transformation complexity (due to the associated cost and risk).

**Comment by bicknellr** [comment]
Hi all, I've been working on generating bundled versions of Lit recently. Our last release (v2.2.0) started uploading these bundles and https://github.com/lit/lit.dev/pull/673 adds a short section to the getting started docs about how to get and use them - [the current preview of the new docs section is here](https://pr673-42f90a8---lit-dev-5ftespv5na-uc.a.run.app/docs/getting-started/#use-bundles). It would be great to get your feedback!

**Comment by bicknellr** [comment]
The bundles are up and a short docs section about using them is now available at <https://lit.dev/docs/getting-started/#use-bundles>.

**Comment by dpikt** [comment]
Hi @bicknellr, are there any plans for a static build of `lit-html`? I've got the same use case, but just for that package. Cheers!

**Comment by msingh00** [comment]
> The bundles are up and a short docs section about using them is now available at https://lit.dev/docs/getting-started/#use-bundles.

Unfortunately..the documentation there was little help as I included those bundles as modules and still received the error this thread discusses.  after going through this thread, someone posted this, that worked for me.

import {LitElement, html} from "https://cdn.pika.dev/lit-element/^2.2.1"

it is still unclear to me what the right approach for directly linking the bundles is...but atleast i can put the last 2 hours searching for a solution behind me and go on to learning lit.   I can say this..it seems the vue folks have figured this out by using importmap.  not sure why its so hard here.

**Comment by bicknellr** [comment]
@msingh00, could you describe the error you're seeing in more detail and/or provide a repro?

**Comment by msingh00** [comment]
> 

I was having this issue:  https://github.com/lit/lit-element/issues/76

**Comment by msingh00** [comment]
> 

I was having this issue: https://github.com/lit/lit-element/issues/76.
it was a bit frustrating until i found this thread.  I think it would be helpful to either have the documentation consider folks that just want to quickly include the library/framework by referencing the link (as opposed to npm or webpack setups)...
or to give an example step by step on how to do so.  The documentation and tutorials are good - but that one little piece is missing.

**Comment by bicknellr** [comment]
<https://github.com/lit/lit-element/issues/76#issuecomment-1225274738>:

> getting this same error...have this in my main: `<script type="module" src="https://cdn.jsdelivr.net/gh/lit/dist@2/all/lit-all.min.js" ></script>`
> 
> and this line in my component js cause the same error: `import {LitElement, html} from 'lit'`
> 
> what is the recommended way of doing this? as the tutorial do not seem to cover this

You should use the bundle URL instead of `lit` as the module specifier.

So this:

```html
<script type="module" src="https://cdn.jsdelivr.net/gh/lit/dist@2/all/lit-all.min.js"></script>
<script type="module">
import {LitElement, html} from 'lit';
</script>
```

Becomes this:

```html
<script type="module">
import {LitElement, html} from 'https://cdn.jsdelivr.net/gh/lit/dist@2/all/lit-all.min.js';
</script>
```

**Comment by msingh00** [comment]
Thanks.  i will use that bundle instead of the one i found earlier in this thread. 
the method how to import seems to have made a difference...that is probably what should be added to the documentation/tutorial i think.

thanks again

**Comment by thescientist13** [comment]
I think the docs are open source, so maybe a quick PR to add that snippet?  As I agree, I think that would be a really helpful addition since I wouldn't be surprised if others didn't get that nuance.  👌 
https://github.com/lit/lit.dev/blob/main/packages/lit-dev-content/site/docs/getting-started.md

**Comment by josephr5000** [comment]
> @jfbrennan Note that you can do the exact same thing with LitElement and unpkg:
> 
> ```js
>     import {LitElement, html} from 'https://unpkg.com/lit-element?module';
> ```

Very helpful!  FYI this is now 'https://unpkg.com/lit?module'

**Comment by josephr5000** [comment]
> I think the docs are open source, so maybe a quick PR to add that snippet? As I agree, I think that would be a really helpful addition since I wouldn't be surprised if others didn't get that nuance. 👌 https://github.com/lit/lit.dev/blob/main/packages/lit-dev-content/site/docs/getting-started.md

Agreed. `any modern browser should be able to import and run the bundles from within a <script type="module">` is not sufficient to get the point across.

**Comment by josephr5000** [comment]
@thescientist13 thanks for the nudge. Submitted a PR here, which just got approved.
https://github.com/lit/lit.dev/pull/917

**Comment by bicknellr** [comment]
Since you mentioned import maps earlier... Other than the [bare module specifiers](https://lit.dev/docs/tools/requirements/) (i.e. what import maps intend to enable), Lit's npm packages are completely standard JS, so you can actually use import maps to run them directly from from those so long as you know enough about the dependency graph and where to get those things to be able to write it, or use a tool to write it for you. (It looks like [`@jsenv/node-module-import-map`](https://www.npmjs.com/package/@jsenv/node-module-import-map) might do this for a local npm project?)

Of course, this only works in browsers that support import maps[^1], so shipping this isn't viable yet. (Hopefully not for long!) I haven't indicated any versions in the unpkg URLs here, so this particular import map relies on all of the latest versions of these packages being a valid combination, which just happens to work because we release everything simultaneously (not a guarantee).

[^1]: I think this is only Chromium and Gecko with the `dom.importMaps.enabled` flag in `about:config` currently.

```html
<!DOCTYPE html>
<script type="importmap">
{
  "imports": {
    "lit": "https://unpkg.com/lit/index.js",
    "lit/": "https://unpkg.com/lit/",
    "@lit/reactive-element": "https://unpkg.com/@lit/reactive-element/reactive-element.js",
    "@lit/reactive-element/": "https://unpkg.com/@lit/reactive-element/",
    "lit-element": "https://unpkg.com/lit-element/index.js",
    "lit-element/": "https://unpkg.com/lit-element/",
    "lit-html": "https://unpkg.com/lit-html/lit-html.js",
    "lit-html/": "https://unpkg.com/lit-html/"
  }
}
</script>
<script type="module">
import {LitElement, html} from 'lit';

class CounterElement extends LitElement {
  static properties = {
    clickCount: {
      type: Number,
      state: true,
    },
  };

  constructor() {
    super();
    this.clickCount = 0;
  }

  render() {
    return html`
      <button @click="${() => this.clickCount++}">
        This button has been clicked ${this.clickCount} times.
      </button>
    `;
  };
}

customElements.define('counter-element', CounterElement);
</script>
<counter-element></counter-element>
```

**Comment by thescientist13** [comment]
re: import maps, can definitely recommend https://github.com/guybedford/es-module-shims.  Have been using it in my project [Greenwood](https://www.greenwoodjs.io/about/how-it-works/#cli) to facilitate unbundled local development and has been working quite well.  🌟

**Comment by chase-moskal** [comment]
@bicknellr 

> (It looks like [@jsenv/node-module-import-map](https://www.npmjs.com/package/@jsenv/node-module-import-map) might do this for a local npm project?)

you might like to check out [importly](https://github.com/chase-moskal/importly#readme), my import map generator for npm projects. you can find a list of similar tools [here in the wicg import maps readme](https://github.com/WICG/import-maps#community-polyfills-and-tooling).

as others have mentioned, [es-module-shims](https://github.com/guybedford/es-module-shims) is top-tier :heart:

**Comment by miltonhowe** [comment]
> [lit/lit-element#76 (comment)](https://github.com/lit/lit-element/issues/76#issuecomment-1225274738):
> You should use the bundle URL instead of `lit` as the module specifier.
> 
> So this:
> 
> ```
> <script type="module" src="https://cdn.jsdelivr.net/gh/lit/dist@2/all/lit-all.min.js"></script>
> <script type="module">
> import {LitElement, html} from 'lit';
> </script>
> ```
> 
> Becomes this:
> 
> ```
> <script type="module">
> import {LitElement, html} from 'https://cdn.jsdelivr.net/gh/lit/dist@2/all/lit-all.min.js';
> </script>
> ```

what about this?
`import {customElement, property} from 'https://cdn.jsdelivr.net/gh/lit/dist@2.6.1/all/lit-all.min.js';`

no matter what I try, I cannot seem to import the decorators. Are they not part of the bundle? is there another bundle? why?

**Comment by p-ob** [comment]
> what about this?
> `import {customElement, property} from 'https://cdn.jsdelivr.net/gh/lit/dist@2.6.1/all/lit-all.min.js';`
> 
> No matter what I try, I cannot seem to import the decorators. Are they not part of the bundle? is there another bundle? why?
> Are the bundles only for js and not for TypeScript? If so the docs should spell this out more clearly. And that makes them minimally useful as the rest of the documentation, all the how-tos etc. use TypeScript and decorators.

The [documentation for decorators](https://lit.dev/docs/components/properties/#declare-with-decorators) calls out that they only work with TypeScript, and to use the alternatives for pure JS solutions where a bundler isn't involved. I'm sure that'll change now that decorators are Stage 3 in TC39 and once browsers ship an implementation.

So yes the out-of-the-box bundle, to be used client-side without any build tooling, is only supporting JavaScript. And as vanilla JS as possible so they don't fork standards, I'd imagine.

**Comment by miltonhowe** [comment]
> > what about this?
> > `import {customElement, property} from 'https://cdn.jsdelivr.net/gh/lit/dist@2.6.1/all/lit-all.min.js';`
> > No matter what I try, I cannot seem to import the decorators. Are they not part of the bundle? is there another bundle? why?
> > Are the bundles only for js and not for TypeScript? If so the docs should spell this out more clearly. And that makes them minimally useful as the rest of the documentation, all the how-tos etc. use TypeScript and decorators.
> 
> The [documentation for decorators](https://lit.dev/docs/components/properties/#declare-with-decorators) calls out that they only work with TypeScript or when using a bundler, and to use the alternatives for pure JS solutions where a bundler isn't involved. I'm sure that'll change now that decorators are Stage 3 in TC39 and once browsers ship an implementation.
> 
> So yes the out-of-the-box bundle, to be used client-side without any build tooling, is only supporting JavaScript. And as vanilla JS as possible so they don't fork standards, I'd imagine.

I am using Typescript, and the decorators are working, without a bundler, loading the Lit modules from `unpkg` using `<importmap>`.  I would like to switch to use the `jsdelivr` CDN but cannot do so without all the modules being included.

I suppose mine is an edge case unforeseen by the bundle distributors, but it is nonetheless a valid case, which as I said has been working using a different CDN. There is more than one way to use Typescript, and not all involve using `npm` and/or bundlers. In my case I am using `.Net` and `Microsoft.TypeScript.MSBuild`. I would be able to use the decorators if they were included in the bundles (as well as the d.ts type definitions).

**Comment by p-ob** [comment]
> > > what about this?
> > > `import {customElement, property} from 'https://cdn.jsdelivr.net/gh/lit/dist@2.6.1/all/lit-all.min.js';`
> > > No matter what I try, I cannot seem to import the decorators. Are they not part of the bundle? is there another bundle? why?
> > > Are the bundles only for js and not for TypeScript? If so the docs should spell this out more clearly. And that makes them minimally useful as the rest of the documentation, all the how-tos etc. use TypeScript and decorators.
> > 
> > The [documentation for decorators](https://lit.dev/docs/components/properties/#declare-with-decorators) calls out that they only work with TypeScript or when using a bundler, and to use the alternatives for pure JS solutions where a bundler isn't involved. I'm sure that'll change now that decorators are Stage 3 in TC39 and once browsers ship an implementation.
> > 
> > So yes the out-of-the-box bundle, to be used client-side without any build tooling, is only supporting JavaScript. And as vanilla JS as possible so they don't fork standards, I'd imagine.
> 
> I am using Typescript, and the decorators are working, without a bundler, loading the Lit modules from `unpkg` using `<importmap>`.  I would like to switch to use the `jsdelivr` CDN but cannot do so without all the modules being included.
> 
> I suppose mine is an edge case unforeseen by the bundle distributors, but it is nonetheless a valid case, which as I said has been working using a different CDN. There is more than one way to use Typescript, and not all involve using `npm` and/or bundlers. In my case I am using `.Net` and `Microsoft.TypeScript.MSBuild`. I would be able to use the decorators if they were included in the bundles (as well as the d.ts type definitions).
> 
> 

If you had this working with unpkg and want to use a different CDN, any CDN that acts as a sort of proxy to npm would work. jsdelivr can do that, too:

https://cdn.jsdelivr.net/npm/lit/index.js

You just can't use their kitchen sink bundle. I'd expect the importmap to look very similar to what you had for unpkg.

**Comment by miltonhowe** [comment]
> If you had this working with unpkg and want to use a different CDN, any CDN that acts as a sort of proxy to npm would work. jsdelivr can do that, too:
> 
> https://cdn.jsdelivr.net/npm/lit/index.js
> 
> You just can't use their kitchen sink bundle. I'd expect the importmap to look very similar to what you had for unpkg.

In fact it worked first try with simply substituting the server and path you provided.
I realise this discussion is taking place in a long since closed issue, but since we got this far I will post my working example in case someone else stumbles here in the future the way I did.
```
<script type="importmap">
{
  "imports": {
    "lit": "https://cdn.jsdelivr.net/npm/lit/index.js",
    "lit/": "https://cdn.jsdelivr.net/npm/lit/",
    "lit-html": "https://cdn.jsdelivr.net/npm/lit-html/lit-html.js",
    "lit-html/": "https://cdn.jsdelivr.net/npm/lit-html/",
    "lit-element": "https://cdn.jsdelivr.net/npm/lit-element/lit-element.js",
    "lit-element/": "https://cdn.jsdelivr.net/npm/lit-element/",
    "@("@")lit/": "https://cdn.jsdelivr.net/npm/@("@")lit/",
    "@("@")lit/reactive-element": "https://cdn.jsdelivr.net/npm/@("@")lit/reactive-element/reactive-element.js"
  }
  ```
  The somewhat confusing @("@") syntax is to escape the @ signs as this lives in an ASP Razor template.
  This is the trial-and-error list I found I needed, a combination of direct mappings to .js files and some generic mappings to folders ending in / - it is possible some of it is redundant, I just kept adding one ref at a time until all my imports were working.
  
I have only one Lit Component so far and this is how its imports read using the sourcemap
```import {LitElement, html, css, nothing} from 'lit';
import {customElement, property} from 'lit/decorators.js';
import {until} from 'lit/directives/until.js';
import {when} from 'lit/directives/when.js';```

Thank you @p-ob for your help in steering me in the right direction as well as understanding more about how this all works.

**Comment by jikkuatwork** [comment]
I have been scratching my head for so long on this. I really think `lit` should do a simple example with CDN static builds that works without any hassle in CodePen or another project.

I stumbled on this project again seeing someone mention that this doesn't require any bundling but it just feels so complicated to use.

A simple example would have solved this. Would be happy to help get it done, if someone can guide me on how to get `all` lit packages via CDN and I can simply try any feature without any other bundling tools.

**Comment by jimmont** [comment]
crude example:
https://sourdough.github.io/starter/www/
https://github.com/sourdough/starter/tree/main/www
has a long list of things to improve but works as an early starting point

**Comment by jikkuatwork** [comment]
Thanks, but roughly during the week that I wrote that comment I discovered [Petite Vue](https://github.com/vuejs/petite-vue) and I have to say I fell in love! 

Don't think any other web framework will make me turn away from this one. Have been looking for this DX for over 2 decades. Its super elegant to build components and reuse them without any bundling whatsoever. Hate that I don't have a proper page setup to demo this but I promise I will come back once its ready. Have been tied with work for some months now.

**Comment by eleses** [comment]
@jikkuatwork : they kinda done it now but their lit-all.min.js still doesn't include Lit Task for instance. And the latter is kinda broken that even old versions include the _latest_ lit react from CDN. So, if you try to load old Task (say 3.0.2) from labs (i.e. that came with Lit 2) into an old (embedded) browser without ES2021 native support it will bomb because it tries  to pull the latest (ES2021 requiring `??=`) lit react. 

Also Lit 2 has fairly substantial bugs #4266 #4408, so you still have to transpile Lit 3.1 (at least) yourself even for ES2019 browsers.

**Comment by jikkuatwork** [comment]
> [@jikkuatwork](https://github.com/jikkuatwork) : they kinda done it now but their lit-all.min.js still doesn't include Lit Task for instance. And the latter is kinda broken that even old versions include the _latest_ lit react from CDN. So, if you try to load old Task (say 3.0.2) from labs (i.e. that came with Lit 2) into an old (embedded) browser without ES2021 native support it will bomb because it tries to pull the latest (ES2021 requiring `??=`) lit react.
> 
> Also Lit 2 has fairly substantial bugs [#4266](https://github.com/lit/lit/issues/4266) [#4408](https://github.com/lit/lit/issues/4408), so you still have to transpile Lit 3.1 (at least) yourself even for ES2019 browsers.

Yes, never liked lit. I wish it was something I will like. But it wasn't. Interestingly, I moved away from Petite Vue to Preact :). Feels much better choice due to the way the components can be structured.

If you anyone is keen, the DX is better than Petite Vue and helps setup the code in a much more modular/reusable pattern without the complexity of bundling. I have a small project I did a few months ago: https://github.com/jikkuatwork/aia
