### ISSUE TITLE
[infra] Lit logo image that works in dark mode / on other backgrounds

### ISSUE THREAD

**Issue by TarunavBA** [lit/lit#2296]
# Description

The Lit Logo is not visible properly in GitHub dark mode. 

# Steps to Reproduce

1. Go to GitHub.com/lit/lit
2. Change the GitHub theme to dark
2. See that the lit logo is not visible.

## Expected Results

The logo should be both dark and light mode compatible

## Actual Results

The logo is not visible

## Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by thescientist13** [comment]
might be helpful to include some screenshots in the description to make it a bit easier to understand / see the issue.

**Comment by TarunavBA** [comment]
Sure @thescientist13 .

**Comment by TarunavBA** [comment]
Here it is :
![Screenshot_2021-11-13-10-22-07-708](https://user-images.githubusercontent.com/89698728/141606108-a2b0b6fb-a37b-4143-960f-d171ba0c18aa.jpeg)

**Comment by TarunavBA** [comment]
Any updates on this @thescientist13 ?

**Comment by thescientist13** [comment]
I'm not really a graphic designer nor am I an owner of the Lit repo, so my ability to help is very limited other than to help triage and assist from the outside. 😅 

That said, your screenshot is helpful as it it looks like it is the text aspect to the image that doesn't render properly in dark mode, naturally, given the text is dark. 

I saw Adam Wathan (creator of Tailwind) had a similar [question / challenge](https://twitter.com/adamwathan/status/1438096197672132617).  I'm not sure what he means by sticker, but effectively he added a white border to the text so that in light mode, it looks the same, but in dark mode, the text has a stroke around it to keep it from getting lost in dark mode.


<img width="616" alt="Screen Shot 2021-11-16 at 10 00 03 AM" src="https://user-images.githubusercontent.com/895923/142009446-42091b0e-9b9e-4820-9ef6-3d0501e1de3a.png">

<img width="615" alt="Screen Shot 2021-11-16 at 9 58 47 AM" src="https://user-images.githubusercontent.com/895923/142009476-cb079727-b256-4bec-809a-52566db744ca.png">

----

Maybe that would be helpful for the Lit team to consdier?

**Comment by TarunavBA** [comment]
Hey @justinfagnani I know a good friend of mine who could help us. Are you ok if he helps?

**Comment by justinfagnani** [comment]
Hey @TarunavBA we have an agency that produces our assets for us. @graynorton is going to forward this to them.

**Comment by aomarks** [comment]
GitHub supports light/dark image toggling now. Adding a dark theme variant in https://github.com/lit/lit/pull/2314.

**Comment by graynorton** [comment]
See Ocupop guidance in #2314.

**Comment by TarunavBA** [comment]
> Hey @TarunavBA we have an agency that produces our assets for us. @graynorton is going to forward this to them.

Ok @justinfagnani

**Comment by justinfagnani** [comment]
Fixed in https://github.com/lit/lit/pull/3457
