### ISSUE TITLE
[lit/reactive-element] css-tag not a concern of ReactiveElement

### ISSUE THREAD

**Issue by woutervroege** [lit/lit#2315]
Currently, `css-tag` is included in the `ReactiveElement` base class.
As the explicit promise of this class is not to have an opinion about rendering DOM, I think anything css and stylesheet related should be a concern of `LitElement`.

I love the idea of separating the (brilliant!) update lifecycle from the rendering engine and I think this particular thing is kinda breaking this promise.

**Comment by web-padawan** [comment]
I agree that it would be good to have some separation, like it used to be with `UpdatingElement` in the past.

**Comment by woutervroege** [comment]
Indeed. Furthermore, people who prefer this base class are very likely not going to use `css-tag` in their project, which makes ~40% of the javascript payload. (Yes, I know we're talking very small absolute numbers, but it's relatively huge ;-))

**Comment by justinfagnani** [comment]
We specifically moved styles support into ReactiveElement because it's useful without lit-html. A direct subclass of ReactiveElement or a subclass that integrates a different template system, like Preact, would generally still almost always be able to add styles to their element. There is nothing lit-html specific about the css tag and it's support in ReactiveElement.

**Comment by web-padawan** [comment]
@justinfagnani While in general your point is valid, is there any justification for not having a yet another layer represented by a dedicated class, something like `StyledReactiveElement` (name inspired by the original [lit-styles](https://github.com/lit-styles/lit-styles) project by @bashmish)?

**Comment by woutervroege** [comment]
@justinfagnani Any element is perfectly able to add styles to their element without the use of `css-tag`.
I love the elegance of decoupling the update lifecycle from the way DOM is rendered. I think really odd to promise a free choice DOM rendering solution, except for the `css-part`.
Moreover, given the ongoing debate regarding constructible stylesheets, `css-tag` is one of the more opinionated functions in the `lit` library, leveraging some great magic, but a foreign citizen in the context of the as-unopinated-as-can-be-boilerplate-preventing base class of `ReactiveElement`.

Why just not ship it as optional `{ import }` method? That would solve both the issue and service people who'd love to use the css magic?

**Comment by justinfagnani** [comment]
The style functionality really truly does not have anything to do with the Lit integration and it's useful to all custom elements.

The style functionality also does not depend on constructible stylesheets - which is not as nearly as controversial as might be portrayed and there is largely consensus on the feature - it works fine without it. It might be slightly opinionated, but all of ReactiveElement is opinionated, and it's our opinion that declarative static styles are a generally useful feature with good DX at a layer below Lit.

It would be a breaking change to remove it from ReactiveElement, so that's simply not an option for us at the moment.

**Comment by web-padawan** [comment]
Personally, I see an old `UpdatingElement` as a good example of "a la carte" idea that used to be one of the principles behind Polymer 2. I don't think it was largely used back then because of the complexity of Polymer mixins (it's still a challenge for me to remember all of them), but I really liked the approach used by previous version of LitElement.

**Comment by woutervroege** [comment]
@justinfagnani I hear you, but I think it's good to separate the design issue from the support issue.

If the toilet is placed in the kitchen, we have to address this, regardless of the fact that people rely and depend on it 🚽😀.
Plus, if semantic versioning is done right (which I believe is so far), users will perfectly know when to expect breaking changes.

For now, embracing @web-padawan idea: Why not just add `UpdatingElement.js`, and let `ReactiveElement.js` extend it + add the `css` tag? This will cause no harm whatsoever to all existing users while re-gaining the bare-bones updating base class.

**Comment by justinfagnani** [comment]
ReactiveElement is opinionated, and includes our estimation of what the most common required features of a base class are except templating. This includes styles, which the vast majority of elements are going to need. I think it's the very rare exception that _doesn't_ need styling.

**Comment by woutervroege** [comment]
Opinion is not the concern, to me it feels it just covers the load when stating on lit.dev docs that 'ReactiveElement is a 'base element class which manages element properties and attributes.'

Is your opinion determinative in this project or do we need further input of other contributors on this? (Please do not take this the wrong way, just wanna know whether I need to rest my case :))

**Comment by sorvell** [comment]
Going to close this. This issue was carefully considered in the design of ReactiveElement and the team decided that rendering and basic styling of a shadowRoot was something we wanted to encourage and support even in our lowest level base class. That said, these features can be customized or even ignored if desired.
