### ISSUE TITLE
Example of Tailwindcss integration ?

### ISSUE THREAD

**Issue by electroheadfx** [lit/lit#2369]
I'm looking for example of demo showing the usage of Tailwindcss with LitElement. At least how should we proceed ? With Vite it would like amazing.

**Comment by Westbrook** [comment]
https://dev.to/43081j/using-tailwind-postcss-and-stylelint-with-lit-element-projects-2hb9

**Comment by electroheadfx** [comment]
its for web pack but thanks. I'd would like to stay on vite

**Comment by thescientist13** [comment]
> its for web pack but thanks. I'd would like to stay on vite

Not sure which part you are having trouble, with the tooling or usage within a Web Component, but as far as the tooling goes, Tailwinds has an entire section of [Framework Guides](https://tailwindcss.com/docs/installation/framework-guides) in their Getting Started docs, including one for Vite.

It all mostly just comes down to find how a given tools supports PostCSS, since that all Tailwind is at the end fo the day.

**Comment by electroheadfx** [comment]
perfect thanks @thescientist13

**Comment by zalelion** [comment]
try https://github.com/viskit/css

**Comment by running-grass** [comment]
> 试试https://github.com/viskit/css

@zalelion  it's 404

**Comment by running-grass** [comment]
It is implemented by using the unsafe and adoptstyles of lit, based on the constructive stylesheet.

Look here
https://github.com/running-grass/starter-lit-with-tailwind
