### ISSUE TITLE
[ssr] Investigate removing "window" polyfill

### ISSUE THREAD

**Issue by augustjk** [lit/lit#2453]
A potential solution to https://github.com/lit/lit/issues/2393 and related issues.

Libraries such as SASS test for the presence of `window` to determine whether they are running inside Node or on the Web. The SSR polyfill currently defines `window`, which causes those libraries to mistakenly believe they are running on the Web, when they are in fact running on Node.

This issue tracks investigating the proposal from https://github.com/lit/lit/issues/2393#issuecomment-1020454371 to remove `window` from the SSR polyfill, and instead assign polyfilled APIs (such as `customElements`) directly to Node's `global`.

The immediate problem with this is that there exists code, including in our own Lit libraries and in user code, which depends on the presence of `window`. However, references to `window` can be replaced with `globalThis` (which is defined both on the Web and in Node), so this approach may be a good way to achieve broader compatibility without adding too much of a burden on writing SSR-compatible component code.

- [ ] Write up this proposal and get consensus on whether this approach is the right one.
- [ ] Find all of the spots in the Lit libraries where we reference `window` and replace with `globalThis`.
- [ ] Investigate IE11 compatibility. IE11 doesn't define `globalThis`, but it can be easily polyfilled with `var globalThis = window`. Investigate whether we already do this in the [Web Components Polyfills](https://github.com/webcomponents/polyfills), and if not determine whether we should add it there.
- [ ] Test the changes to Lit and the polyfills in Google3.
- [ ] Modify the SSR global polyfill to skip `window`, but still assign `customElements` and other APIs directly onto Node's `global`.
- [ ] Consider whether we would preserve the option to include `window`. When rendering in an isolated context (vm modules or workers), there would seem to be no reason not to include it.

**Comment by jonathantneal** [comment]
> This issue tracks investigating the proposal from #2393 (comment) to remove window from the SSR polyfill, and instead assign polyfilled APIs (such as customElements) directly to Node's global.

For what it’s worth, [Astro](https://github.com/withastro/astro) assigns `customElements` directly to `globalThis`. 😅🤣

Astro does check for it, first. However, since the mechanism for associating custom element names to constructors is internal, one could theoretically end up with incompatible implementations. I suspect this will be the case for other APIs. I’ve already experienced this issue first hand with libraries that include `EventTarget` polyfills for Node v12 running in Node v14. The polyfill will rely on a `WeakMap` references to an `EventTarget`, but Node v14 fulfilled the bit of code that would have polyfilled `EventTarget` to attach these references.

I just want us to all do better polyfilling WebAPIs into Node. Your input will be greatly appreciated. 🙏

**Comment by justinfagnani** [comment]
Oh, interesting. On the `EventTarget` front, I did some work to extend EventTarget to allow event propagation: https://github.com/lit/lit/pull/2309 We will have to look out for incompatibilities there.

**Comment by augustjk** [comment]
Closing this issue since removing the window polyfill won't solve the issue we're having with sass and it seems we'll be able to work around that. See #2393 for details.
