### ISSUE TITLE
lit-html package with type="module" uses extensionless imports in /directive.d.ts causing typescript to fail.

### ISSUE THREAD

**Issue by philkunz** [lit/lit#2644]
Note the differences in https://unpkg.com/browse/lit-html@2.2.1/directive.d.ts
vs https://unpkg.com/browse/lit@2.2.1/directive.d.ts

the lit directive.d.ts specifies an extension.
the lit-html directive.d.ts does not, which causes the typescript transpiler to fail!

note: https://unpkg.com/browse/lit-html@2.2.1/package.json specifies itself as "type": module which is why extensionless imports fail.

**Comment by justinfagnani** [comment]
Interesting... we've apparently published `lit-html/directive.d.ts` without file extensions since 2.0.0. This happens because import `lit-html.js` without an extension in that file. This would normally cause errors, but the imports are type-only so they're elided from `directive.js`.

We can definitely fix that, but I'm curious why you're the only one reporting this problem? What toolchain are you using? Even though we have `"type": "module"` in our package.json, we don't export the .d.ts files since they're never imported via Node, which would enforce Node resolution. Given that we have many, many developers using Lit 2.0 in TypeScript, I wonder what's different here.

**Comment by philkunz** [comment]
@justinfagnani I'm currently upgrading our complete package ecosystem to esm. I'm using the new node12 / nodenext module resolutions of typescript (see the options we use here: https://gitlab.com/gitzone/tsbuild/-/blob/master/ts/tsbuild.classes.compiler.ts)

Thus when simply transpiling esm packages that use lit as dependency I run into this problem. Normally people don't extend lit, but rather have it as dependency within a commonjs project. Neither the bundler nor TypeScript will throw in a CommonJS project.

**Comment by justinfagnani** [comment]
I actually think the majority of our users are in JS module projects, not CommonJS. They might not be using node12 resolution yet though.

**Comment by philkunz** [comment]
@justinfagnani true, that could be the case.
