### ISSUE TITLE
Rolling properties not properly initialized.

### ISSUE THREAD

**Issue by vdegenne** [lit/lit#2701]
I made an example code here : https://jsbin.com/dayodix/6/edit?html,output

What seems to be an issue is that when a custom element's reflecting property is connected to a custom element's reflecting property, the property is not properly initialized.
Simply put : 

```javascript
// a-element
render () {
  return html`<b-element ?concealed=${!this.revealed}></b-element>`
}
```

If I use

```javascript
<a-element revealed>
```

`<b-element>` is `concealed` on initialization. Am I missing something about this mechanic or have I found a rusty cog?

**Comment by AndrewJakubowicz** [comment]
Thanks for filing an issue and thanks for making a nice repo! Here's a super minimal repro of the subtle mechanics: [Lit.dev playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy5qcyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5cbndpbmRvdy5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ2ItZWxlbWVudCcsIGNsYXNzIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBwcm9wZXJ0aWVzID0ge1xuICAgIGNvbmNlYWxlZDogeyB0eXBlOiBCb29sZWFuLCByZWZsZWN0OiB0cnVlIH1cbiAgfVxuXG4gIGNvbnN0cnVjdG9yKCkge1xuICAgIHN1cGVyKClcbiAgICAvLyBJc3N1ZSBpcyBoZXJlLiBCeSBkZWZhdWx0aW5nIHRoaXMgdG8gYHRydWVgLCB0aGUgbGFjayBvZiB0aGUgYm9vbGVhbiBhdHRyaWJ1dGUsXG4gICAgLy8gcmVzdWx0cyBpbiBhIHRydWUgZmFsbGJhY2sgdmFsdWUuIENoYW5nZSB0byBgZmFsc2VgIHRvIG1ha2UgaXQgcG9zc2libGUgdG9cbiAgICAvLyBjaGFuZ2UgdGhlIGF0dHJpYnV0ZSBmcm9tIG1hcmt1cC5cbiAgICB0aGlzLmNvbmNlYWxlZCA9IHRydWVcbiAgfVxuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gdGhpcy5jb25jZWFsZWQgPyAnaGlkZGVuJyA6ICdzZWNyZXRseSBzaG93aW5nIGEgc2VjcmV0J1xuICB9XG59KTtcbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8Yi1lbGVtZW50IGNvbmNlYWxlZD48L2ItZWxlbWVudD5cbiAgPGJyIC8-XG4gIDxiLWVsZW1lbnQ-PC9iLWVsZW1lbnQ-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d).

There is some subtle complexity to this mechanic (_boolean attributes_) which needs better documentation. I've filed an issue: https://github.com/lit/lit.dev/issues/744 to ensure this is explained better in the Lit documentation.

The complexity here is that `b-element` defaults `concealed` to `true`.  Changing `concealed` to `false` resolves this issue. The subtle mechanic, is that not declaring an attribute results in the default value being used.
For example; on the hello world https://lit.dev/playground/ example, using `<simple-greeting></simple-greeting>` will use the default `name`, which is `"Somebody"`.
A similar thing is happening here, except there's complexity because the syntax for a false boolean attribute shares the syntax with falling back on the default value. Therefore to keep these two concepts in sync, the default boolean value needs to be `false` if you want to be able to _turn it off _ from html markup.

Hopefully that clears up the confusion of what is happening here. To fix the issue in the code sample, use `this.concealed = true` in the `B-ELEMENT` constructor.

**Comment by AndrewJakubowicz** [comment]
Closing issue in favor of tracking it through a docs improvement: https://github.com/lit/lit.dev/issues/744
