### ISSUE TITLE
[labs/context] ContextRoot will duplicate tracking a context-requesting component which is connected multiple times

### ISSUE THREAD

**Issue by benjamind** [lit/lit#2765]
## Description
`ContextRoot` will track a context-requesting element (that is not getting a satisfied context-request) multiple times if that element is connected/disconnected within the document multiple times. This isn't a major issue in that it only results in a slight performance degradation when that context is ready to be provided in future (since it will receive the context multiple times). But this could be worth addressing if a context-requesting element is frequently added/removed from the DOM without having a satisfying context provider.

**Comment by justinfagnani** [comment]
I tried fixing this this morning, but it might be impossible to correctly fix without a change to the protocol.

The problem is that it's not possible to distinguish from an element firing multiple context-request events because it connected multiple times from firing multiple events because it has multiple ContextConsumers for the same context.

```ts
class MyElement extends LitElement {
  constructor() {
    new ContextConsumer(this, someContext, (value) => {
        console.log('consumer 1', value);
      }, true);
    new ContextConsumer(this, someContext, (value) => {
        console.log('consumer 12, value);
      }, true);
  }
}
```

For whatever reason this may be done - inheritance, mixins, composed controllers, etc. - we _do_ want to call both callbacks here.

So we can't dedupe by element reference. We could maybe dedupe by both element reference and callback references, but that doesn't work for all cases. Sometimes the callbacks won't be stable:

```ts
class MyElement extends LitElement {
  connectedCallback() {
    super.connectedCallback();
    this.consumer = new ContextConsumer(this, someContext, (value) => {
        console.log('consumer 1', value);
      }, true);
  }
}
```

Here the callback will be new every time the element connects.

So maybe it's ok for those callbacks to fire? This would be similar to how addEventListener() works at least: multiple calls with the same event name and listener are deduped.

**Comment by kevinpschaaf** [comment]
It feels like maybe the protocol should have a concept of `unsubscribe` separate from providing a value. You really want the host to unsubscribe from either the context provider or context root if the element is disconnected. But right now, the only way you get `unsubscribe` is by providing a value, which we wouldn't want the context root to do.

**Comment by justinfagnani** [comment]
@kevinpschaaf yes, that's another issue.
