### ISSUE TITLE
[lit-html - SSR] missing parent check for defer-hydration?

### ISSUE THREAD

**Issue by daKmoR** [lit/lit#2946]
# Description

I am not sure why but I currently have a situation where  `marker.parentElement` in `experimental-hydrate.ts` is null.

https://github.com/lit/lit/blob/main/packages/lit-html/src/experimental-hydrate.ts#L161-L164

when I check the code I see this

```js
const parent = marker.parentElement!;
if (parent.hasAttribute('defer-hydration')) {
  parent.removeAttribute('defer-hydration');
}
```

adding check so that `parent` can not be null seems to make it work.

e.g.

```diff
   const parent = marker.parentElement!;
-  if (parent.hasAttribute('defer-hydration')) {
+  if (parent && parent.hasAttribute('defer-hydration')) {
     parent.removeAttribute('defer-hydration');
   }
```

Is that just a missing check? or is there a 0 chance that `parentElement` is ever null? If so I need to check why it's null in my case...

**Comment by aomarks** [comment]
My current hypothesis is that this could happen if you were hydrating a shadow root with an immediate child that is a void (aka empty) element, such as `<input>` or any of [these](https://developer.mozilla.org/en-US/docs/Glossary/Empty_element), and that has an attribute binding. So e.g.

```ts
render() {
  return html`<input max=${this.maxLen}>`;
}
```

Void elements are special because when the HTML parser encounters a child of one of them, it hoists the child up as a sibling, since those elements aren't supposed to have children.

In SSR, when an element has an attribute binding, we represent that with a child comment like `<!--lit-node 0-->`. But if that's in a void element, it will end up as a sibling, instead of a child. We account for this in one place in the hydrate code, but not in another (the place you mentioned).

Working on a repro to confirm.

**Comment by daKmoR** [comment]
thaankks 🙇‍♂️

updated and works as expected 💪
