### ISSUE TITLE
[labs/context] Add a `contextProvider` directive to support providing to part of an element's subtree

### ISSUE THREAD

**Issue by sorvell** [lit/lit#2967]
An element may want to provide different context values to different parts of its subtree. Consider, for example, a context that provides styling data to elements inside a custom element like a dialog. The element might want style various different elements like buttons inside it differently via this styling context data. 

This could be addressed via a `contextProvider` element directive. It would be used something like this:

```
<my-dialog id="favorites" ${contextProvider({context: styling, value: favoritesCss})}>...</my-dialog>
<my-dialog id="settings" ${contextProvider({context: styling, value: settingsCss})}>...</my-dialog>
```

**Comment by justinfagnani** [comment]
@benjamind and I should document why this was left out of v1 (that might be a good year for an ADR process).

The reason is that because rendering is async, and context can be used to provide values to light DOM children, you can get in a race condition where light DOM children fire context request before a parent has rendered and set up the context provider directive.

A controller is initialized earlier and avoids this. It could then wait to see what slot the request congress from.

We do know that this isn't a problem for shadow subtrees.

**Comment by justinfagnani** [comment]
Closing this as not planned because of the race condition with initial render.
