### ISSUE TITLE
[localize] msg function substitutes last used parameter

### ISSUE THREAD

**Issue by victorenator** [lit/lit#2971]
# Description

`msg` function call substitutes last used parameter.

# Steps to Reproduce

1. Write this code

```js
import {html, render} from 'lit';
import {msg} from '@lit/localize';

render(html`
<ol>
<li>${renderItem('ABC')}</li>
<li>${renderItem('CDE')}</li>
<li>${renderItem('123')}</li>
<li>${renderItem('456')}</li>
<ol>
`, document.body);

function renderItem(param) {
  return [
    html`Some text with param <b>${param}</b>`,
    ' ',
    msg(html`Some text with param <b>${param}</b>`),
  ];
}
```

2. See this output...

## Live Reproduction Link

https://stackblitz.com/edit/web-platform-bxitxm

## Expected Results

```
1. Some text with param ABC. Du texte avec paramètre ABC.
2. Some text with param CDE. Du texte avec paramètre CDE.
3. Some text with param 123. Du texte avec paramètre 123.
4. Some text with param 456. Du texte avec paramètre 456.
```

## Actual Results

```
1. Some text with param ABC. Du texte avec paramètre 456.
2. Some text with param CDE. Du texte avec paramètre 456.
3. Some text with param 123. Du texte avec paramètre 456.
3. Some text with param 456. Du texte avec paramètre 456.
```

## Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by augustjk** [comment]
Thank you for the report and reproduction!

The problem appears to be that we're reusing the localized version of the template result with a mutated `values` for all `msg` calls with the same id: 
https://github.com/lit/lit/blob/16a900c7d0191140a65cdb38126ab3653c334935/packages/localize/src/internal/runtime-msg.ts#L56-L60

This should be easily fixable by returning a new object reference for each `msg` call instead of reusing and mutating the object.
