### ISSUE TITLE
[labs/router] Compression mangling error

### ISSUE THREAD

**Issue by diervo** [lit/lit#3031]
# Description

There is a bug in the way package `@lib-labs/router` is bundled, specifically in the way files are being mangled during compression.

In production mode (the default export resolution per package.json), the bundled code at runtime is not equivalent (and incorrect in this case) to its original.

## Cause
The cause (intuitively) seems to be that the mangling during compression is done on a per-file basis:

```js
// Routes.js defines t, which represents _childRoutes) as an empty array.
class Routes {
  this.t = []; // this._childRoutes = [];
  ...
}
// Router.js redefines t as the onclick overriding incorrectly the inherited field
class Router extends Routes {
  this.t=t=>{...} // this was this._onClick = (e) => {
  ...
}
```

Since `Router extends Routes` the code is no longer equivalent after compression.

## Conclusion 

Without looking at the specific processor used to compress the files (`wireit` I believe), seems that doing this process by file will create in this (and many other cases) unintended mangling overrides due to the lack of dependencies context.

### Unwanted observation: 
IMHO I found it odd that the package is being shipped "pre-compressed" as the default, since I believe that should be the responsibility of the consumer, but that's up to the team to decide the rationale to do so :)

**Comment by diervo** [comment]
FYI @justinfagnani this might be affecting other packages if the same build process is being used.

**Comment by AndrewJakubowicz** [comment]
Thank you for filing an issue! Class properties were not being correctly identified in the mangling process. We also were not testing our minified outputs for labs packages. Both resolved in https://github.com/lit/lit/pull/3050

@justinfagnani can speak more to the observation about pre-compressing packages.

**Comment by diervo** [comment]
Thanks for the quick turnaround! Really appreciate the good work 🙏

Oh I know what @justinfagnani will say, just wanted to poke the bear a little 😹

**Comment by justinfagnani** [comment]
Thanks for the report @diervo!

Yeah... I think you know already :) but for posterity I'll get into it a little:

We've been applying minification to our core libraries, even though I agree with you that minification should normally be an app concern, because we could get smaller output by using potentially unsafe settings that we know are safe and tested in our codebase, and in order to make using private API more cumbersome.

We probably don't have to apply this to all of our packages, like router. Andrew's fix is just the easiest, imcremental thing to do without re-litigating our strategy here. I'm open to changing though. Ultimately the right answer is private fields, which can be freely and safely renamed so we won't even have to do it - Terser could by default as used in apps.
