### ISSUE TITLE
[labs/virtualizer] rangeChanged event stops propagation on itself

### ISSUE THREAD

**Issue by najikahalsema** [lit/lit#3051]
VisibilityChanged and RangeChanged events bubble and compose differently. The rangeChanged event stops propagation on itself which doesn't allow for its host to interact with the event. 

[Code demo](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCB7dmlydHVhbGl6ZX0gZnJvbSAnQGxpdC1sYWJzL3ZpcnR1YWxpemVyL3ZpcnR1YWxpemUuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnc2ltcGxlLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgICAgOmhvc3QgeyBcbiAgICAgICAgZGlzcGxheTogYmxvY2s7XG4gICAgICAgIGhlaWdodDogMjAwcHg7XG4gICAgICB9YDtcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgIDxkaXY-XG4gICAgICAke3ZpcnR1YWxpemUoe1xuICAgICAgICBzY3JvbGxlcjogdHJ1ZSwgXG4gICAgICAgIGl0ZW1zOiBBcnJheS5mcm9tKEFycmF5KDEwMCkua2V5cygpKSwgXG4gICAgICAgIHJlbmRlckl0ZW06IChpdGVtKSA9PiBodG1sYDxkaXY-JHtpdGVtfTwvZGl2PmBcbiAgICAgIH0pfVxuICAgICA8L2Rpdj5cbiAgICBgO1xuICB9XG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vb3RoZXItZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbiAgXG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZz48L3NpbXBsZS1ncmVldGluZz5cbiAgPG90aGVyLWdyZWV0aW5nPjwvb3RoZXItZ3JlZXRpbmc-XG4gIFxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIj5cbiAgICBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCdzaW1wbGUtZ3JlZXRpbmcnKS5zaGFkb3dSb290LmFkZEV2ZW50TGlzdGVuZXIoJ3Zpc2liaWxpdHlDaGFuZ2VkJywgKGUpID0-IHtcbiAgICAgIGNvbnNvbGUubG9nKCd2aXNpYmlsaXR5Q2hhbmdlZCcsIGUudGFyZ2V0KTtcbiAgICB9KVxuICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJ290aGVyLWdyZWV0aW5nJykuc2hhZG93Um9vdC5hZGRFdmVudExpc3RlbmVyKCd2aXNpYmlsaXR5Q2hhbmdlZCcsIChlKSA9PiB7XG4gICAgICBjb25zb2xlLmxvZygndmlzaWJpbGl0eUNoYW5nZWQnLCBlLnRhcmdldCk7XG4gICAgfSlcbiAgICBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCdzaW1wbGUtZ3JlZXRpbmcnKS5zaGFkb3dSb290LmFkZEV2ZW50TGlzdGVuZXIoJ3JhbmdlQ2hhbmdlZCcsIChlKSA9PiB7XG4gICAgICBjb25zb2xlLmxvZygncmFuZ2VDaGFuZ2VkJywgZS50YXJnZXQpO1xuICAgIH0pXG4gICAgZG9jdW1lbnQucXVlcnlTZWxlY3Rvcignb3RoZXItZ3JlZXRpbmcnKS5zaGFkb3dSb290LmFkZEV2ZW50TGlzdGVuZXIoJ3JhbmdlQ2hhbmdlZCcsIChlKSA9PiB7XG4gICAgICBjb25zb2xlLmxvZygncmFuZ2VDaGFuZ2VkJywgZS50YXJnZXQpO1xuICAgIH0pXG4gIDwvc2NyaXB0PlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9LHsibmFtZSI6Im90aGVyLWdyZWV0aW5nLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50fSBmcm9tICdsaXQnO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuaW1wb3J0ICdAbGl0LWxhYnMvdmlydHVhbGl6ZXInO1xuXG5AY3VzdG9tRWxlbWVudCgnb3RoZXItZ3JlZXRpbmcnKVxuZXhwb3J0IGNsYXNzIE90aGVyR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICAgIDpob3N0IHsgXG4gICAgICAgIGRpc3BsYXk6IGJsb2NrO1xuICAgICAgICBoZWlnaHQ6IDIwMHB4O1xuICAgICAgfWA7XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICA8bGl0LXZpcnR1YWxpemVyXG4gICAgICAgIHNjcm9sbGVyIFxuICAgICAgICAuaXRlbXM9JHtBcnJheS5mcm9tKEFycmF5KDEwMCkua2V5cygpKX1cbiAgICAgICAgLnJlbmRlckl0ZW09JHsoaXRlbSkgPT4gaHRtbGA8ZGl2Pk90aGVyICR7aXRlbX08L2Rpdj5gfVxuICAgID5cbiAgICAgPC9saXQtdmlydHVhbGl6ZXI-XG4gICAgYDtcbiAgfVxufVxuIn1d)

cc: @Westbrook

**Comment by graynorton** [comment]
Thanks, @najikahalsema. The current state of things is indeed sloppy and we should clean it up.

In thinking about similar native events (e.g. Element scroll events, media player events), my sense is that both `rangeChanged` and `visibilityChanged` should actually change to become non-bubbling.

In cases where you wanted to "wrap" a virtualizer, you'd be responsible for listening to these events on the wrapped virtualizer and re-dispatching them yourself.

Does this sound reasonable?

cc @usergenic @Westbrook 

---

A bit of additional context:

- The rationale behind the original decision to make these events bubble was not recorded, but I don't believe a ton of thought went into it.
- The current code to stop propagation on `rangeChanged` was added hastily in the process of testing and troubleshooting cases where there are nested virtualizers.
  
  Unlike `visibilityChanged`, which is dispatched purely to meet the needs of site/app-level code, `rangeChanged` is used "internally" by the `<lit-virtualizer>` element and the `virtualize` directive to update the DOM, and things were not working properly because outer virtualizers were re-rendering in response to not only their own `rangeChanged` events but also events dispatched by inner virtualizers.

  At this point, a proper fix would have been to either a) make the event non-bubbling;  or b) add logic to ensure that a virtualizer's internals ignore any `rangeChanged` events not dispatched by its own host element, but I didn't pause and think it through—just "made it work".

**Comment by najikahalsema** [comment]
> In cases where you wanted to "wrap" a virtualizer, you'd be responsible for listening to these events on the wrapped virtualizer and re-dispatching them yourself.
> 
> Does this sound reasonable?

That sounds reasonable to me. It'll match what we already do on `visibilityChanged` events, so I think as long as #3052 gets fixed, this should be no problem. Thank you for your attention!

**Comment by Westbrook** [comment]
Are there really browser native events that don't bubble? 😱 I'm always super shocked when they don't compose, I see you `change` event, but I'd not gotten into ones that didn't bubble. 😬

@graynorton In this case the issues you're protecting for would likely not be solved by having these events bubble but no be composed then, right? It would certainly be much easier to consume with bubbling events, but that's as @najikahalsema pointed out above something that we can overcome on our end so it being "the way this work" (and documented as such) makes it easy to reason about the work on our end.

Right now, due to the structure of our elements, we do a little re-dispatching of events on new hosts already. To support the broader responsibility of a consuming dev to do so, can you export the Event extensions you've made so it's easy for us to "act like LitVirtualizers" when doing so?

**Comment by graynorton** [comment]
> That sounds reasonable to me.

Great!

> can you export the Event extensions you've made so it's easy for us to "act like LitVirtualizers"

Sure, we can export our `Event` subclasses so that you can dispatch events of the same type.

**Comment by usergenic** [comment]
Forgot to close this Issue as fixed by #3609
