### ISSUE TITLE
[labs/ssr] URL is missing in the dom-shim

### ISSUE THREAD

**Issue by hsablonniere** [lit/lit#3168]
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

The global browser `URL` is not available in the `vm` module when using the `renderModule` technique.

### Reproduction

Any component that used the `URL` global class from browsers.

### Workaround

I tried adding it in [`dom-shim`](renderModule) using the global `URL` from Node.js and it works!!

It would be great if it were enabled by default.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

"@lit-labs/ssr": "^2.2.2"

### Browser/OS/Node environment

Node version: 18.0.0
npm version: 8.6.0

**Comment by augustjk** [comment]
I'd be careful about how `URL` is actually used by the component in what's passed into its constructor since something like `window.origin` is unavailable server-side but it could very well be used as a utility for formatting urls or query params to render so it seems sensible to expose the classes that already would be normally available in Node into the VM context.
