### ISSUE TITLE
Consider removing copyright years in lit source code?

### ISSUE THREAD

**Issue by mgenware** [lit/lit#3192]
### Which package is this a feature request for?

Other/unknown (please mention in description)

### Description

After minifying my source code with esbuild, I got some similar copyright code. Turns out these lines are from lit source.

```js
/**
 * @license
 * Copyright 2017 Google LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */
/**
 * @license
 * Copyright 2018 Google LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */
/**
 * @license
 * Copyright 2019 Google LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */
/**
 * @license
 * Copyright 2020 Google LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */
/**
 * @license
 * Copyright 2021 Google LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */

```

### Alternatives and Workarounds

I can always remove some duplicate lines by hand.

**Comment by aomarks** [comment]
While we'd love to do this, unfortunately the current Google open source rules require us to write out the specific year that each file was created.

One thing to note is that since there is so much repetition, all of these headers compress extremely well with gzip or brotli. Plus JavaScript comments are extremely fast to parse. So the practical cost of the duplication is pretty minimal.
