### ISSUE TITLE
createComment is not a function error - lit and lit-html 2.3.0 

### ISSUE THREAD

**Issue by aelbore** [lit/lit#3216]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

using vite and vitest error with latest version of lit
<img width="352" alt="Screenshot 2022-08-15 at 11 11 09 AM" src="https://user-images.githubusercontent.com/18069807/184576085-2f3ff707-587a-4c04-ac7a-04ed60464ae9.png">

### Reproduction

Please check stackblitz URL 

https://stackblitz.com/edit/vitejs-vite-omm8ny

### Workaround

downgrade to `lit@2.2.8` and `lit-html@2.2.7` version 

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

2.3.0

### Browser/OS/Node environment

Chrome 103
MacOSX
Node 16

**Comment by aomarks** [comment]
> https://stackblitz.com/edit/vitejs-vite-omm8ny

Thank you for the report and repro!

I get an error in the console `Uncaught ReferenceError: setupCounter is not defined`. It looks like that function indeed is not defined. Maybe something accidentally removed when pairing down the repro?

**Comment by augustjk** [comment]
I think the issue here is that `vitest` is a node test runner and by default uses the `node` export condition. Here's some relevant comment from a maintainer: https://github.com/vitest-dev/vitest/issues/1588#issuecomment-1173312515

There appears to be an option to potentially override that here https://vitest.dev/config/#transformmode-web

I tried just grabbing all .js files and forcing the transform by inlining all the dependencies in your stackblitz repro and the test command does seem to work.
https://stackblitz.com/edit/vitejs-vite-zwvume?file=vite.config.js

**Comment by aelbore** [comment]
@augustjk yes thanks indeed it works, is this a work around? or do you think lit team has permanent fix? im not sure also if this is lit or vitest/vite issue.

**Comment by aelbore** [comment]
@aomarks i create video reproduce this is base on @augustjk stackblitz repo (above)

https://user-images.githubusercontent.com/18069807/184782535-6458371a-bafb-4e80-a539-f64e7e626c36.mov

**Comment by aelbore** [comment]
@aomarks if you think this not lit issue we can close this

**Comment by augustjk** [comment]
While it's work-aroundable, perhaps we can also add some check here to use an existing `document` if it exists.

https://github.com/lit/lit/blob/ecdb3bcd311772e227f6e2b8e73614471ddf2682/packages/lit-html/src/lit-html.ts#L347-L353
