### ISSUE TITLE
[labs/ssr] ElementRenderer async rendering interoperability?

### ISSUE THREAD

**Issue by nicholasrice** [lit/lit#3219]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

SSR (@lit-labs/ssr)

### Description

Hey! I'm investigating some async SSR scenarios for FAST (which implements its own ElementRenderer and renderer), and at this point I'm unsure how to support async rendering in a way that interoperates with other ElementRenderer / rendering implementations. I saw that @kevinpschaaf took an initial stab at an async rendering implementation here: https://github.com/lit/lit/pull/1690, which adjusts renderShadow to conditionally return promise types. That is what I've been exploring as well, however that implementation circumvents the type system which seems problematic from an interoperability perspective.

Is interoperative async rendering a goal of ElementRenderer and if so, have you considered opening up `ElementRenderer.renderShadow()` and `ElementRenderer.renderLight()` to support promise return types? I understand this would likely degrade the sync rendering scenarios which isn't ideal.

### Alternatives and Workarounds

Are there other ways that ElementRenderer can communicate it should render async, which rendering implementations can *choose* to support? Perhaps a flag that sync renderers could ignore, while async rendering could await until ready? This could keep the ElementRenderer APIs synchronous while offering the rendering process at large the opportunity to be async.

```ts
abstract class ElementRenderer {
	/* ... */
	public readyToRender: true | Promise<true> = true; 
}
```

I'm not sure what the right answer here is, but we've got async rendering scenarios that I'd love to get working in a way that interoperates with other ElementRenderer implementations, so I wanted to start the conversation.

**Comment by justinfagnani** [comment]
I think #1690 is the right direction and we can work on the types to include `string | Promise<string>` on the ElementRenderer interface and have top-level render functions either return `Iterable<string | Promise<string>>` or `Iterable<string>` and throw if they encounter a Promise.

As part of enabling Promises, I think we also want a way of send contextual information to renderers about whether the top-level function can handle Promises. Some renderers might be able to conditionally render sync values, maybe just skipping async work, if the renderer can't handle them.

I don't think adding a Promise to ElementRenderer is sufficient because of the way that the iterables are chained. If a child element is async rendered a parent would have to be too and the parent's promise would depend on its children - otherwise `renderShadow()` would emit Promises when it gets to those async children.

**Comment by nicholasrice** [comment]
Oops yep, that wouldn't work at all, good call. Great, providing async context / configuration to `ElementRenderer` seems like a good approach. Using `RenderInfo` to communicate that seems like it would work well. It is already provided to `ElementRenderer.renderShadow()` and `ElementRenderer.renderLight()` and is used to control other parts of the rendering process.

**Comment by augustjk** [comment]
Completed in https://github.com/lit/lit/pull/3467
