### ISSUE TITLE
[labs/context] SSR compatibility

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#3301]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Context (@lit-labs/context)

### Description

Before graduating `@lit-labs/context` and `@lit-labs/ssr` we should implement context support in SSR. This may be done via general event support in SSR as in #2309, or if that's not feasible, in some other way.

### Alternatives and Workarounds

None

**Comment by dunqan** [comment]
We really support `@lit-labs/context` idea, and it would be really nice to have it working seamlessly with SSR, but our main worries are:

1. It uses an Event based protocol, super nice solution on CSR, doesn't look so nice on SSR, but it looks like Lit is trying to push SSR support for Events because of this.

If lit SSR is a liniear process, idea of using event listeners to the parent (when the parent is partially rendered already) looks like not complete solution (but I agree, will work for limited use cases, like context implementation).
  
2. What about partial hydration, when child component was hydrated before parent was able to setup event listeners?

Did you consider any mechanism of serializing context, so child ements are able to pick it up from the DOM on hydration, without having to hydrate parent first?

**Comment by bennypowers** [comment]
shouldn't the controller attach the listener in hostConnected anyways, rather than in the constructor?

**Comment by justinfagnani** [comment]
@sorvell I'm not sure this should be closed yet. Event support is opt-in and not documented.

**Comment by kyubisation** [comment]
Sorry, that's on me, as I referenced this issue in my PR. Feel free to re-open this.
I can try to add appropriate documentation to lit.dev in January.

**Comment by kyubisation** [comment]
lit/lit.dev#1390
