### ISSUE TITLE
[lit/directives]: async functions as arguments

### ISSUE THREAD

**Issue by timreichen** [lit/lit#3406]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

It would be useful to be able to pass async functions as arguments to the `until` directive. Atm a function has to be wrapped:
```ts
until((async () => {
  // async stuff …
})());
```
Allowing async functions makes the directive more flexible and nicer:
```ts
until(async () => {
  // async stuff …
});
```

### Alternatives and Workarounds

- Writing a custom directive

**Comment by augustjk** [comment]
Hmm.. I feel like taking in a function makes more sense if the directive gets to call it by providing some argument to it, and I can't envision the `until()` directive doing that.

I can see doing an immediately invoked function expression inline seems clunky but in practice I'd prefer to define that async function as a class method and call it to provide the argument.

```js
class MyElement extends LitElement {
  ...

  async getData() {
    const data = await callService();
    return data;
  }

  render() {
    return html`
      <div>
        ${until(getData(), 'loading...')}
      </div>
    `;
  }
}
```

**Comment by timreichen** [comment]
I think that is just unnecessary boilerplate for easy tasks. Why not support both?
There are a lot of directives that use (sync) functions and don't provide arguments (`guard`, `choose`, `when`).
I would rather do this:
```js
class MyElement extends LitElement {
  ...

  render() {
    return html`
      <div>
        ${until(async () => await callService()), 'loading...')}
      </div>
    `;
  }
}
```

**Comment by augustjk** [comment]
This comment here explains more about the problems with taking a function https://github.com/lit/lit/issues/3447#issuecomment-1310844029

**Comment by kevinpschaaf** [comment]
In addition to the discussion linked above, in most cases, you don't actually want to invoke an async function and generate a new promise for _every render_; rather you only want to do something like that when the dependencies of the async function or task change (and when the template re-renders because some text in an unrelated part of the template changed, for example).

The [`@lit-labs/task`](https://www.npmjs.com/package/@lit-labs/task) controller provides a much more robust way to manage running something like `callService()` and rendering its results in your template.

For these reasons, we're unlikely to consider expanding the API of `until`, since we don't think it's ultimately a generally useful way to handle complex async tasks.
