### ISSUE TITLE
[labs/react] Assigning React event handler to undefined overrides LitElement class method if named the same

### ISSUE THREAD

**Issue by vmizgiris-equinix** [lit/lit#3471]
### Which package(s) are affected?

React (@lit-labs/react)

### Description

Passing `undefined` as a property value to a React event handler prop (e.g. onDoSomething) overrides and wipes out the base class method, if the method and the event prop **are named the same** (e.g. internal method this.onDoSomething on the class instance).

A very common use case in React is to wrap common functionality and pass down props to the internal components. When assigning these props, we name them explicitly in the downstream component, but the component prop will always be undefined by default, which results in an explicit assignment of `undefined` values. 

I am providing the reproduction below.

### Reproduction

[Link to Lit playground where the behaviour can be observed](https://lit.dev/playground/#project=W3sibmFtZSI6ImFwcC50c3giLCJjb250ZW50IjoiaW1wb3J0IHtSZWFjdCwgUmVhY3RET019IGZyb20gJy4vcmVhY3QuanMnO1xuaW1wb3J0IHtjcmVhdGVDb21wb25lbnR9IGZyb20gJ0BsaXQtbGFicy9yZWFjdCc7XG5pbXBvcnQge0NvdW50ZXJCdXR0b24gYXMgQ291bnRlckJ1dHRvbldDfSBmcm9tICcuL2NvdW50ZXItYnV0dG9uLmpzJztcblxuY29uc3QgQ291bnRlckJ1dHRvbiA9IGNyZWF0ZUNvbXBvbmVudCh7XG4gIHJlYWN0OiBSZWFjdCxcbiAgdGFnTmFtZTogJ2NvdW50ZXItYnV0dG9uJyxcbiAgZWxlbWVudENsYXNzOiBDb3VudGVyQnV0dG9uV0MsXG4gIC8vIDEuIE1hcCB0aGUgZXZlbnQgZXhwbGljaXRseSB0byBhbiBldmVudCBkaXNwYXRjaGVkIGJ5IHRoZSBjb21wb25lbnQuXG4gIC8vIFRoZSBldmVudCBtYXkgYmUgYSBicm93c2VyIGV2ZW50IG9yIGEgY3VzdG9tIGV2ZW50LiBJJ20gb25seSB1c2luZyB0aGUgJ2NsaWNrJyBldmVudCBoZXJlXG4gIC8vIGZvciBkZW1vbnN0cmF0aW9uLlxuICBldmVudHM6IHsgb25DbGljazogJ2NsaWNrJyB9XG59KTtcblxuY29uc3Qge3VzZUNhbGxiYWNrLCB1c2VTdGF0ZX0gPSBSZWFjdDtcblxuZXhwb3J0IGNvbnN0IEFwcCA9ICgpID0-IHtcbiAgY29uc3QgW2NvdW50LCBzZXRDb3VudF0gPSB1c2VTdGF0ZSgwKTtcblxuICBjb25zdCBvbkNsaWNrID0gdXNlQ2FsbGJhY2soKCkgPT4gc2V0Q291bnQoY291bnQgKyAxKSwgW2NvdW50XSk7XG5cbiAgLy8gMi4gU2V0IHRoZSBjYWxsYmFjayBwcm9wIHRvIHVuZGVmaW5lZCBhbmQgb2JzZXJ2ZSBicm93c2VyIGNvbnNvbGUgd2hlbiB0aGUgYnV0dG9uIGlzIGNsaWNrZWRcbiAgLy8gKHNlZSBjb3VudGVyLWJ1dHRvbi50cyBmb3IgdGhlIGludGVybmFsIGNsaWNrIGhhbmRsZXIpXG4gIHJldHVybiA8Q291bnRlckJ1dHRvbiBvbkNsaWNrPXt1bmRlZmluZWR9IGNvdW50PXtjb3VudH0-PC9Db3VudGVyQnV0dG9uPjtcbn07XG5cbmNvbnN0IG5vZGUgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcjYXBwJyk7XG5jb25zdCByb290ID0gUmVhY3RET00uY3JlYXRlUm9vdChub2RlISk7XG5cbnJvb3QucmVuZGVyKDxBcHA-PC9BcHA-KTtcbiJ9LHsibmFtZSI6ImNvdW50ZXItYnV0dG9uLnRzIiwiY29udGVudCI6ImltcG9ydCB7IGh0bWwsIExpdEVsZW1lbnQgfSBmcm9tICdsaXQnO1xuaW1wb3J0IHsgY3VzdG9tRWxlbWVudCwgcHJvcGVydHkgfSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbkBjdXN0b21FbGVtZW50KCdjb3VudGVyLWJ1dHRvbicpXG5leHBvcnQgY2xhc3MgQ291bnRlckJ1dHRvbiBleHRlbmRzIExpdEVsZW1lbnQge1xuICBAcHJvcGVydHkoeyB0eXBlOiBOdW1iZXIgfSkgY291bnQgPSAwO1xuICBcbiAgLy8gMy4gTm90aWNlIHRoYXQgdGhlIGxvZyBzdGF0ZW1lbnQgZG9lcyBub3QgZ2V0IGV4ZWN1dGVkIGFueW1vcmUuXG4gIC8vIFRoaXMgbWV0aG9kIGdldHMgd2lwZWQgb3V0IGlmIFJlYWN0IHBhc3NlcyB1bmRlZmluZWQgdG8gdGhlIGV2ZW50IGNhbGxiYWNrIHByb3AgdGhhdCBoYXMgYSBtYXRjaGluZyBuYW1lLlxuICAvLyBUaGUgbWV0aG9kIG5hbWUgY291bGQgYmUgYW55dGhpbmcgLSBpdCBkb2VzIG5vdCBuZWVkIHRvIG1hdGNoIFwib24uLi5cIlxuICBwcml2YXRlIG9uQ2xpY2sgPSAoKSA9PiB7XG4gICBjb25zb2xlLmxvZygnVGhpcyBzaG91bGQgYWx3YXlzIGdldCBwcmludGVkIG9uIGJ1dHRvbiBjbGljaycpO1xuICB9O1xuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxidXR0b24gQGNsaWNrPSR7dGhpcy5vbkNsaWNrfT5jbGljayBjb3VudDogJHt0aGlzLmNvdW50fTwvYnV0dG9uPlxuICAgIGA7XG4gIH1cbn1cbiJ9LHsibmFtZSI6InJlYWN0LnRzIiwiY29udGVudCI6Ii8vIGh0dHBzOi8vZ2l0aHViLmNvbS9mYWNlYm9vay9yZWFjdC9pc3N1ZXMvMTAwMjFcbmV4cG9ydCBjb25zdCBSZWFjdCA9ICh3aW5kb3cgYXMgYW55KS5SZWFjdDtcbmV4cG9ydCBjb25zdCBSZWFjdERPTSA9ICh3aW5kb3cgYXMgYW55KS5SZWFjdERPTTtcbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFkb2N0eXBlIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCBzcmM9XCJodHRwczovL3VucGtnLmNvbS9yZWFjdEAxOC91bWQvcmVhY3QuZGV2ZWxvcG1lbnQuanNcIj48L3NjcmlwdD5cbiAgPHNjcmlwdCBzcmM9XCJodHRwczovL3VucGtnLmNvbS9yZWFjdC1kb21AMTgvdW1kL3JlYWN0LWRvbS5kZXZlbG9wbWVudC5qc1wiPjwvc2NyaXB0PlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL2FwcC5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxkaXYgaWQ9XCJhcHBcIj48L2Rpdj5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0)

### Workaround

1. Rename internal class methods so that they never match the mapped event name in React-wrapped component. This is of course not an ideal workaround as we are not able to enforce naming conventions on private/protected class methods.

2. Always assign a default value such as `() => {}` to event handlers in the consumer application. Not desirable, but available as a quick workaround for people who need to fix their app quickly.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

1.1.0

### Browser/OS/Node environment

Browser: Chrome 107.0.5304.110 (Official Build) (x86_64)
OS: macOS 12.6.1
Node version: 18.12.1
npm version: 8.19.2

**Comment by vmizgiris-equinix** [comment]
P.S.: possibly related - https://github.com/lit/lit/issues/3394

**Comment by vmizgiris-equinix** [comment]
Rough guess: wondering if it has to do with this? In the diff below, I've changed the logic back to what it was before 1.1.0:

![image](https://user-images.githubusercontent.com/82578575/202974033-c7ec3eb6-20fa-4aeb-bca6-2fffc23996ae.png)

Seems like the if check was combined (left side) and so in some cases where it finds an event mapping, it won't actually go into this block to add the event listener, and continue with setting the corresponding property on the `node`, which might be the reason mapped event handlers can override class methods?

**Comment by taylor-vann** [comment]
Hey! Thanks for submitting.

I believe this is working as intended.

The changes made in `1.1.0` better reflect expected component behavior in the React ecosystem. The main takeaway being React takes ownership of state. Callbacks are one of the main way users interact with state. Our wrapper takes a function and allows for any method or property on a web component to be set as `props` in a [forwardedRef](https://reactjs.org/docs/forwarding-refs.html) function.

In your example, if no callback is provided or if `undefined` is not provided, the callback initially attached to the element class will be called. However, as soon as a prop is given from react (external to the wrapped web component) the corresponding property will be updated. This includes the value of `undefined` which will remove the event listener from the web component just like in React.

This behavior is demonstrated by the first and third buttons [in this modification of your example].(https://lit.dev/playground/#gist=3d9267ac14d069308fc01e6c7d7351b3).

**Comment by vmizgiris-equinix** [comment]
@taylor-vann, but what about overriding private methods of a class instance? That should not be allowed.

**Comment by taylor-vann** [comment]
I understand the issue.

The class instance method is not removed. The event listener is removed from the a part of the shadow dom inside the web component. Your event listener happens to be a class method, private or otherwise.

After it doesn't fire because the private method is not attached as an event listener but it is still apart of the class.

**Comment by vmizgiris-equinix** [comment]
I'm talking about the private method not firing when the external prop is assigned to undefined, not the event listener.

**Comment by justinfagnani** [comment]
@vmizgiris-equinix 

> we do not expect any methods if they happen to be named the same way in the class instance to be removed from the instance. To me that clearly is a bug and not intentional behaviour.

Setting properties via JSX is just shorthand for assigning them via JS, and this is exactly how JavaScript works.

Consider the following class and property assignment:

```ts
class A {
  go() {
    console.log('A.go!');
  }
}

const a = new A();
a.go = undefined;
a.go();
```

This will not print `"A.go!"` to the console, it will result in a TypeError because `undefined` isn't a function.

You can see what's happening by inspecting the instance and prototypes:
```ts
> a['go']
< undefined

> a.__prototype__['go']
< ƒ go() {
    console.log('A.go!');
  }
```

The prototype still has `go` defined, but it aliased by the instance property `go` because of the property assignment.

This is what's happening when you have a method named `onClick` and try to set an instance property also named `onClick` via JSX.

> Now not only the event handler gets overridden, but the class instance method, which has nothing to do with the event handler, gets wiped out.

It's important to understand that this is just JavaScript semantics: due to property lookup on the prototype chain, a prototype method and an instance property of the same name _do_ have something to do with each other. The instance property is resolved first because it's lower on the prototype chain.

And in your example code you're installing your default onClick handler as an instance field (you don't need to do this in Lit, btw), which is then actually _replaced_ by the property set. Slightly different than the method name collision, but the same effect. Again, standard JavaScript behavior.

If you have a method that's truly internal and shouldn't be overridden, it needs to be named something that won't conflict with a user property. If you're trying to make a system where you have a always-called built-in handler and a potentially-installed user-provided handler, then you'll need two names, like:

```ts
@customElement('counter-button')
export class CounterButton extends LitElement {
  @property({ type: Number }) count = 0;
  
  declare onClick?: (e: MouseEvent) => void;
  
  _onClick(e) {
   this.count++;
   // Call a user onClick if it exists.
   this.onClick.?(e);
  };

  render() {
    return html`
      <button @click=${this._onClick}>click count: ${this.count}</button>
    `;
  }
}
```

**Comment by vmizgiris-equinix** [comment]
@justinfagnani, thanks for the in-depth explanation. I am aware that the prop assignment can override the prototype, but my point is that there is no explicit warning or best practices section where it says you cannot name your internal method this and that because it may conflict with the event handler name.

People who use a library built on Lit components in React or any other library for that matter should rightfully not have to worry about these sort of backdoors and unusual behaviour. If I expose a callback as a prop on my React class-based or functional component, I would never have to worry about naming conventions within my component class or function.

I personally like consistent naming conventions, but there are a lot of folks whose main language is not english and, from a lengthy practical experience, they may not see any difference between "onClick" and "handleClick" for an internal function that is attached to DOM.

**Comment by vmizgiris-equinix** [comment]
> And in your example code you're installing your default onClick handler as an instance field (you don't need to do this in Lit, btw)

My example might not be very clear, but this method is my internal function that could very well be handling some other internal click deeper down in the shadow DOM - it is not a "default" event handler here

**Comment by justinfagnani** [comment]
I understand that this is hard to debug, but it's likewise hard for us to offer warnings because this is fundamental JavaScript behavior. There's actually not an easy way for us to tell that you have a property that you don't intend to be overridden, or that someone has assigned a value to it. It's just a JavaScript object and JSX is just doing assignments.

I would really hesitate to call this behavior anything like a backdoor. There's a property on an object, and then an assignment to that property. This is exactly what we're trying to enable with the React wrapper.

It's possible that the confusion here is with TypeScript's `private` keyword, which surprising to some coming from languages with real privacy, doesn't limit the ability to set or access the property from the outside at all. `private` only influences TypeScript type-checking and it isn't possible (that I know) for us to warn about in JSX checking either.

Real JavaScript private fields with the `#foo` syntax actually helps a lot here, as that is private only to the class and not settable from the outside at all, enforced by the JS runtime. If you can use real private fields - they're pretty well supported in browsers now - I would recommend them.

```ts
@customElement('counter-button')
export class CounterButton extends LitElement {
  @property({ type: Number }) count = 0;
  
  declare onClick?: (e: MouseEvent) => void;
  
  #onClick(e) {
   this.count++;
   // Call a user onClick if it exists.
   this.onClick.?(e);
  };

  render() {
    return html`
      <button @click=${this.#onClick}>click count: ${this.count}</button>
    `;
  }
}
```

**Comment by vmizgiris-equinix** [comment]
I'm aware of how JavaScript works with regards to assignments. All I'm saying here is that the approach taken has non-obvious effects and should be at documented at the very least. The choice to expose methods and properties as JSX props as a whole is also the design choice of Lit, so IMO it's not right to say that JavaScript does not allow not overriding class methods :)
