### ISSUE TITLE
Nested slots ends projecting to the wrong spot

### ISSUE THREAD

**Issue by thiagoaslima-ibge** [lit/lit#3546]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

I was playing with LitElement and tried to reproduce nested lists without success.

Imagine I have the following component:

```
import { html, LitElement } from "lit";
import { customElement } from "lit/decorators.js";

@customElement('custom-ol')
export class CustomOLElement extends LitElement {
  render() {
    return html`
      <ol part="list">
        <slot></slot>
      </ol>
    `;
  }
}
```

And I try to create a list with a sublist like this: 

```
<custom-ol>
      <li>first</li>
      <li>
        second
        <custom-ol>
          <li>sub first</li>
          <li>sub second</li>
        </custom-ol>
      </li>
      <li>third</li>
</custom-ol>
```

I would expect it to behave the same as if I was using plain ol tags.
Instead, all `li` ends projected on the first-level and the inner `custom-ol` slot ends empty.
Worst than that, the browser closes the element on the wrong spot, removing the last li (third) from the list.

Below a snapshot of how the browser renders it. On the left is the custom-ol example, and on the right I replaced custom-ol tag by the plain ol.

<img width="365" alt="ol-render" src="https://user-images.githubusercontent.com/94484525/209922451-60faefc9-1998-41f9-b0e8-32786a738d7f.png">

Also, the DOM tree, showing the last li outside the parent:

<img width="389" alt="dom-tree" src="https://user-images.githubusercontent.com/94484525/209922541-acf25cec-a325-465e-8d0c-91787c32f3c3.png">

Am I doing something wrong here?

### Reproduction

Find an example on:

[lit.dev playground](https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLnRzIiwiY29udGVudCI6ImltcG9ydCB7IGh0bWwsIExpdEVsZW1lbnQgfSBmcm9tICdsaXQnO1xuaW1wb3J0IHsgY3VzdG9tRWxlbWVudCB9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ2N1c3RvbS1vbCcpXG5leHBvcnQgY2xhc3MgQ3VzdG9tT0xFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxvbCBwYXJ0PVwibGlzdFwiPlxuICAgICAgICA8c2xvdD48L3Nsb3Q-XG4gICAgICA8L29sPlxuICAgIGA7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9yZXByby5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxkaXYgc3R5bGU9XCJkaXNwbGF5OiBmbGV4OyBnYXA6IDMwcHg7IGhlaWdodDogMTUwcHhcIj5cbiAgICAgIDxkaXY-XG4gICAgICAgIDxjdXN0b20tb2w-XG4gICAgICAgICAgPGxpPmZpcnN0PC9saT5cbiAgICAgICAgICA8bGk-XG4gICAgICAgICAgICBzZWNvbmRcbiAgICAgICAgICAgIDxjdXN0b20tb2w-XG4gICAgICAgICAgICAgIDxsaT5zdWIgZmlyc3Q8L2xpPlxuICAgICAgICAgICAgICA8bGk-c3ViIHNlY29uZDwvbGk-XG4gICAgICAgICAgICA8L2N1c3RvbS1vbD5cbiAgICAgICAgICA8L2xpPlxuICAgICAgICAgIDxsaT50aGlyZDwvbGk-XG4gICAgICAgIDwvY3VzdG9tLW9sPlxuICAgICAgPC9kaXY-XG5cbiAgICAgIDxvbD5cbiAgICAgICAgPGxpPmZpcnN0PC9saT5cbiAgICAgICAgPGxpPlxuICAgICAgICAgIHNlY29uZFxuICAgICAgICAgIDxvbD5cbiAgICAgICAgICAgIDxsaT5zdWIgZmlyc3Q8L2xpPlxuICAgICAgICAgICAgPGxpPnN1YiBzZWNvbmQ8L2xpPlxuICAgICAgICAgIDwvb2w-XG4gICAgICAgIDwvbGk-XG4gICAgICAgIDxsaT50aGlyZDwvbGk-XG4gICAgICA8L29sPlxuICAgIDwvZGl2PlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ) 

[Stackblitz](https://stackblitz.com/edit/vitejs-vite-ryv6sw?file=index.html)

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.4.1

### Browser/OS/Node environment

Chrome 108.0.5359.124
MacOS 12.6

**Comment by thiagoaslima-ibge** [comment]
Another thing I just noticed is, if I replace `li` by `div` inside the inner `custom-ol`, the items get projected correctly. I've updated the Stackblitz example to show this case as well.

**Comment by p-ob** [comment]
I don't believe `<li>` elements can be used within any arbitrary parent element. They can only be used in `<ul>`, `<ol>`, or `<menu>`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li.

You could solve this by making the consumer provide the `<ol>` themselves in the slot:

```html
        <custom-ol>
          <ol>
            <li>first</li>
            <li>
              second
              <custom-ol>
                <ol>
                  <li>sub first</li>
                  <li>sub second</li>
                </ol>
              </custom-ol>
            </li>
            <li>third</li>
          </ol>
        </custom-ol>
```

which results in the expected rendering:
![image](https://user-images.githubusercontent.com/3483866/209986303-1b019c54-1bcc-4689-a8d2-c8abbbc43393.png)

If only we could extend built-in elements and have full browser interoperability :)

**Comment by thiagoaslima-ibge** [comment]
@p-ob Thanks for your response. 
So, for what I understand, the slot projection enforces a valid html, and will rearrange things based on it.
Is it right?

**Comment by p-ob** [comment]
I actually just think the browser's HTML parser, ignoring the slot, is trying to figure out the correct structure. Since this is technically invalid HTML, it's trying to figure out the "best" way to render it. The output HTML markup (ignoring the shadow DOM from your element) is the following:
![image](https://user-images.githubusercontent.com/3483866/210005423-53bcf09f-1230-44c4-8b05-0dcc157961e4.png)

It's confused by the HTML, promotes the nested `<li>`s up a level and then evicts the final `<li>`. 

You can get a similar experience without custom elements at all: https://stackblitz.com/edit/vitejs-vite-hjptw4?file=index.html

Notice how the `<li>` labelled "third" still gets evicted:
![image](https://user-images.githubusercontent.com/3483866/210005714-b9ecbf3b-fe58-4d1b-9c83-231608a5ae28.png)

**Comment by kevinpschaaf** [comment]
I'm going to close this issue, as the reported undesired behavior is a function of the HTML spec and not something that Lit can change. 

For background, the [Customized Built-Ins](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#:~:text=popup%2Dinfo%22\).-,Customized%20built%2Din%20elements,-inherit%20from%20basic) portion of the HTML spec allows for making a custom `<ol>` tag that can accept `<li>` children directly, however Webkit has not shipped this portion of the spec due to long-standing opposition to it (you can read more background on the [WebKit tracker](https://bugs.webkit.org/show_bug.cgi?id=182671) and [Webkit Standards Positions](https://github.com/WebKit/standards-positions/issues/97). As such, you cannot rely on this feature in production without a polyfill.

Short of that, achieving what you want would require a change in the [HTML parsing spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element:~:text=None.-,Contexts%20in%20which%20this%20element%20can%20be%20used%3A,-Inside%20ol%20elements), which would be _very_ unlikely to receive traction. Please consider the alternatives listed above (slotting the `<ol>` as well, choosing a different element such as `<div>` for the list items etc.).
