### ISSUE TITLE
[labs/task] Task improperly warns user about rendering

### ISSUE THREAD

**Issue by DaveStein** [lit/lit#3566]
### Which package(s) are affected?

Task (@lit-labs/task)

### Description

Using the default `render` from `Task` results in a console warning.

![image](https://user-images.githubusercontent.com/472727/212441785-f01ea21d-750e-4008-a1bb-47cd979fa5ac.png)

### Reproduction

The following class warns user there is an issue, despite just following default examples.

```js
export class WorldPosts extends LitElement {
  posts: Post[] = [];

  private _apiTask = new Task(this, {
    task: async () => {
      console.log('demo time');
      return [
        {
          message: 'hello',
        },
      ];
    },
     // this will autorun, but not run automatically on any subsequent updates since it tracks no args
    args: () => [],
  });

  render() {
    return html`
      ${this._apiTask.render({
        complete: (posts: Post[]) => {
          const list = posts.map(post => html`<li>${post.message}</li>`);

          return html`<ul>
            ${list}
          </ul>`;
        },
        error: console.error,
      })}
    `;
  }
}
```

### Workaround

Possibly overwriting update methods? Not sure

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.5.0

### Browser/OS/Node environment

Browser: Chrome
OS: 13.1 (22C65)

**Comment by kevinpschaaf** [comment]
Confirmed in [playground](https://lit.dev/playground/#gist=c437a9a806626df6219669aab81e81c0) that the `requestUpdate()` will always happen via a synchronous call path (regardless of the task fn provided): `hostUpdated()` -> `performUpdate()` -> `run()` -> [`requestUpdate()`](https://github.com/lit/lit/blob/main/packages/labs/task/src/task.ts#L207), leading to the warning. The warning is real, as in it looks like Task will always result in a double-render.

Seems like the `performUpdate()` should probably be called from `hostUpdate()` timing instead of `hostUpdated()`, so that we don't need to do a `requestUpdate()` to see e.g. the initial change to pending state.

@sorvell @justinfagnani Any downsides to making that change?

**Comment by kevinpschaaf** [comment]
Thanks, didn't see the comment up there.

```js
// 3. If this is instead or additionally triggered in `willUpdate`, the
// warning goes away in the common case that the update itself does not change
// the deps; however, the `requestUpdate` to render pending state  will not
// trigger another update since the element is updating. This `requestUpdate`
// could be triggered in updated, but that results in the same issue as #2.
```
This part doesn't make sense to me, @sorvell. Why is the discussion of when to call `requestUpdate()` relevant when considering moving task's `performUpdate()` to `willUpdate()`/`hostUpdate()` timing? Calling `requestUpdate()` to reflect any change to the task state should be unnecessary, since we're about to call `render()`.

> in the common case that the update itself does not change the deps

I also don't follow how/why an update changing the input deps to a task would ever be a thing we try to support. That feels circular and anti-pattern-ish -- updates should never _cause_ state changes, only reflect them to the rendering -- but maybe I'm missing a key use case?

**Comment by tbroyer** [comment]
Fwiw, I'd rather have the pending state right when the args change triggers the task (so `performUpdate()` called from `willUpdate()`/`hostUpdate()`), but `requestUpdate()` still has to be called from the `run()` when the task is not triggered by args change but manually. Maybe refactor with 2 code paths: one from `run()` that calls `requestUpdate()`, and another from `hostUpdate()` that doesn't?

**Comment by justinfagnani** [comment]
I think we can change timing to `hostUpdate()`.

If component authors put their computed state updated in `willUpdate()`, then `hostUpdate()` should be good timing to start the task. If they override `update()`, then the have to compute state before `super.update()`, which is already usually the case. State updated after that will still be visible to the task if the host triggers another update cycle on its own.
