### ISSUE TITLE
[labs/context] Request to allow custom ContextProvider in @provide decorator

### ISSUE THREAD

**Issue by jrj2211** [lit/lit#3692]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Context (@lit-labs/context)

### Description
I've been having a discussion in #3685 about how to deal with using an instance of a class as the value for the context value. Issue is, I want to encapsulate the logic for something, such as a timer that keeps track of the timer and status (stop, running, paused) without having to make the providing element know anything about it - aka it should be able to update its internal values itself.

@vdegenne informed me I could do this with a reactive controller. Since `ContextProvider` is already a reactive controller, I modified his example to extend `ContextProvider`, cutting out a bunch of code and allowing the timer to call setValue directly and without having to add another function to the providing element. Works pretty well:

[Playground Demo](https://tinyurl.com/context-provider-extend)

### Proposal
Issue is I cannot use `@provide()` directly as that forces creation of a ContextProvider. What I'd like to see is the ability to optionally pass in a provider class to use for that. I think this unlocks a lot of deeper possibilities with context providers if you can make your own custom provider class.

```
@provide({ context: timerContext, provider: TimerProvider});
```

### Alternatives and Workarounds

Don't use the decorator and manually call it but that's no fun:

```
public timerContext = new TimerProvider(this, timerContext); 
```

**Comment by rictic** [comment]
The `@provide` decorator is intended for providing values set into the decorated field. Your example syntax isn't legal JS or TS because there isn't a decorated member:

```ts
@provide({ context: timerContext, provider: TimerProvider});
```

**Comment by joezappie** [comment]
@rictic Could this be relooked at? I'm back to wishing something like this was built into Lit.

I apologize for not including the full example and just showing what I thought the @provide syntax should be. I've updated my [Lit Playground Example](https://lit.dev/playground/#sample=examples%2Fdirective-template-content&project=W3sibmFtZSI6Im15LWVsZW1lbnQudHMiLCJjb250ZW50IjoiXG5pbXBvcnQgeyBMaXRFbGVtZW50LCBodG1sLCBjc3MsIFJlYWN0aXZlQ29udHJvbGxlciB9IGZyb20gJ2xpdCc7XG5pbXBvcnQgeyBjb25zdW1lLCBjcmVhdGVDb250ZXh0LCBDb250ZXh0LCBDb250ZXh0UHJvdmlkZXIgfSBmcm9tICdAbGl0LWxhYnMvY29udGV4dCc7XG5pbXBvcnQgeyBjdXN0b21FbGVtZW50LCBwcm9wZXJ0eSB9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCB7Y2hvb3NlfSBmcm9tICdsaXQvZGlyZWN0aXZlcy9jaG9vc2UuanMnO1xuaW1wb3J0IHtSZWFjdGl2ZUVsZW1lbnR9IGZyb20gJ0BsaXQvcmVhY3RpdmUtZWxlbWVudCc7XG5pbXBvcnQge2RlY29yYXRlUHJvcGVydHl9IGZyb20gJ0BsaXQvcmVhY3RpdmUtZWxlbWVudC9kZWNvcmF0b3JzL2Jhc2UuanMnO1xuXG5leHBvcnQgY29uc3QgdGltZXJDb250ZXh0ID0gY3JlYXRlQ29udGV4dCgndGltZXInKTtcblxuLy8gTU9ESUZJRUQgUFJPVklERSBERUNPUkFUT1IgRlJPTSBMSVQvQ09OVEVYVFxuLy8gaHR0cHM6Ly9naXRodWIuY29tL2xpdC9saXQvYmxvYi9tYWluL3BhY2thZ2VzL2NvbnRleHQvc3JjL2xpYi9kZWNvcmF0b3JzL3Byb3ZpZGUudHNcbmZ1bmN0aW9uIHByb3ZpZGUoeyBjb250ZXh0LCBwcm92aWRlciB9KSB7XG4gIHJldHVybiAoKHByb3RvT3JUYXJnZXQsbmFtZU9yQ29udGV4dCkgPT4ge1xuICAgIC8vIE1hcCBvZiBpbnN0YW5jZXMgdG8gY29udHJvbGxlcnNcbiAgICBjb25zdCBjb250cm9sbGVyTWFwID0gbmV3IFdlYWtNYXAoKTtcblxuICAgIGlmICh0eXBlb2YgbmFtZU9yQ29udGV4dCA9PT0gJ29iamVjdCcpIHtcbiAgICAgIC8vIFN0YW5kYXJkIGRlY29yYXRvcnMgYnJhbmNoXG4gICAgICBuYW1lT3JDb250ZXh0LmFkZEluaXRpYWxpemVyKGZ1bmN0aW9uICh0aGlzKSB7XG4gICAgICAgIGNvbnN0IFByb3ZpZGVyQ2xhc3MgPSBwcm92aWRlciB8fCBDb250ZXh0UHJvdmlkZXI7XG4gICAgICAgIGNvbnRyb2xsZXJNYXAuc2V0KHRoaXMsIG5ldyBDb250ZXh0UHJvdmlkZXIodGhpcywge2NvbnRleHR9KSk7XG4gICAgICB9KTtcbiAgICAgIHJldHVybiB7XG4gICAgICAgIGdldCh0aGlzKSB7XG4gICAgICAgICAgcmV0dXJuIHByb3RvT3JUYXJnZXQuZ2V0LmNhbGwodGhpcyk7XG4gICAgICAgIH0sXG4gICAgICAgIHNldCh0aGlzLCB2YWx1ZSkge1xuICAgICAgICAgIGNvbnRyb2xsZXJNYXAuZ2V0KHRoaXMpPy5zZXRWYWx1ZSh2YWx1ZSk7XG4gICAgICAgICAgcmV0dXJuIHByb3RvT3JUYXJnZXQuc2V0LmNhbGwodGhpcywgdmFsdWUpO1xuICAgICAgICB9LFxuICAgICAgICBpbml0KHRoaXMsIHZhbHVlKSB7XG4gICAgICAgICAgY29udHJvbGxlck1hcC5nZXQodGhpcyk_LnNldFZhbHVlKHZhbHVlKTtcbiAgICAgICAgICByZXR1cm4gdmFsdWU7XG4gICAgICAgIH0sXG4gICAgICB9O1xuICAgIH0gZWxzZSB7XG4gICAgICAvLyBFeHBlcmltZW50YWwgZGVjb3JhdG9ycyBicmFuY2hcbiAgICAgIChwcm90b09yVGFyZ2V0LmNvbnN0cnVjdG9yIGFzIHR5cGVvZiBSZWFjdGl2ZUVsZW1lbnQpLmFkZEluaXRpYWxpemVyKFxuICAgICAgICAoZWxlbWVudCkgPT4ge1xuICAgICAgICAgIGNvbnN0IFByb3ZpZGVyQ2xhc3MgPSBwcm92aWRlciB8fCBDb250ZXh0UHJvdmlkZXI7XG4gICAgICAgICAgY29udHJvbGxlck1hcC5zZXQoZWxlbWVudCwgbmV3IFByb3ZpZGVyQ2xhc3MoZWxlbWVudCwge2NvbnRleHR9KSk7XG4gICAgICAgIH1cbiAgICAgICk7XG4gICAgICAvLyBwcm94eSBhbnkgZXhpc3Rpbmcgc2V0dGVyIGZvciB0aGlzIHByb3BlcnR5IGFuZCB1c2UgaXQgdG9cbiAgICAgIC8vIG5vdGlmeSB0aGUgY29udHJvbGxlciBvZiBhbiB1cGRhdGVkIHZhbHVlXG4gICAgICBjb25zdCBkZXNjcmlwdG9yID0gT2JqZWN0LmdldE93blByb3BlcnR5RGVzY3JpcHRvcihcbiAgICAgICAgcHJvdG9PclRhcmdldCxcbiAgICAgICAgbmFtZU9yQ29udGV4dFxuICAgICAgKTtcbiAgICAgIGxldCBuZXdEZXNjcmlwdG9yO1xuICAgICAgaWYgKGRlc2NyaXB0b3IgPT09IHVuZGVmaW5lZCkge1xuICAgICAgICBjb25zdCB2YWx1ZU1hcCA9IG5ldyBXZWFrTWFwKCk7XG4gICAgICAgIG5ld0Rlc2NyaXB0b3IgPSB7XG4gICAgICAgICAgZ2V0OiBmdW5jdGlvbiAodGhpcykge1xuICAgICAgICAgICAgcmV0dXJuIHZhbHVlTWFwLmdldCh0aGlzKTtcbiAgICAgICAgICB9LFxuICAgICAgICAgIHNldDogZnVuY3Rpb24gKHRoaXMsIHZhbHVlKSB7XG4gICAgICAgICAgICBjb250cm9sbGVyTWFwLmdldCh0aGlzKSEuc2V0VmFsdWUodmFsdWUpO1xuICAgICAgICAgICAgdmFsdWVNYXAuc2V0KHRoaXMsIHZhbHVlKTtcbiAgICAgICAgICB9LFxuICAgICAgICAgIGNvbmZpZ3VyYWJsZTogdHJ1ZSxcbiAgICAgICAgICBlbnVtZXJhYmxlOiB0cnVlLFxuICAgICAgICB9O1xuICAgICAgfSBlbHNlIHtcbiAgICAgICAgY29uc3Qgb2xkU2V0dGVyID0gZGVzY3JpcHRvci5zZXQ7XG4gICAgICAgIG5ld0Rlc2NyaXB0b3IgPSB7XG4gICAgICAgICAgLi4uZGVzY3JpcHRvcixcbiAgICAgICAgICBzZXQ6IGZ1bmN0aW9uICh0aGlzLCB2YWx1ZSkge1xuICAgICAgICAgICAgY29udHJvbGxlck1hcC5nZXQodGhpcykhLnNldFZhbHVlKHZhbHVlKTtcbiAgICAgICAgICAgIG9sZFNldHRlcj8uY2FsbCh0aGlzLCB2YWx1ZSk7XG4gICAgICAgICAgfSxcbiAgICAgICAgfTtcbiAgICAgIH1cbiAgICAgIE9iamVjdC5kZWZpbmVQcm9wZXJ0eShwcm90b09yVGFyZ2V0LCBuYW1lT3JDb250ZXh0LCBuZXdEZXNjcmlwdG9yKTtcbiAgICAgIHJldHVybjtcbiAgICB9XG4gIH0pIGFzIGFueTtcbn1cblxuXG4vLyBNYWtlIGEgY3VzdG9tIHByb3ZpZGVyIHRoYXQgY2FuIGhhbmRsZSBpdHMgb3duIHN0YXRlXG5jbGFzcyBUaW1lclByb3ZpZGVyIGV4dGVuZHMgQ29udGV4dFByb3ZpZGVyPGFueT4ge1xuICBzdGF0aWMgU1RBVEVTID0ge0lETEU6MCwgUlVOTklORzoxfTtcbiAgY29uc3RydWN0b3IoaG9zdCwgY29udGV4dCwgaW5pdGlhbERhdGEgPSBudWxsKSB7XG4gICAgc3VwZXIoaG9zdCwgY29udGV4dCwgaW5pdGlhbERhdGEpO1xuICAgIHRoaXMuc2V0VmFsdWUodGhpcywgdHJ1ZSk7XG4gIH1cbiAgXG4gIGludGVydmFsID0gbnVsbDtcbiAgXG4gIF9zdGF0ZSA9IFRpbWVyUHJvdmlkZXIuU1RBVEVTLklETEU7XG4gIGdldCBzdGF0ZSgpIHsgcmV0dXJuIHRoaXMuX3N0YXRlIH1cbiAgc2V0IHN0YXRlKHYpIHsgdGhpcy5fc3RhdGUgPSB2OyB0aGlzLnNldFZhbHVlKHRoaXMsIHRydWUpfVxuICBcbiAgX2NvdW50ID0gMDtcbiAgZ2V0IGNvdW50KCkgeyByZXR1cm4gdGhpcy5fY291bnQgfVxuICBzZXQgY291bnQodikgeyB0aGlzLl9jb3VudCA9IHY7IHRoaXMuc2V0VmFsdWUodGhpcywgdHJ1ZSkgfVxuICBcbiAgc3RhcnQoKSB7XG4gICAgdGhpcy5zdGF0ZSA9IFRpbWVyUHJvdmlkZXIuU1RBVEVTLlJVTk5JTkc7XG4gICAgdGhpcy5jb3VudCA9IDA7XG4gICAgdGhpcy5fY3JlYXRlSW50ZXJ2YWwoKTtcbiAgfVxuICBcbiAgc3RvcCgpIHtcbiAgICB0aGlzLnN0YXRlID0gVGltZXJQcm92aWRlci5TVEFURVMuSURMRTsgXG4gICAgY2xlYXJJbnRlcnZhbCh0aGlzLmludGVydmFsKTtcbiAgfVxuICBcbiAgX2NyZWF0ZUludGVydmFsKCkge1xuICAgIGNsZWFySW50ZXJ2YWwodGhpcy5pbnRlcnZhbCk7XG4gICAgdGhpcy5pbnRlcnZhbCA9IHNldEludGVydmFsKCgpID0-IHsgdGhpcy5jb3VudCArPSAxIH0sIDEwMDApO1xuICB9XG59XG5cbi8vIEVsZW1lbnQgZm9yIGNvbnRyb2xsaW5nIHRoZSBzdGF0ZSBvZiB0aGUgdGltZXJcbkBjdXN0b21FbGVtZW50KCd0aW1lci1idXR0b25zJylcbmNsYXNzIFRpbWVyQnV0dG9ucyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBAY29uc3VtZSh7Y29udGV4dDogdGltZXJDb250ZXh0LCBzdWJzY3JpYmU6IHRydWV9KVxuICBAcHJvcGVydHkoe2F0dHJpYnV0ZTogZmFsc2V9KVxuICB0aW1lcjtcblxuICByZW5kZXIoKSB7XG4gICByZXR1cm4gaHRtbGAgXG4gICAgICAgJHtjaG9vc2UodGhpcy50aW1lci5zdGF0ZSwgW1xuICAgICAgICAgW1RpbWVyUHJvdmlkZXIuU1RBVEVTLklETEUsICgpID0-IGh0bWxgXG4gICAgICAgICAgIDxidXR0b24gQGNsaWNrPSR7KCkgPT4gdGhpcy50aW1lci5zdGFydCgpfT5TdGFydDwvYnV0dG9uPlxuICAgICAgICAgYF0sXG4gICAgICAgICBbVGltZXJQcm92aWRlci5TVEFURVMuUlVOTklORywgKCkgPT4gaHRtbGBcbiAgICAgICAgICAgPGJ1dHRvbiBAY2xpY2s9JHsoKSA9PiB0aGlzLnRpbWVyLnN0b3AoKX0-U3RvcDwvYnV0dG9uPlxuICAgICAgICAgYF1cbiAgICAgICBdKX1cbiAgIGA7XG4gIH1cbn1cblxuLy8gRWxlbWVudCB0byBzaG93IHRoZSBjdXJyZW50IHRpbWVyIHZhbHVlXG5AY3VzdG9tRWxlbWVudCgndGltZXItZGlzcGxheScpXG5jbGFzcyBUaW1lckRpc3BsYXkgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgQGNvbnN1bWUoe2NvbnRleHQ6IHRpbWVyQ29udGV4dCwgc3Vic2NyaWJlOiB0cnVlfSlcbiAgQHByb3BlcnR5KHthdHRyaWJ1dGU6IGZhbHNlfSlcbiAgdGltZXI7IFxuICBcbiAgcmVuZGVyKCkge1xuICAgcmV0dXJuIGh0bWxgPGRpdj4ke3RoaXMudGltZXIuY291bnR9YDtcbiAgfVxufVxuXG4vLyBFbGVtZW50IHRvIGNvbWJpbmUgdGltZXIgZnVuY3Rpb25hbGl0eVxuQGN1c3RvbUVsZW1lbnQoJ3RpbWVyLWNvbXBvbmVudCcpXG5jbGFzcyBUaW1lckNvbXBvbmVudCBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYDpob3N0IHsgYm9yZGVyOjFweCBzb2xpZCBncmF5O21hcmdpbjogMjBweDsgcGFkZGluZzoyMHB4OyBkaXNwbGF5OiBibG9jazsgfWA7XG4gIFxuICAvLyBQYXNzIGluIHRoZSBjdXN0b20gdGltZXIgcHJvdmlkZXIgdGhhdCBoYXMgaXRzIG93biBsb2dpY1xuICBAcHJvdmlkZSh7Y29udGV4dDogdGltZXJDb250ZXh0LCBwcm92aWRlcjogVGltZXJQcm92aWRlcn0pXG4gIHRpbWVyO1xuICBcbiAgQHByb3BlcnR5KHt0eXBlOiBTdHJpbmd9KVxuICB0aXRsZTtcbiAgXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgICAgPGNvbnRlbnQ-XG4gICAgICAgICAgPGRpdj4ke3RoaXMudGl0bGV9PC9kaXY-XG4gICAgICAgICAgPHRpbWVyLWJ1dHRvbnM-PC90aW1lci1idXR0b25zPlxuICAgICAgICAgIDx0aW1lci1kaXNwbGF5PjwvdGltZXItZGlzcGxheT5cbiAgICAgICAgPC9jb250ZW50PlxuICAgICAgICBcbiAgICBgO1xuICB9XG59XG5cbi8vIFNpdGUgcm9vdCBlbGVtZW50XG5AY3VzdG9tRWxlbWVudCgnYXBwLWNvbnRhaW5lcicpXG5jbGFzcyBBcHBDb250YWluZXIgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgICA8dGltZXItY29tcG9uZW50IHRpdGxlPSdUaW1lciAxJz48L3RpbWVyLWNvbXBvbmVudD5cbiAgICAgICAgPHRpbWVyLWNvbXBvbmVudCB0aXRsZT0nVGltZXIgMic-PC90aW1lci1jb21wb25lbnQ-XG4gICAgYDtcbiAgfVxufVxuXG5cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPHN0eWxlPlxuICBib2R5IHsgZm9udC1mYW1pbHk6IHNhbnMtc2VyaWY7IH1cbjwvc3R5bGU-XG5cbjxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vbXktZWxlbWVudC5qc1wiPjwvc2NyaXB0PlxuXG48YXBwLWNvbnRhaW5lcj48L2FwcC1jb250YWluZXI-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d) where I've modified the `@provide` decorator to allow a custom `ContextProvider` to be used.


Heres a snippet from the playground of the **very minor** changes I'd like to see to allow overriding the default ContextProvider. It would have no changes to any current projects, but would allow more flexibility.

```
function provide({ context, provider }) {
  return ((protoOrTarget,nameOrContext) => {
      ...

      // Standard decorators branch
      nameOrContext.addInitializer(function (this) {
        const ProviderClass = provider || ContextProvider;
        controllerMap.set(this, new ContextProvider(this, {context}));
      });

     ...
  });
}
```

The end goal here is to have a provided object that is able to update itself. I do not see anyway this is possible without using a custom ContextProvider.

The issue is if I want to bundle logic for controlling a timer, I cant just make a Timer class and provide that as that timer has no way of telling its consumer its updated. In the following example, the consumer will never update because the reference to the object isnt changing. The only way I see this is possible is bundling the timer logic into a ContextProvider.

```
class Timer {
   value = 0;

  tick() {
     value += 1;
  } 
}

class AppContainer extends LitElement {
  @provide({ context: timerContext })
  timer = new Timer();
  
  constructor() {
    super();
    setInterval(() => {
    timer.tick();
    });
  }
}

class TimerDisplay extends LitElement {
  @consume({ context: timerContext, subscribe?: boolean })
  timer;

  render() {
    return html`Time is ${this.timer.value}`;
  }
```

**Comment by justinfagnani** [comment]
@joezappie I think this is a misuse of ContextProvider. It's not meant to be a general solution for observable state, it's mean to allow passing values down a tree. What you're doing with `this.setValue(this, true)` is telling all consumers that there's a new Timer, when there isn't. Our intention with context is definitely not to encourage every observable object to _be_ a context.

What I would do is make an observable Timer class. There are several options including EventTarget, signals, observables, etc. We have a `@lit-labs/preact-signals` package this you could use now.

One of the most platform-centric and bare-bones way to be observable is to implement EventTarget. Then the consumer just has to listen to an event and update. I've made a decorator to make this more ergonomic before:

```ts
const listeners = new WeakMap<Element, () => void>();

/**
 * A property decorator that subscribes to an event on the property value and
 * calls `requestUpdate` when the event fires.
 */
export const updateOnEvent = (eventName: string) => (target: ReactiveElement, propertyKey: string) => {
  const descriptor = Object.getOwnPropertyDescriptor(target, propertyKey)!;

  const {get, set} = descriptor;
  const newDescriptor = {
    ...descriptor,
    set(this: ReactiveElement, v: EventTarget) {
      let listener = listeners.get(this);
      if (listener === undefined) {
        listeners.set(this, listener = () => this.requestUpdate());
      }
      const oldValue = get!.call(this);
      oldValue?.removeEventListener?.(eventName, listener);
      v?.addEventListener?.(eventName, listener);
      return set!.call(this, v);
    },
  };
  Object.defineProperty(target, propertyKey, newDescriptor);
};
```

I've update your playground top use this: https://lit.dev/playground/#gist=e3600ffc30ff9359404d4268c59d22a7

**Comment by joezappie** [comment]
@justinfagnani Thank you for the fast reply! 

I think what you've shown is an excellent solution to what I'm looking to do. I agree, I always felt weird trying to turn the provider into a controller.

I also like that components can subscribe to different events if only certain parts of the controller affect their display. Lots of flexibility there, awesome!
