### ISSUE TITLE
CSP style-src violation with lit html

### ISSUE THREAD

**Issue by OnurGumus** [lit/lit#3722]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When I try to use lit-html the following line fails with style-src violation

https://github.com/lit/lit/blob/c10df5d71ed08e4834959fe1ed9e865f13c0e31b/packages/lit-html/src/lit-html.ts#L1021
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/4114592/224680705-9f195db4-fedc-4af9-9cbc-f88882902173.png">

### Reproduction

I am not sure but repros on latest Edge browser

### Workaround

Need to use unsafe-hash

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.6.1

### Browser/OS/Node environment

Edge : 111, MacOs

**Comment by justinfagnani** [comment]
Given the location of the error, which is creating a `<template>` element, not a `<style>` element, I have to guess that youre template strings have a `<style>` tag in them. In that case you need to add a nonce attribute to the style tag.

If you use LitElements's static `styles` property instead, we already support adding a nonce, with the global `litNonce` variable. See https://lit.dev/docs/api/ReactiveElement/#ReactiveElement.styles

Note that a nonce really should be set to a unique value for every request, otherwise it's guessable and not a good security mechanism. That means that if you set the `nonce` attribute in a template it should be bound to a variable that's set per-request. You could use `global.litNonce` for that too, so the same nonce will work for static `styles`.

**Comment by OnurGumus** [comment]
Thanks @justinfagnani this was in deed helpful. It wasn't the template tag but I noticed I have used inline style for a div down stream. Moving it to proper style file fixed the problem.
