### ISSUE TITLE
[localize-tools] Transform mode using rollup is broken with typescript >= ~4.9

### ISSUE THREAD

**Issue by jpzwarte** [lit/lit#3739]
### Which package(s) are affected?

Localize (@lit/localize)

### Description

When I run `rollup -c` with the `localeTransformer` configured, it no longer replaces any `msg('...')` calls in the outputted files.

### Reproduction

See https://github.com/jpzwarte/lit-localize-rollup-bug

### Workaround

Not very practical, but if I downgrade the project version of typescript to 4.7.4 (the same as what the Lit tools use), then it works as expected again.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

`@lit/localize-tools@0.6.7`

TypeScript ~4.7: ✅
TypeScript ~4.8: ✅
TypeScript ~4.9: ❌
TypeScript ~5.0: ❌

### Browser/OS/Node environment

-

**Comment by jpzwarte** [comment]
I'm trying to debug this, but it seems like the `Transformer.visitNode` in `transform.js` is only getting called for the *entire* `foo.ts` file. `visitEachChild` is broken/doesn't work as expected anymore?

**Comment by 43081j** [comment]
FYI this is a slightly deeper problem

localize-tools has its own typescript dependency which can differ from the one the consumer has.

when you call rollup, it will have its own typescript which it uses to create an AST. it passes that into your custom transform (localize-tools) which has its own typescript version it tries to pass the AST on to.

problem is, between typescript versions the AST can be incompatible as the `SyntaxKind` changes (so visitors won't run as expected because they won't be aware of the right kinds).

would be ideal if the rollup plugin gave you the instance of typescript you can call instead of importing it

**Comment by jpzwarte** [comment]
`@rollup/plugin-typescript` uses the project typescript version afaict: "Default: peer dependency" (https://github.com/rollup/plugins/tree/master/packages/typescript/#typescript

So there are 2 versions of typescript here: the project one and the localize-tools one.

**Comment by 43081j** [comment]
Yes it does, exactly. 

Really it should pass the typescript module through to transformers I suppose, or localize can only ever work with compatible syntax trees

**Comment by aomarks** [comment]
We've been using `~` semver constraint, because TypeScript doesn't use semver and introduces breaking changes with minor releases. We could maybe relax this to `^` for localize-tools, which would mean in your repro the typescript version would have been deduped to `4.9.5`. If I `rm -rf node_modules/@lit/localize-tools/node_modules/typescript` then the repro works.
