### ISSUE TITLE
[lit-html] styleMap breaks if value is a number

### ISSUE THREAD

**Issue by dklemmt** [lit/lit#3787]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

While adding a check for !important in styleMap (line 104) in version 2.7.1 it is not checked if this value is a **string**. In case of z-index the value will be a number and the check will crash as 'endsWith' naturally expects a string.

In our system we're using an older fixed version of Lit (2.6.x) but lit always grabs the latest version for lit-element or lit-html due to ^ which is not what you would expect. Even while setting a fixed version npm i crashed our applications as it installed the latest versions as dependency. Would be better to fix the version for lit sub-packages to be sure to get always the version you request.

Thanks :)

### Reproduction

Use z-index with a number.

### Workaround

Adding lit-html in version 2.7.0 or lower as dependency

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

2.7.1

### Browser/OS/Node environment

not relevant

**Comment by justinfagnani** [comment]
Our typings say that styleMap values can only be strings, so if you were using TypeScript you should have gotten an error.

But you might not be using TypeScript and number values are reasonable for plain numbered properties, so I think we should support this.

btw, you can choose an older version of lit-html with npm overrides: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

We use dependencies ranges in `lit` so that we reduce the chance of package duplication.

**Comment by dklemmt** [comment]
Hi @justinfagnani thanks for your quick reply. Unfortunately it's an old code base without TypeScript so nobody realized yet. Would be great if you could support this. We could just create a string before, but it might be easier and less error-prone for none TS users to add this little check into the code. And it might save some code, if you just need to do the check more than once. But it's up to you. :)

Ah I missed the override functionality. Will add it into our package.json and it should be fine.

Thank you very much :)
