### ISSUE TITLE
[labs/react]: react's event listener prevents lit component's event listener to fire

### ISSUE THREAD

**Issue by philSixZero** [lit/lit#3829]
### Which package(s) are affected?

React (@lit-labs/react)

### Description

During implementation of a lit component (`my-component`) and wrapping it to work in React, we encountered the issue that a `onClick` listener which is set directly on the `<MyComponent onClick={...}>` will hinder a click listener inside of the component to fire.

### Reproduction

Here the link to a [playground example](https://lit.dev/playground/#sample=examples%2Freact-events&project=W3sibmFtZSI6ImFwcC50c3giLCJjb250ZW50IjoiaW1wb3J0IHtSZWFjdCwgUmVhY3RET019IGZyb20gJy4vcmVhY3QuanMnO1xuaW1wb3J0IHtjcmVhdGVDb21wb25lbnR9IGZyb20gJ0BsaXQtbGFicy9yZWFjdCc7XG5pbXBvcnQge0NvdW50ZXJCdXR0b24gYXMgQ291bnRlckJ1dHRvbldDfSBmcm9tICcuL2NvdW50ZXItYnV0dG9uLmpzJztcblxuY29uc3QgQ291bnRlckJ1dHRvbiA9IGNyZWF0ZUNvbXBvbmVudCh7XG4gIHJlYWN0OiBSZWFjdCxcbiAgdGFnTmFtZTogJ2NvdW50ZXItYnV0dG9uJyxcbiAgZWxlbWVudENsYXNzOiBDb3VudGVyQnV0dG9uV0MsXG59KTtcblxuY29uc3Qge3VzZUNhbGxiYWNrLCB1c2VTdGF0ZX0gPSBSZWFjdDtcblxuZXhwb3J0IGNvbnN0IEFwcCA9ICgpID0-IHtcbiAgY29uc3QgW2NvdW50LCBzZXRDb3VudF0gPSB1c2VTdGF0ZSgwKTtcblxuICBjb25zdCBvbkNsaWNrID0gdXNlQ2FsbGJhY2soKCkgPT4gc2V0Q291bnQoY291bnQgKyAxKSwgW2NvdW50XSk7XG4gIGNvbnN0IG9uQ2xpY2syID0gdXNlQ2FsbGJhY2soKCkgPT4gc2V0Q291bnQoY291bnQgKyAxKSwgW2NvdW50XSk7XG5cbiAgcmV0dXJuIDxkaXY-XG4gICAgXG4gICAgPHA-TGlzdGVuZXIgb24gY29tcG9uZW50OjwvcD5cbiAgICA8Q291bnRlckJ1dHRvbiBvbkNsaWNrPXtvbkNsaWNrfSBjb3VudD17Y291bnR9PjwvQ291bnRlckJ1dHRvbj5cbiAgICBcbiAgICA8cD5ObyBsaXN0ZW5lcjwvcD5cbiAgICA8ZGl2PlxuICAgICA8Q291bnRlckJ1dHRvbj48L0NvdW50ZXJCdXR0b24-XG4gICAgPC9kaXY-XG4gICAgXG4gICAgPHA-PGI-V29ya2Fyb3VuZDwvYj46OjwvcD5cbiAgICA8ZGl2IG9uQ2xpY2s9e29uQ2xpY2syfT5cbiAgICAgPENvdW50ZXJCdXR0b24gY291bnQ9e2NvdW50fT48L0NvdW50ZXJCdXR0b24-XG4gICAgPC9kaXY-XG4gICAgXG4gICA8L2Rpdj47XG59O1xuXG5jb25zdCBub2RlID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcignI2FwcCcpO1xuY29uc3Qgcm9vdCA9IFJlYWN0RE9NLmNyZWF0ZVJvb3Qobm9kZSEpO1xuXG5yb290LnJlbmRlcig8QXBwPjwvQXBwPik7XG4ifSx7Im5hbWUiOiJjb3VudGVyLWJ1dHRvbi50cyIsImNvbnRlbnQiOiJpbXBvcnQgeyBodG1sLCBMaXRFbGVtZW50IH0gZnJvbSAnbGl0JztcbmltcG9ydCB7IGN1c3RvbUVsZW1lbnQsIHByb3BlcnR5LCBzdGF0ZSB9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ2NvdW50ZXItYnV0dG9uJylcbmV4cG9ydCBjbGFzcyBDb3VudGVyQnV0dG9uIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIEBwcm9wZXJ0eSh7IHR5cGU6IE51bWJlciB9KSBjb3VudCA9IDA7XG4gIEBzdGF0ZSgpIGludGVybmFsQ291bnQgPSAwO1xuICBvbkNsaWNrKGU6IE1vdXNlRXZlbnQpIHtcbiAgICB0aGlzLmludGVybmFsQ291bnQrKztcbiAgfVxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICA8YnV0dG9uIEBjbGljaz1cIiR7dGhpcy5vbkNsaWNrfVwiPmNsaWNrIGNvdW50OiAke3RoaXMuY291bnR9IC8gaW50ZXJuYWw6ICR7dGhpcy5pbnRlcm5hbENvdW50fTwvYnV0dG9uPlxuICAgIGA7XG4gIH1cbn1cbiJ9LHsibmFtZSI6InJlYWN0LnRzIiwiY29udGVudCI6Ii8vIGh0dHBzOi8vZ2l0aHViLmNvbS9mYWNlYm9vay9yZWFjdC9pc3N1ZXMvMTAwMjFcbmV4cG9ydCBjb25zdCBSZWFjdCA9ICh3aW5kb3cgYXMgYW55KS5SZWFjdDtcbmV4cG9ydCBjb25zdCBSZWFjdERPTSA9ICh3aW5kb3cgYXMgYW55KS5SZWFjdERPTTtcbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFkb2N0eXBlIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCBzcmM9XCJodHRwczovL3VucGtnLmNvbS9yZWFjdEAxOC91bWQvcmVhY3QuZGV2ZWxvcG1lbnQuanNcIj48L3NjcmlwdD5cbiAgPHNjcmlwdCBzcmM9XCJodHRwczovL3VucGtnLmNvbS9yZWFjdC1kb21AMTgvdW1kL3JlYWN0LWRvbS5kZXZlbG9wbWVudC5qc1wiPjwvc2NyaXB0PlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL2FwcC5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxkaXYgaWQ9XCJhcHBcIj48L2Rpdj5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0).

The internal counter is icremented by the component's listener, the other counter by react's listener. Clicking the button increments only the counter, not the internal counter. Now, if the `onClick` listener is removed from the react component, the internal counter starts to increment.

### Workaround

Mount the react `onClick` listener to a wrapper element of the web component and both listeners will fire as expected.

```jsx
<div onClick={...}>
  <MyComponent></MyComponent>
</div>
```

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.7.x

### Browser/OS/Node environment

Chrome & Firefox

**Comment by augustjk** [comment]
There's a couple thing contributing to this "event masking" effect.

The `@lit-labs/react` wrapper works by checking if a given prop exists on the the component class prototype and setting it on the instance. It has no special handling of props name that begin with "on" like "onClick". This means the actual `CounterButton.prototype.onClick` method that is meant to be added as an event handler simply gets overwritten by the the `onClick` function set on the instance.

Due to the ease by which this happens, the convention usually is to add `_` to these internal methods like `_onClick` or make it private like `#onClick`. Sometimes you'll see attempts to avoid further confusion by calling it something like `handleClick` as well without the "on" prefix. Doing any of these alleviates the "Listener on component" situation in the playground repro.

Another thing too is that if you want the `onClick` prop to actually work as an event handler for the "click" event on the wrapped component, you should add it to the `events` option when creating it.

```ts
const CounterButton = createComponent({
  react: React,
  tagName: 'counter-button',
  elementClass: CounterButtonWC,
  events: {
    onClick: 'click',
  }
});
```

This will make it such that the `onClick` prop passed to the component will specifically used as an event handler added with `addEventListener` on the element itself, and will not be set as a property on the element.

I realize the basis for the repro came from the React playground example so that should be updated.

**Comment by philSixZero** [comment]
Thank you for your detailed response @augustjk!

Two things are still unclear for me:
 - That means React sets the `CounterButton.prototype.onClick` when adding the `onClick` attribute? I always thought that it would do something like `addEventListener('click', method)` internally.
  - Why is the event not fired in the component, since the listener is set by using `@click` on a shadowDOM element and not on the  `CounterButton.prototype`? The example is not using `event.stopPropagation` or something in the React `onClick` listener.

**Comment by augustjk** [comment]
React does do the `addEventlistener('click', method)` thing but only for select events, and only for built-in browser components (https://react.dev/reference/react-dom/components/common#common-props). React also treats custom elements as built-in so if you just do the bare custom element tag in jsx like `<counter-button onClick={handleClick}></counter-button>` that actually works fine.

React does not treat `onClick` as a special thing if it's passed to a React component.

A React component made with `@lit-labs/react`, though, will take all props passed in and if it's found in the underlying custom element class's prototype, it will set it as a property on the element (which is an instance of the custom element class). Part of that code is here: https://github.com/lit/lit/blob/7932f7ddc21308dc0bf7b1bbd0dde781a6c8dece/packages/labs/react/src/create-component.ts#L278-L295

The problem with that in the way the playground example above is set up is that, the custom element class actually wants to use a method called `onClick` to be the function passed to the event listener.

```ts
// counter-button.ts
export class CounterButton extends LitElement {
  ...
  onClick(e: MouseEvent) {
    this.internalCount++;
  }

  render() {
    return html`
      <button @click="${this.onClick}">click count: ${this.count} / internal: ${this.internalCount}</button>
    `;
  }
}
```

The `onClick` here is added to the prototype of the `CounterButton` class, and `this.onClick` refers to that.

But, when you do `<CounterButton onClick={someOtherFunction}></CounterButton>`, the `this.onClick` within the `render` method ends up referring to `someOtherFunction`. So it's not that the event is not fired, the event is fired but the handler that gets called is different than what you expect.

Hence, one of the fix is to make sure there's no way to overwrite the internal event handler like:

```ts
// counter-button.ts
export class CounterButton extends LitElement {
  ...
  #onClick(e: MouseEvent) {
    this.internalCount++;
  }

  render() {
    return html`
      <button @click="${this.#onClick}">click count: ${this.count} / internal: ${this.internalCount}</button>
    `;
  }
}
```

The `#` makes it a [private field](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) so there's no risk of overriding that.

Alternatively, `@lit-labs/react` wrapped components have a way doing the special handling of props for event handlers, which is the `events` in the config object showed in my previous comment, which can make `onClick` passed to a React element actually be used as a click event handler.
