### ISSUE TITLE
[labs/virtualizer] Virtualizer renders the entire list of items multiple times when invisible 

### ISSUE THREAD

**Issue by jpzwarte** [lit/lit#3831]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

I have a combo-box component that uses `<lit-virtualizer>` in the overlay. See https://dna.iddinkgroup.com/?path=/story/core_forms-combo-box-examples--api to see the component in action.

The component containing the overlay is created at the same time as the combo-box component itself. So `<lit-virtualizer>` is also created at the same time. When the combo-box is inactive, the overlay is hidden.

Now I've noticed that in this scenario, the `renderItem` callback is called *multiple* times for the *entire list*. Perhaps this is due somehow to `<lit-virtualizer>`'s rendering logic not taking into account that it may not have a bounding rect yet?

### Reproduction

https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCAnQGxpdC1sYWJzL3ZpcnR1YWxpemVyJztcblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BwIHsgY29sb3I6IGJsdWUgfWA7XG5cbiAgbGlzdCA9IEFycmF5KDMwMDApLmZpbGwoKS5tYXAoKF8sIGluZGV4KSA9PiAoe1xuICAgIHVpZDogaW5kZXgsXG4gICAgbmFtZTogKE1hdGgucmFuZG9tKCkgKyAxKS50b1N0cmluZygzNikuc3Vic3RyaW5nKDcpXG4gIH0pKTtcbiAgXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxkaXYgc3R5bGU9XCJkaXNwbGF5Om5vbmVcIj5cbiAgICAgICAgPGxpdC12aXJ0dWFsaXplciAuaXRlbXM9JHt0aGlzLmxpc3R9IC5yZW5kZXJJdGVtPSR7dGhpcy5yZW5kZXJJdGVtfT48L2xpdC12aXJ0dWFsaXplcj5cbiAgICAgIDwvZGl2PlxuICAgIGA7XG4gIH1cbiAgXG4gIHJlbmRlckl0ZW0oaXRlbSkge1xuICAgIGNvbnNvbGUubG9nKCdyZW5kZXJJdGVtJywgaXRlbSk7XG4gICAgcmV0dXJuIGh0bWxgPGRpdj4ke2l0ZW0ubmFtZX08L2Rpdj5gO1xuICB9ICAgXG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZyBuYW1lPVwiV29ybGRcIj48L3NpbXBsZS1ncmVldGluZz5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0

### Workaround

I fixed this behavior by only rendering the `<lit-virtualizer>` when the overlay is open.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

0.7.2, 1.0.0 and 2.0.0

### Browser/OS/Node environment

-

**Comment by usergenic** [comment]
Thanks for filing this. We have no tests around a virtualizer in a display:none case! Your workaround sounds like the right one for now but we'll see if there might not be a way to identify and address the case in virtualizer's own render cycle.

**Comment by antoniogagos** [comment]
I have another issue related to `display: none`. I have large costly lists on different tabs. After the initial render, I want these lists retained when users switch between tabs.

The problem happens because under display: none, each children height will be 0, so the virtualizer assumes there's room for every item and renders them all. So in my case switching to another tab will create a node for every single item of my list.

This behavior can be seen in this example, where toggling the tree visibility using display none will keep adding nodes until all are complete: [bug example](https://lit.dev/playground/#project=W3sibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi90ZXN0LWxpc3QuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8dGVzdC1saXN0PjwvdGVzdC1saXN0PlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9LHsibmFtZSI6InRlc3QtbGlzdC50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHksIHN0YXRlfSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5pbXBvcnQgXCJodHRwczovL2VzbS5zaC9AbGl0LWxhYnMvdmlydHVhbGl6ZXJcIjtcblxuQGN1c3RvbUVsZW1lbnQoJ3Rlc3QtbGlzdCcpXG5leHBvcnQgY2xhc3MgVGVzdExpc3QgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BwIHsgY29sb3I6IGJsdWUgfWA7XG4gXG4gIEBwcm9wZXJ0eSh7YXR0cmlidXRlOiBmYWxzZX0pXG4gIGl0ZW1zOiBudW1iZXJbXSA9IG5ldyBBcnJheSgxMDAwKS5maWxsKG51bGwpLm1hcCgoXywgaWR4KSA9PiBpZHgpO1xuXG4gIHRvZ2dsZVRyZWVWaXNpYmlsaXR5KCkge1xuICAgIGNvbnN0IHZpcnR1YWxpemVyID0gdGhpcy5zaGFkb3dSb290LnF1ZXJ5U2VsZWN0b3I8SFRNTEVsZW1lbnQ-KCdsaXQtdmlydHVhbGl6ZXInKTtcbiAgICBjb25zdCB2aXNpYmxlID0gdmlydHVhbGl6ZXIuc3R5bGUuZGlzcGxheSAhPT0gJ25vbmUnO1xuICAgIGlmICh2aXNpYmxlKSB7XG4gICAgICB2aXJ0dWFsaXplci5zdHlsZS5zZXRQcm9wZXJ0eSgnZGlzcGxheScsICdub25lJyk7XG4gICAgfSBlbHNlIHtcbiAgICAgIHZpcnR1YWxpemVyLnN0eWxlLnJlbW92ZVByb3BlcnR5KCdkaXNwbGF5Jyk7XG4gICAgfVxuICB9XG4gIFxuICBAc3RhdGUoKVxuICBpdGVtc1JlbmRlcmVkID0gMDtcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICA8ZGl2IHN0eWxlPVwicG9zaXRpb246IHN0aWNreTsgdG9wOiAwOyBiYWNrZ3JvdW5kOiAjZmZmOyB6LWluZGV4OiAxOyBwYWRkaW5nLWJsb2NrOiAxcmVtO1wiPlxuICAgICAgICBDb25uZWN0ZWQgY2hpbGRyZW4gPSAke3RoaXMuaXRlbXNSZW5kZXJlZH1cblxuICAgICAgICA8YnV0dG9uIEBjbGljaz0ke3RoaXMudG9nZ2xlVHJlZVZpc2liaWxpdHl9PlRvZ2dsZSB0cmVlIHZpc2liaWxpdHk8L2J1dHRvbj5cbiAgICAgIDwvZGl2PlxuXG4gICAgICA8bGl0LXZpcnR1YWxpemVyXG4gICAgICAgIEByYW5nZUNoYW5nZWQ9JHtlID0-IHsgdGhpcy5pdGVtc1JlbmRlcmVkID0gZS5sYXN0IC0gZS5maXJzdDsgfX1cbiAgICAgICAgLml0ZW1zPSR7dGhpcy5pdGVtc31cbiAgICAgICAgLnJlbmRlckl0ZW09JHtpID0-IGh0bWxgPGRpdiBjbGFzcz1cIml0ZW1cIj4ke2l9PC9kaXY-YH0-XG4gICAgICA8L2xpdC12aXJ0dWFsaXplcj5cbiAgICBgO1xuICB9XG4gXG59XG4ifV0)

I'm not sure if there is a reliable way to check this (like looking at every ancestor, because I guess hostElement's size can't be checked). But if it's not an scenario that can be detected, maybe a "disable", "observersDisabled", "disableObservers", "enableObservers" properties or methods could be used. Without this my case for instance it's a major problem.
