### ISSUE TITLE
[labs/virtualizer/layout] lit virtualizer item change event doesn't propogate to auto update layout in case of a grid layout

### ISSUE THREAD

**Issue by TarunAdobe** [lit/lit#4080]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

Updating the items attribute doesn't update the layout of the grid for a component extending lit-virtualizer class. 
cc: @Westbrook 

### Reproduction

Please checkout this minimal reproduction of the bug [here](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCAnQGxpdC1sYWJzL3ZpcnR1YWxpemVyJztcbmltcG9ydCB7IExpdFZpcnR1YWxpemVyIH0gZnJvbSAnQGxpdC1sYWJzL3ZpcnR1YWxpemVyL0xpdFZpcnR1YWxpemVyLmpzJztcbmltcG9ydCB7Z3JpZH0gZnJvbSAnQGxpdC1sYWJzL3ZpcnR1YWxpemVyL2xheW91dHMvZ3JpZC5qcyc7XG5cbmludGVyZmFjZSBJdGVtIGV4dGVuZHMgUmVjb3JkPHN0cmluZywgdW5rbm93bj4ge1xuICAgIGlkOiBudW1iZXI7XG59XG5cbmZ1bmN0aW9uIGdlbmVyYXRlSXRlbXMoY291bnQ6IG51bWJlcik6IEl0ZW1bXSB7XG4gICAgY29uc3QgaXRlbXM6IEl0ZW1bXSA9IFtdO1xuICAgIHdoaWxlIChjb3VudCkge1xuICAgICAgICBjb3VudCAtPSAxO1xuICAgICAgICBpdGVtcy51bnNoaWZ0KHsgaWQ6IGNvdW50IH0pO1xuICAgIH1cbiAgICByZXR1cm4gaXRlbXM7XG59XG5cbmNvbnN0IHJlbmRlckl0ZW0gPSAoKTogVGVtcGxhdGVSZXN1bHQgPT4ge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgICA8ZGl2IHN0eWxlPVwiYm9yZGVyOiAycHggeWVsbG93IHNvbGlkOyBtYXJnaW46IDVweFwiPlxuICAgICAgICAgPGgzPmhlbGxvPC9oMz5cbiAgICAgICAgPC9kaXY-XG4gICAgYDtcbn07XG5cbkBjdXN0b21FbGVtZW50KCdzcC1ncmlkJylcbmV4cG9ydCBjbGFzcyBHcmlkIGV4dGVuZHMgTGl0VmlydHVhbGl6ZXIgeyBcbiAgXG4gIHByb3RlY3RlZCBvdmVycmlkZSB1cGRhdGUoY2hhbmdlczogYW55KTogdm9pZCB7XG4gICAgIGNvbnNvbGUubG9nKCdjaGFuZ2VzIGluIHRoZSB1cGRhdGUgRnVuY3Rpb246ICcsIGNoYW5nZXMpO1xuICAgICBzdXBlci51cGRhdGUoY2hhbmdlcyk7XG4gIH1cbiAgXG4gIHB1YmxpYyBvdmVycmlkZSByZW5kZXIoKTogYW55PDE-IHtcbiAgICAgICAgcmV0dXJuIGh0bWxgXG4gICAgICAgICAgICA8c2xvdD48L3Nsb3Q-XG4gICAgICAgIGBcbiAgIH07ICBcbn1cblxuY29uc3QgZ3JpZGQgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCdzcC1ncmlkJykgYXMgR3JpZDtcbmxldCBpdGVtcyA9IGdlbmVyYXRlSXRlbXMoMTApO1xuZ3JpZGQuaXRlbXMgPSBpdGVtcztcbmdyaWRkLnJlbmRlckl0ZW0gPSByZW5kZXJJdGVtO1xuZ3JpZGQubGF5b3V0ID0gZ3JpZCgpO1xuXG52YXIgYnV0dG9uID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudChcImJ1dHRvblwiKTtcbmJ1dHRvbi5pbm5lckhUTUwgPSBcIkRlbGV0ZVwiO1xuLy8gYnV0dG9uLm9uQ2xpY2sgPSBoYW5kbGVDbGljaztcbmJ1dHRvbi5hZGRFdmVudExpc3RlbmVyIChcImNsaWNrXCIsIGZ1bmN0aW9uKCkge1xuICBpdGVtcyA9IGl0ZW1zLnNsaWNlKDAsIGl0ZW1zLmxlbmd0aC0xKTtcbiAgZ3JpZGQuaXRlbXMgPSBpdGVtcztcbn0pO1xuXG52YXIgYm9keSA9IGRvY3VtZW50LmdldEVsZW1lbnRzQnlUYWdOYW1lKFwiYm9keVwiKVswXTtcbmJvZHkuYXBwZW5kQ2hpbGQoYnV0dG9uKTtcblxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzcC1ncmlkIHN0eWxlPVwiYm9yZGVyOiAzcHggc29saWQgcmVkXCI-PC9zcC1ncmlkPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ).
       
Steps to reproduce bug -
- Trying deleting a few elements using the delete button and notice how the layout still has extra white space after the element(s) is deleted

### Workaround

I haven't been able to find a workaround for this issue.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in all versions

### Browser/OS/Node environment

All Browsers

**Comment by graynorton** [comment]
This issue is a regression caused by the fix for https://github.com/lit/lit/issues/3052.

Reverting that fix makes this problem go away, but brings back the original issue (duh).

The solution is to have the `virtualize` directive's `update` method conditionally return either `noChange` or the output of its `render()` method (depending on whether `items` have changed or not); this produces the desired behavior in both cases.

Here's a modified Playground example that repros #4080 but also tests to make sure that #3052 remains fixed and that dynamic changes to the `renderItem()` method work as expected:

https://lit.dev/playground/#gist=50cd45bf2735538f8d599653c5852cef

I've confirmed locally that the following two-line change does the trick:

<img width="1162" alt="image" src="https://github.com/lit/lit/assets/32065/621c1772-fac9-48cf-81c8-1a406008a497">

I don't have time immediately to turn this fix into a PR; would probably be late this week or next at best, and honestly I'd be happiest if @usergenic or someone else currently working actively on Lit could take it from here. (I'd be happy to answer questions, hop on a VC, etc.)

**Comment by augustjk** [comment]
@graynorton It seems a bit counter-intuitive that you'd return `noChange` when items actually changed. What's the rationale for this? I can confirm it does fix the issue with a local repro, though I'm having trouble writing a test that correctly picks up on this.

**Comment by graynorton** [comment]
> It seems a bit counter-intuitive that you'd return `noChange` when items actually changed. What's the rationale for this?

Good question!

Prior to the fix for #3052, the `virtualize` directive never rendered its children as part of Lit's normal directive update lifecycle. Instead, it simply passed relevant config changes (e.g., changes to `items` and `layout`) through to its `Virtualizer` instance and waited to render its children until that `Virtualizer` instance emitted an internal `rangeChanged` event.

Conceptually, this was very clean: the directive completely delegated its rendering lifecycle to its `Virtualizer` instance. However, this meant that when state external to the Virtualizer config (anything other than `items` and `layout`, e.g. selection state) were supposed to affect the rendering of children, changes to that external state would not cause children to re-render as desired (because Virtualizer didn't know anything relevant had changed).

In the fix for #3052, we just allowed the directive to render its children both as part of the standard lifecycle *and* when directed by Virtualizer. This resulted in some redundant work, but the performance impact wasn't significant and it produced the desired behavior.

The problem reported in the current issue occurs because Virtualizer uses a MutationObserver (alongside a ResizeObserver) to drive its own internal update cycle; if this MutationObserver isn't triggered as expected, a cycle may not complete, and the DOM may not be updated as expected. In this case, the directive re-renders its children immediately as part of the standard directive update cycle (before Virtualizer reflows), then again after Virtualizer reflows...but the MutationObserver doesn't fire after the second render because the child elements rendered to the DOM are identical, and as a result the Virtualizer update cycle doesn't complete and the recalculated size of the host element never gets "flushed" to the DOM.

The rationale behind the proposed fix is to only let the directive render children in the standard directive lifecycle if it knows that a Virtualizer reflow will not occur.

I'm out of time for now, but wanted to share this much for your info. I checked out your branch and spent a bit of time this morning trying to figure out what the salient difference is between the automated test case and the manual test case I made in my Playground, but haven't yet figured it out.

**Comment by augustjk** [comment]
@graynorton this appears to solve the race condition in the test. https://github.com/lit/lit/pull/4108/commits/53df95ab9d29d33dcff1afe1eb0990cfc4ea72a3

Technically this on its own without the `noChange` return also fixes the original issue but I think it's worth to keep that to save some cycles and defer to virtualizer rendering when possible.

**Comment by graynorton** [comment]
@augustjk Nice! I will give your PR a proper review tonight or tomorrow morning.

**Comment by TarunAdobe** [comment]
Hey @graynorton any updates on this one...?

**Comment by augustjk** [comment]
@TarunAdobe The fix is now released in `@lit-labs/virtualizer@2.0.6`. Thank you for reporting!
