### ISSUE TITLE
[lit/react] React wrapped component typescript error with property named 'size' in Preact

### ISSUE THREAD

**Issue by ajmchambers** [lit/lit#4374]
### Which package(s) are affected?

React (@lit/react)

### Description

Getting a typescript error when using SlButton with [size](https://github.com/shoelace-style/shoelace/blob/next/src/components/button/button.component.ts#L64-L65) property in preact (react is fine).

```tsx
<SlButton size="small">Button</SlButton>
```

This is the text I see when hovering over size in vscode:

```
Type '"small"' is not assignable to type '((number | SignalLike<number | undefined>) & ("small" | "medium" | "large")) | undefined'.ts(2322)

jsx.d.ts(2316, 3): The expected type comes from property 'size' which is declared here on type 'IntrinsicAttributes & Omit<ComponentProps<SlButton, { onSlBlur: EventName<SlBlurEvent>; onSlFocus: EventName<SlFocusEvent>; onSlInvalid: EventName<SlInvalidEvent>; }>, "ref"> & RefAttributes<...> & Readonly<...>'

(property) size?: ((number | JSXInternal.SignalLike<number | undefined>) & ("small" | "medium" | "large")) | undefined
```

### Reproduction

Here is a stackblitz example:
https://stackblitz.com/edit/vitejs-vite-fhterf?file=src%2Fapp.tsx&terminal=dev

Note:
- modified vite preact typescript preset
- added preact/compat types to tsconfig

### Workaround

Can cast it as any to get rid of error:

```tsx
<SlButton size={"small" as any}>Button Text</SlButton>
```

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

lit: 3.0.2, @lit/react: 1.0.1

### Browser/OS/Node environment

Browser: Edge 119.0.2151.44
OS: Windows 11 23H2 22631.2506
Node: v18.18.0
npm: 9.4.2

**Comment by augustjk** [comment]
This looks specifically due to `preact`'s typing of `HTMLAttributes` which includes this line: https://github.com/preactjs/preact/blob/b4a1cc206b3519d80b931134933c917b0f08178c/src/jsx.d.ts#L2316

Probably wanting to account for https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/size

I don't see it in `@types/react`'s equivalent here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e2351cb03d18c520b908836dd38365efd563c104/types/react/index.d.ts#L1944

They rather include it specifically for the `InputElementAttributes` https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e2351cb03d18c520b908836dd38365efd563c104/types/react/index.d.ts#L2344

For our wrapped component props, we do an intersection type with `React.HTMLAttributes` because custom elements should be able to take any of those props that HTML elements can have. Here it happens to collide with a property defined on the custom element.

My initial reaction was that this should be fixed by preact's type to not include `size` in `HTMLAttributes`, but perhaps it's valid that any component defined props should override the built-in types, like we do for event handlers already.
https://github.com/lit/lit/blob/462350126d51d56f9211d50db43762d81a8b8ed1/packages/react/src/create-component.ts#L62-L69
