### ISSUE TITLE
After lit component createRenderRoot returns this, the slot is invalid.

### ISSUE THREAD

**Issue by ZengTianShengZ** [lit/lit#4422]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

After lit component createRenderRoot returns this, the slot is invalid.

### Reproduction

```js
export class GdWcButton extends LitElement {
    public createRenderRoot() {
        return this;
    }

    render() {
        return html`
            <div class="gdwc-button">
                <slot></slot>
            </div>
        `;
    }
}
```

use button

```html
<GdWcButton> xxx </GdWcButton>
```

xxx cannot be rendered into slot

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

"lit": "^3.1.0"

### Browser/OS/Node environment

chrome 114
macos
node v18

**Comment by augustjk** [comment]
Slots are a platform feature that only work with shadow DOM. Lit does not do anything special with them. Opting out of shadow DOM means opting out of slots too.

**Comment by AndrewJakubowicz** [comment]
Closing this issue because the `<slot>` element is a browser element and exists for projecting nodes into the shadow DOM. MDN has a great explainer: https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_templates_and_slots

You can still pass children without slots, but you'll have to do it via your own userland method. E.g. via element properties and Lit templates like this [Lit playground example](https://lit.dev/playground/#gist=7b07fea45877eaaefca16eaad5328beb).
