### ISSUE TITLE
Integrated with another framework

### ISSUE THREAD

**Issue by centratelemedia** [lit/lit#4469]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Other/unknown (please mention in description)

### Description

Can lit be integrated with other Web Components such as Web Components from https://www.htmlelements.com/demos/

### Alternatives and Workarounds

I don't have another alternate...

**Comment by sorvell** [comment]
In general, yes. Lit and web components in general are designed to be interoperable with each other. That said, individual frameworks may have specific requirements or expectations that limit their ability to seamlessly interoperate.

In particular, while [htmlelements](https://www.htmlelements.com/) publishes web components, they have some odd behaviors that limit interoperability. Specifically, it doesn't seem to me that they use the `slot` element for composition (see this [example](https://lit.dev/playground/#gist=7025c781a26d04af90b522a9b76ccb9b)).

Lit works well with major frameworks like react, angular, vue, svelte, etc. Lit based ui libraries like [shoelace](https://shoelace.style/) or [material](https://material-web.dev) are good options and sometimes offer framework specific integrations.

**Comment by centratelemedia** [comment]
@sorvell 

Thank you for the explanation and code examples, another question, why doesn't Lite provide features like createMemo, routing like in SolidJS, actually I really love SolidJS because in my trials, it can render 3000 items and update them sourced from WebSocket, and update Google markers smoothly... but solidjs has very minimal UI framework support, so I tried other alternatives such as lite, but I saw that lite doesn't provide many components such as routing, memos and others... please explain

**Comment by sorvell** [comment]
Lit is a library for building interoperable web components, not a framework for building web apps. Along with other tools and libraries, Lit can definitely be used to build complex applications. Check out [Lit's web site](https://lit.dev/) to learn more about its purpose and mission.

* memo: this is mostly needed to avoid expensive work in functional systems. Since web components are stateful objects, this is done a little differently: Lit has a [reactive update cycle](https://lit.dev/docs/components/lifecycle/#reactive-update-cycle) that provides methods to perform work (e.g. `shouldUpdate`, `willUpdate`, `updated`) selectively based on changes since the previous update.
* ecosystem: check out [awesome-lit](https://github.com/web-padawan/awesome-lit) for a curated list of resources.
* lit-labs and routing: check out [lit-labs](https://lit.dev/docs/libraries/labs/) for extended features that are in progress. There's a [router](https://www.npmjs.com/package/@lit-labs/router) under development, but there are other options as well like the [vaadin router](https://github.com/vaadin/router).
* components: as mentioned [shoelace](https://shoelace.style/) or [material](https://material-web.dev/) are good options

**Comment by centratelemedia** [comment]
@sorvell , thank for explanation
