### ISSUE TITLE
Error in createAttributeParts of hydrate-lit-html.js when attempting to server render a library component in Next.js

### ISSUE THREAD

**Issue by keisha-rw** [lit/lit#4477]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

My team is creating a design system of Lit components, which we export both as web components and React-wrapped web components.  We'd like to enable full SSR capabilities for the React wrapped components of our library at the very least, though eventually it'd be great to do both.

I've gotten to the point where I can see the DSD and things are mostly working as intended, but I'm hitting an `Unhandled runtime error` with the `hydrate-lit-html.js` script from @lit-labs/ssr-client when I include our primary-navigation component in a Next.js app.
![image](https://github.com/lit/lit/assets/49070129/bf1ce644-eb72-4457-9562-c6c5179befd4)

I'm having a hard time understanding what's causing this issue and I'd appreciate any insights you all might have.  I've included a reproduction to show what's going on.

Please let me know if you have any issues reproducing the issue or if I can help explain in more detail.

### Reproduction

You can find a stripped-down reproduction of our library here: https://github.com/keisha-rw/lit-components-lib
And a Next.js application that shows the issue can be found here: https://github.com/keisha-rw/next-learn
(Most of the time, our React consumers are using Next.js applications, so my repro is for Next.js.)

The README of the library explains how to view the issue (you should just need to pull down the repos and run the given commands). 

You can find the primary navigation component that hits this issue here: https://github.com/keisha-rw/lit-components-lib/blob/main/packages/web-components/src/lib/components/primary-navigation/primary-navigation.ts

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.1.5 (@lit-labs/ssr-client)

### Browser/OS/Node environment

Browser: any
Node version: 18.17.0
Next.js version: 14.0.4 (though it happens in v13 as well)

**Comment by augustjk** [comment]
Thanks for the repro! I located the source of the error to be the conditional render here: https://github.com/keisha-rw/lit-components-lib/blob/861d5b96899d5c775e61cace6386fbcfd34ab4f0/packages/web-components/src/lib/components/primary-navigation/primary-navigation.ts#L887-L888

The server render returns the template with `<pds-button>` but the client render returns `nothing`. The mismatch is causing the error during hydration.

Conditional rendering is tricky as we currently require an exact match between what was rendered on the server and the initial client render, especially trickier when slot detection is involved since we can't do that on the server :( . A workaround for now would be to make sure the initial client render is consistent with server render (either make server also return nothing or make initial client always render the fallback button) and do any updates client-side on the slotchange.

We haven't quite decided on a better way of handling these kinds of mismatch during hydration where an option might be to, instead of throwing like we currently do, blow away the server rendered DOM and recreate with the client result. https://github.com/lit/lit/issues/1434

BTW, I found the source of the error by adding a log of the `state` before throwing which included a reference to the comment node above the problematic part of the DOM. I'll work on improving the error there rather than the cryptic thrown `internal error`.

**Comment by keisha-rw** [comment]
You rock, @augustjk!  🎉  Thanks for taking the time to dig in and help me figure this one out.  Your description for how you figured out the problem will be immensely helpful as I work through this issue in a few other components.

I agree that blowing away the server-rendered DOM and recreating on the client might be a better option.  Perhaps you could then console.warn (or something similar) to let consumers know that you're using the client result.  Though that's a tough call to make since folks could easily miss that.

Regardless, thanks again for helping me work through this.  I appreciate all the work you've done to keep pushing SSR forward for lit components!

**Comment by augustjk** [comment]
I opened #4481 which will close this issue. It's not exactly a fix for handling the mismatch but should provide a clearer error message to help fix these scenarios with workarounds.

#1434 still remains an open task for us to decide on a strategy for a more graceful handling of hydration mismatch.
