### ISSUE TITLE
[ssr] Document design for lit-html SSR solution

### ISSUE THREAD

**Issue by kevinpschaaf** [lit/lit#931]

**Comment by MarkiyanPyts** [comment]
Guys for cloud platforms like SalesForce Commerce Cloud there is no possibility to use node or any other BD mainstream BD language, I would really appreciate if Google considered this working on SSR for lit-html. It would be a game changer for this kind of technology.

**Comment by frank-dspeed** [comment]
@MarkiyanPyts i am working on this and i am realy far if you want to discusse patterns for lit-html and ssr simply respond here.

The key things to know about lit-html and ssr
- you should not use lit-html for ssr but you should use something compatible for example lit-html-server 
- you should avoid directives and work with custom elements to do bindings

if you use lit-html for ssr then you will need a process on the server that does dom parsing and you will also need to handle async tasks. You will also need a cache solution for the results as the operation is expensiv.

**Comment by MarkiyanPyts** [comment]
Thanks for your reply, some time has passed since my initial question, SFCC is now moving towards headless architecture so in some time mainstream server side languages like node will be available for SSR.

I think first use cases of web components will be more related to functionality that does not require perfect SEO,

If we talk about big projects it will be vue (e.g nuxt) or react based ones but it would be awesome to have ability to mix web components in such apps, while still having some sane SSR mechanism which would work in tandem with Nuxt SSR for example

In my opinion web components at this point is great tool for industry to finally standardize way of building components but in course of next few years to gain popularity they need to play nice with mainstream frameworks as well

**Comment by aomarks** [comment]
Closing as we have released an SSR solution (https://github.com/lit/lit/tree/main/packages/labs/ssr)

Tracking the need for docs on lit.dev at https://github.com/lit/lit/issues/2435
